import type { AppLang } from '@/lib/language';

export type ChromeCopy = {
  desk: string;
  portals: string;
  also: string;
  verify: string;
  labs: string;
  file: string;
  assistant: string;
  home: string;
  privacy: string;
  terms: string;
  product: string;
  official: string;
  contact: string;
  blurb: string;
  published: string;
  address: string;
  langLabel: string;
  complaint: string;
  labSearch: string;
  lightMode: string;
  darkMode: string;
  updated: string;
};

const EN: ChromeCopy = {
  desk: 'Indian Standards desk',
  portals: 'Portals',
  also: 'Also on BIS',
  verify: 'Verify product',
  labs: 'Labs',
  file: 'Product file',
  assistant: 'Assistant',
  home: 'Home',
  privacy: 'Privacy',
  terms: 'Terms of service',
  product: 'Product',
  official: 'Official BIS',
  contact: 'Contact BIS',
  blurb: 'A navigation desk for Indian Standards and BIS services. It points to the official page, or it stops.',
  published: 'Published BIS contact. This desk does not receive licence applications.',
  address: 'Manak Bhavan, New Delhi',
  langLabel: 'Language',
  complaint: 'File a complaint',
  labSearch: 'Laboratory search',
  lightMode: 'Switch to light mode',
  darkMode: 'Switch to dark mode',
  updated: 'Last updated 25 September 2026',
};

function C(p: Partial<ChromeCopy>): ChromeCopy {
  return { ...EN, ...p };
}

const BY: Record<AppLang, ChromeCopy> = {
  en: EN,
  hi: C({
    desk: 'भारतीय मानकों की डेस्क',
    portals: 'पोर्टल',
    also: 'BIS पर और',
    verify: 'उत्पाद जाँचें',
    labs: 'प्रयोगशालाएँ',
    file: 'उत्पाद फ़ाइल',
    assistant: 'सहायक',
    home: 'होम',
    privacy: 'गोपनीयता',
    terms: 'सेवा की शर्तें',
    product: 'उत्पाद',
    official: 'आधिकारिक BIS',
    contact: 'BIS से संपर्क',
    blurb: 'भारतीय मानकों और BIS सेवाओं की डेस्क। आधिकारिक पेज बताती है, वरना रुक जाती है।',
    published: 'प्रकाशित BIS संपर्क। यह डेस्क लाइसेंस आवेदन नहीं लेती।',
    address: 'मानक भवन, नई दिल्ली',
    langLabel: 'भाषा',
    complaint: 'शिकायत दर्ज करें',
    labSearch: 'प्रयोगशाला खोज',
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
    updated: 'अंतिम अपडेट 25 सितंबर 2026',
  }),
  bn: C({
    desk: 'ভারতীয় মানের ডেস্ক',
    portals: 'পোর্টাল',
    also: 'BIS-এ আরও',
    verify: 'পণ্য যাচাই',
    labs: 'ল্যাব',
    file: 'পণ্য ফাইল',
    assistant: 'সহায়ক',
    home: 'হোম',
    privacy: 'গোপনীয়তা',
    terms: 'সেবার শর্ত',
    product: 'পণ্য',
    official: 'অফিসিয়াল BIS',
    contact: 'BIS-এ যোগাযোগ',
    blurb: 'ভারতীয় মান ও BIS সেবার ডেস্ক। অফিসিয়াল পাতা দেখায়, না হলে থামে।',
    published: 'প্রকাশিত BIS যোগাযোগ। এই ডেস্ক লাইসেন্স আবেদন নেয় না।',
    address: 'মানক ভবন, নতুন দিল্লি',
    langLabel: 'ভাষা',
    complaint: 'অভিযোগ জমা',
    labSearch: 'ল্যাব খোঁজ',
    lightMode: 'লাইট মোড',
    darkMode: 'ডার্ক মোড',
    updated: 'সর্বশেষ ২৫ সেপ্টেম্বর ২০২৬',
  }),
  ta: C({
    desk: 'இந்திய தர மேசை',
    portals: 'தளங்கள்',
    also: 'BIS-இல் மேலும்',
    verify: 'பொருளைச் சரிபார்',
    labs: 'ஆய்வகங்கள்',
    file: 'பொருள் கோப்பு',
    assistant: 'உதவியாளர்',
    home: 'முகப்பு',
    privacy: 'தனியுரிமை',
    terms: 'சேவை விதிகள்',
    product: 'பொருள்',
    official: 'அதிகாரப்பூர்வ BIS',
    contact: 'BIS தொடர்பு',
    blurb: 'இந்திய தரங்கள் மற்றும் BIS சேவைகளுக்கான மேசை. அதிகாரப்பூர்வ பக்கத்தைக் காட்டும், இல்லையென்றால் நிற்கும்.',
    published: 'வெளியிடப்பட்ட BIS தொடர்பு. இந்த மேசை உரிம விண்ணப்பத்தைப் பெறாது.',
    address: 'மானக் பவன், புது தில்லி',
    langLabel: 'மொழி',
    complaint: 'புகார் பதிவு',
    labSearch: 'ஆய்வகத் தேடல்',
    lightMode: 'வெளிர் பயன்முறை',
    darkMode: 'இருள் பயன்முறை',
    updated: 'கடைசி புதுப்பிப்பு 25 செப்டம்பர் 2026',
  }),
  te: C({
    desk: 'భారతీయ ప్రమాణాల డెస్క్',
    portals: 'పోర్టల్స్',
    also: 'BISలో ఇంకా',
    verify: 'ఉత్పత్తి తనిఖీ',
    labs: 'ప్రయోగశాలలు',
    file: 'ఉత్పత్తి ఫైల్',
    assistant: 'సహాయకుడు',
    home: 'హోమ్',
    privacy: 'గోప్యత',
    terms: 'సేవా నిబంధనలు',
    product: 'ఉత్పత్తి',
    official: 'అధికారిక BIS',
    contact: 'BIS సంప్రదింపు',
    blurb: 'భారతీయ ప్రమాణాలు మరియు BIS సేవల డెస్క్. అధికార పేజీ చూపిస్తుంది, లేకపోతే ఆగుతుంది.',
    published: 'ప్రచురిత BIS సంప్రదింపు. ఈ డెస్క్ లైసెన్సు దరఖాస్తులు తీసుకోదు.',
    address: 'మానక్ భవన్, న్యూ ఢిల్లీ',
    langLabel: 'భాష',
    complaint: 'ఫిర్యాదు దాఖలు',
    labSearch: 'ప్రయోగశాల శోధన',
    lightMode: 'లైట్ మోడ్',
    darkMode: 'డార్క్ మోడ్',
    updated: 'చివరి నవీకరణ 25 సెప్టెంబర్ 2026',
  }),
  mr: C({
    desk: 'भारतीय मानकांची डेस्क',
    portals: 'पोर्टल',
    also: 'BIS वर आणखी',
    verify: 'उत्पाद तपासा',
    labs: 'प्रयोगशाळा',
    file: 'उत्पाद फाइल',
    assistant: 'सहायक',
    home: 'मुखपृष्ठ',
    privacy: 'गोपनीयता',
    terms: 'सेवेच्या अटी',
    product: 'उत्पाद',
    official: 'अधिकृत BIS',
    contact: 'BIS संपर्क',
    blurb: 'भारतीय मानके आणि BIS सेवांची डेस्क. अधिकृत पान दाखवते, नाहीतर थांबते.',
    published: 'प्रकाशित BIS संपर्क. ही डेस्क परवाना अर्ज घेत नाही.',
    address: 'मानक भवन, नवी दिल्ली',
    langLabel: 'भाषा',
    complaint: 'तक्रार नोंदवा',
    labSearch: 'प्रयोगशाळा शोध',
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
    updated: 'शेवटचे अपडेट २५ सप्टेंबर २०२६',
  }),
  gu: C({
    desk: 'ભારતીય ધોરણોની ડેસ્ક',
    portals: 'પોર્ટલ',
    also: 'BIS પર વધુ',
    verify: 'ઉત્પાદન તપાસો',
    labs: 'પ્રયોગશાળાઓ',
    file: 'ઉત્પાદન ફાઇલ',
    assistant: 'સહાયક',
    home: 'હોમ',
    privacy: 'ગોપનીયતા',
    terms: 'સેવાની શરતો',
    product: 'ઉત્પાદન',
    official: 'અધિકૃત BIS',
    contact: 'BIS સંપર્ક',
    blurb: 'ભારતીય ધોરણો અને BIS સેવાઓની ડેસ્ક. અધિકૃત પાનું બતાવે, નહીંતર અટકે.',
    published: 'પ્રકાશિત BIS સંપર્ક. આ ડેસ્ક લાઇસન્સ અરજી લેતી નથી.',
    address: 'માનક ભવન, નવી દિલ્હી',
    langLabel: 'ભાષા',
    complaint: 'ફરિયાદ નોંધો',
    labSearch: 'પ્રયોગશાળા શોધ',
    lightMode: 'લાઇટ મોડ',
    darkMode: 'ડાર્ક મોડ',
    updated: 'છેલ્લું અપડેટ 25 સપ્ટેમ્બર 2026',
  }),
  kn: C({
    desk: 'ಭಾರತೀಯ ಮಾನದಂಡಗಳ ಮೇಜು',
    portals: 'ಪೋರ್ಟಲ್‌ಗಳು',
    also: 'BIS ನಲ್ಲಿ ಇನ್ನಷ್ಟು',
    verify: 'ಉತ್ಪನ್ನ ಪರಿಶೀಲನೆ',
    labs: 'ಪ್ರಯೋಗಾಲಯಗಳು',
    file: 'ಉತ್ಪನ್ನ ಕಡತ',
    assistant: 'ಸಹಾಯಕ',
    home: 'ಮುಖಪುಟ',
    privacy: 'ಗೌಪ್ಯತೆ',
    terms: 'ಸೇವಾ ನಿಬಂಧನೆಗಳು',
    product: 'ಉತ್ಪನ್ನ',
    official: 'ಅಧಿಕೃತ BIS',
    contact: 'BIS ಸಂಪರ್ಕ',
    blurb: 'ಭಾರತೀಯ ಮಾನದಂಡಗಳು ಮತ್ತು BIS ಸೇವೆಗಳ ಮೇಜು. ಅಧಿಕೃತ ಪುಟ ತೋರಿಸುತ್ತದೆ, ಇಲ್ಲದಿದ್ದರೆ ನಿಲ್ಲುತ್ತದೆ.',
    published: 'ಪ್ರಕಟಿತ BIS ಸಂಪರ್ಕ. ಈ ಮೇಜು ಪರವಾನಗಿ ಅರ್ಜಿ ಸ್ವೀಕರಿಸುವುದಿಲ್ಲ.',
    address: 'ಮಾನಕ್ ಭವನ, ನವದೆಹಲಿ',
    langLabel: 'ಭಾಷೆ',
    complaint: 'ದೂರು ಸಲ್ಲಿಸಿ',
    labSearch: 'ಪ್ರಯೋಗಾಲಯ ಹುಡುಕಾಟ',
    lightMode: 'ಬೆಳಕಿನ ಸ್ಥಿತಿ',
    darkMode: 'ಕತ್ತಲ ಸ್ಥಿತಿ',
    updated: 'ಕೊನೆಯ ನವೀಕರಣ 25 ಸೆಪ್ಟೆಂಬರ್ 2026',
  }),
  ml: C({
    desk: 'ഇന്ത്യൻ മാനദണ്ഡ ഡെസ്ക്',
    portals: 'പോർട്ടലുകൾ',
    also: 'BIS-ൽ കൂടുതൽ',
    verify: 'ഉൽപ്പന്നം പരിശോധിക്കുക',
    labs: 'ലാബുകൾ',
    file: 'ഉൽപ്പന്ന ഫയൽ',
    assistant: 'സഹായി',
    home: 'ഹോം',
    privacy: 'സ്വകാര്യത',
    terms: 'സേവന നിബന്ധനകൾ',
    product: 'ഉൽപ്പന്നം',
    official: 'ഔദ്യോഗിക BIS',
    contact: 'BIS ബന്ധം',
    blurb: 'ഇന്ത്യൻ മാനദണ്ഡങ്ങളും BIS സേവനങ്ങളും ഉള്ള ഡെസ്ക്. ഔദ്യോഗിക പേജ് കാണിക്കും, ഇല്ലെങ്കിൽ നിൽക്കും.',
    published: 'പ്രസിദ്ധീകരിച്ച BIS ബന്ധം. ഈ ഡെസ്ക് ലൈസൻസ് അപേക്ഷ സ്വീകരിക്കില്ല.',
    address: 'മാനക് ഭവൻ, ന്യൂ ഡൽഹി',
    langLabel: 'ഭാഷ',
    complaint: 'പരാതി നൽകുക',
    labSearch: 'ലാബ് തിരയൽ',
    lightMode: 'ലൈറ്റ് മോഡ്',
    darkMode: 'ഡാർക്ക് മോഡ്',
    updated: 'അവസാനം പുതുക്കിയത് 25 സെപ്റ്റംബർ 2026',
  }),
  pa: C({
    desk: 'ਭਾਰਤੀ ਮਾਪਦੰਡਾਂ ਦੀ ਡੈਸਕ',
    portals: 'ਪੋਰਟਲ',
    also: 'BIS ਉੱਤੇ ਹੋਰ',
    verify: 'ਉਤਪਾਦ ਜਾਂਚੋ',
    labs: 'ਪ੍ਰਯੋਗਸ਼ਾਲਾਵਾਂ',
    file: 'ਉਤਪਾਦ ਫ਼ਾਈਲ',
    assistant: 'ਸਹਾਇਕ',
    home: 'ਘਰ',
    privacy: 'ਗੋਪਨੀਯਤਾ',
    terms: 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ',
    product: 'ਉਤਪਾਦ',
    official: 'ਅਧਿਕਾਰਤ BIS',
    contact: 'BIS ਸੰਪਰਕ',
    blurb: 'ਭਾਰਤੀ ਮਾਪਦੰਡਾਂ ਅਤੇ BIS ਸੇਵਾਵਾਂ ਦੀ ਡੈਸਕ। ਅਧਿਕਾਰਤ ਪੰਨਾ ਦੱਸਦੀ ਹੈ, ਨਹੀਂ ਤਾਂ ਰੁਕ ਜਾਂਦੀ ਹੈ।',
    published: 'ਪ੍ਰਕਾਸ਼ਿਤ BIS ਸੰਪਰਕ। ਇਹ ਡੈਸਕ ਲਾਇਸੰਸ ਅਰਜ਼ੀ ਨਹੀਂ ਲੈਂਦੀ।',
    address: 'ਮਾਨਕ ਭਵਨ, ਨਵੀਂ ਦਿੱਲੀ',
    langLabel: 'ਭਾਸ਼ਾ',
    complaint: 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
    labSearch: 'ਪ੍ਰਯੋਗਸ਼ਾਲਾ ਖੋਜ',
    lightMode: 'ਲਾਈਟ ਮੋਡ',
    darkMode: 'ਡਾਰਕ ਮੋਡ',
    updated: 'ਆਖ਼ਰੀ ਅੱਪਡੇਟ 25 ਸਤੰਬਰ 2026',
  }),
  ur: C({
    desk: 'بھارتی معیارات کی ڈیسک',
    portals: 'پورٹل',
    also: 'BIS پر مزید',
    verify: 'مصنوع جانچیں',
    labs: 'تجربہ گاہیں',
    file: 'مصنوع فائل',
    assistant: 'معاون',
    home: 'ہوم',
    privacy: 'رازداری',
    terms: 'خدمات کی شرائط',
    product: 'مصنوع',
    official: 'سرکاری BIS',
    contact: 'BIS رابطہ',
    blurb: 'بھارتی معیارات اور BIS خدمات کی ڈیسک۔ سرکاری صفحہ بتاتی ہے، ورنہ رک جاتی ہے۔',
    published: 'شائع شدہ BIS رابطہ۔ یہ ڈیسک لائسنس درخواست نہیں لیتی۔',
    address: 'مانک بھون، نئی دہلی',
    langLabel: 'زبان',
    complaint: 'شکایت درج کریں',
    labSearch: 'لیب تلاش',
    lightMode: 'لائٹ موڈ',
    darkMode: 'ڈارک موڈ',
    updated: 'آخری تازہ کاری 25 ستمبر 2026',
  }),
  or: C({
    desk: 'ଭାରତୀୟ ମାନକ ଡେସ୍କ',
    portals: 'ପୋର୍ଟାଲ',
    also: 'BIS ରେ ଆହୁରି',
    verify: 'ଉତ୍ପାଦ ଯାଞ୍ଚ',
    labs: 'ପରୀକ୍ଷାଗାର',
    file: 'ଉତ୍ପାଦ ଫାଇଲ',
    assistant: 'ସହାୟକ',
    home: 'ହୋମ',
    privacy: 'ଗୋପନୀୟତା',
    terms: 'ସେବା ସର୍ତ୍ତ',
    product: 'ଉତ୍ପାଦ',
    official: 'ଅଧିକୃତ BIS',
    contact: 'BIS ଯୋଗାଯୋଗ',
    blurb: 'ଭାରତୀୟ ମାନକ ଓ BIS ସେବାର ଡେସ୍କ। ଅଧିକୃତ ପୃଷ୍ଠା ଦେଖାଏ, ନହେଲେ ଅଟକେ।',
    published: 'ପ୍ରକାଶିତ BIS ଯୋଗାଯୋଗ। ଏହି ଡେସ୍କ ଲାଇସେନ୍ସ ଆବେଦନ ନିଏ ନାହିଁ।',
    address: 'ମାନକ ଭବନ, ନୂଆ ଦିଲ୍ଲୀ',
    langLabel: 'ଭାଷା',
    complaint: 'ଅଭିଯୋଗ ଦାଖଲ',
    labSearch: 'ପରୀକ୍ଷାଗାର ସନ୍ଧାନ',
    lightMode: 'ଲାଇଟ୍ ମୋଡ୍',
    darkMode: 'ଡାର୍କ ମୋଡ୍',
    updated: 'ଶେଷ ଅପଡେଟ୍ 25 ସେପ୍ଟେମ୍ବର 2026',
  }),
};

export function chromeCopy(lang: AppLang): ChromeCopy {
  return BY[lang] ?? EN;
}
