export const APP_LANGS = [
  { id: "en", native: "English", speech: "en-IN", prompt: "English" },
  { id: "hi", native: "हिन्दी", speech: "hi-IN", prompt: "Hindi (Devanagari)" },
  { id: "bn", native: "বাংলা", speech: "bn-IN", prompt: "Bengali (Bangla script)" },
  { id: "ta", native: "தமிழ்", speech: "ta-IN", prompt: "Tamil" },
  { id: "te", native: "తెలుగు", speech: "te-IN", prompt: "Telugu" },
  { id: "mr", native: "मराठी", speech: "mr-IN", prompt: "Marathi (Devanagari)" },
  { id: "gu", native: "ગુજરાતી", speech: "gu-IN", prompt: "Gujarati" },
  { id: "kn", native: "ಕನ್ನಡ", speech: "kn-IN", prompt: "Kannada" },
  { id: "ml", native: "മലയാളം", speech: "ml-IN", prompt: "Malayalam" },
  { id: "pa", native: "ਪੰਜਾਬੀ", speech: "pa-IN", prompt: "Punjabi (Gurmukhi)" },
  { id: "ur", native: "اردو", speech: "ur-IN", prompt: "Urdu (Nastaliq)" },
  { id: "or", native: "ଓଡ଼ିଆ", speech: "or-IN", prompt: "Odia" },
] as const;

export type AppLang = (typeof APP_LANGS)[number]["id"];

const LANG_IDS = new Set<string>(APP_LANGS.map((l) => l.id));

export function isAppLang(v: string | undefined | null): v is AppLang {
  return !!v && LANG_IDS.has(v);
}

export function langPromptName(lang: AppLang): string {
  return APP_LANGS.find((l) => l.id === lang)?.prompt || "English";
}

export function speechLang(lang: AppLang): string {
  return APP_LANGS.find((l) => l.id === lang)?.speech || "en-IN";
}

/** Script helper only. Do not auto-switch the UI language from typed text. */
export function detectLanguage(text: string, current: AppLang = "en"): AppLang {
  if (/[\u0900-\u097F]/.test(text)) return current === "mr" ? "mr" : "hi";
  return current;
}

export type UiPack = {
  disclaimer: string;
  instruction: string;
  micDenied: string;
  micUnsupported: string;
  micWaiting: string;
  errorServer: string;
  welcomeTitle: string;
  welcomeDesc: string;
  thinking: string;
  sources: string;
  documents: string;
  highConf: string;
  medConf: string;
  lowConf: string;
  followUp: string;
  contextHelper: string;
  relatedStandards: string;
  certRoadmap: string;
  understandingPurity: string;
  huidLookup: string;
  enterHuid: string;
  verifyJeweller: string;
  quickLinks: string;
  recentChats: string;
  shareConversation: string;
  shareNoContent: string;
  shareSuccess: string;
  bookmarks: string;
  noBookmarks: string;
  bookmarkAdded: string;
  bookmarkRemoved: string;
  offlineTitle: string;
  offlineDesc: string;
  cachedHistoryBadge: string;
  micListening: string;
  micNoSpeech: string;
  micNetworkError: string;
  composerPlaceholder: string;
  listeningPlaceholder: string;
  stopDone: string;
  jumpLatest: string;
  speakTitle: string;
  writingResponse: string;
  internetRestored: string;
  sourceBacked: string;
  emptyQuery: string;
  catalogueLoadError: string;
  exported: string;
  exportFailed: string;
  retry: string;
  copyLabel: string;
  copiedLabel: string;
  confidenceHint: string;
  you: string;
  attach: string;
  exportLabel: string;
  pngReadError: string;
  fileType: string;
  shareHeading: string;
  errorTitle: string;
  errorFallback: string;
  privacyHint: string;
  chipHuid: string;
  chipCement: string;
  chipLaptop: string;
  sendLabel: string;
};

export type FallbackShell = {
  title: string;
  refuse: string;
  kysHint: string;
  headingApplicable: string;
  headingNot: string;
  notBody: string;
  schemePrefix: string;
  followYes: string;
  followNo: string;
};

const EN: UiPack = {
  disclaimer: "Catalogue metadata from public BIS sources. Not legal advice. Re-check live portals for fees and QCO status.",
  instruction: "Ask your question or describe your product...",
  micDenied: "Microphone permission denied. Please allow it in your browser settings.",
  micUnsupported: "Your browser does not support speech recognition. Please use Google Chrome.",
  micWaiting: "Waiting for microphone permission...",
  errorServer: "Sorry, there was an error connecting to the server.",
  welcomeTitle: "Namaste! I am ManakMitra",
  welcomeDesc: "Ask about Indian Standards, ISI / CRS certification, hallmarking, labs, and consumer queries.",
  thinking: "ManakMitra is thinking...",
  sources: "Sources",
  documents: "documents",
  highConf: "High",
  medConf: "Needs verification",
  lowConf: "Insufficient evidence",
  followUp: "Suggested next question",
  contextHelper: "Official links",
  relatedStandards: "Related Standards",
  certRoadmap: "Certification Roadmap",
  understandingPurity: "Hallmark purity marks",
  huidLookup: "HUID help",
  enterHuid: "HUID is verified in the official BIS CARE app",
  verifyJeweller: "Open BIS CARE / HUID help",
  quickLinks: "Quick Links",
  recentChats: "Recent Chats",
  shareConversation: "Share Conversation",
  shareNoContent: "No conversation to share.",
  shareSuccess: "Conversation copied to clipboard!",
  bookmarks: "Bookmarks",
  noBookmarks: "No saved messages yet.",
  bookmarkAdded: "Message bookmarked!",
  bookmarkRemoved: "Bookmark removed.",
  offlineTitle: "Offline / Limited Connectivity",
  offlineDesc: "You are offline. Sending a new question needs a connection.",
  cachedHistoryBadge: "Offline",
  micListening: "Listening... speak now",
  micNoSpeech: "No speech detected. Tap mic to speak again.",
  micNetworkError: "Speech recognition requires an active internet connection.",
  composerPlaceholder: "Talk with ManakMitra...",
  listeningPlaceholder: "Listening... your words will appear here",
  stopDone: "Stop listening",
  jumpLatest: "Latest",
  speakTitle: "Speak to type",
  writingResponse: "ManakMitra is writing a response...",
  internetRestored: "Internet connection restored.",
  sourceBacked: "Source-backed answers",
  emptyQuery: "Please enter your question.",
  catalogueLoadError: "I could not load the BIS catalogue just then. Please try again or use Know Your Standard.",
  exported: "Conversation saved.",
  exportFailed: "Could not export.",
  retry: "Try again",
  copyLabel: "Copy",
  copiedLabel: "Copied",
  confidenceHint: "Based on the official BIS catalogue",
  you: "You",
  attach: "Attach a PNG or a text file",
  exportLabel: "Export",
  pngReadError: "That file could not be read.",
  fileType: "Only a PNG or a text file (.txt, .md, .csv, .json) is allowed.",
  shareHeading: "ManakMitra conversation",
  errorTitle: "Something went wrong",
  errorFallback: "An unexpected error occurred. Try reloading the page.",
  privacyHint: "Do not paste confidential documents or personal information.",
  chipHuid: "Verify HUID on gold jewellery",
  chipCement: "ISI licence for cement",
  chipLaptop: "CRS registration for laptops",
  sendLabel: "Send",
};

function pack(p: Partial<UiPack>): UiPack {
  return { ...EN, ...p };
}

export const UI_DICTIONARY: Record<AppLang, UiPack> = {
  en: EN,
  hi: pack({
    disclaimer: "यह सार्वजनिक BIS कैटलॉग मेटाडेटा पर आधारित है। यह कानूनी सलाह नहीं है। शुल्क और QCO स्थिति लाइव पोर्टल पर जाँचें।",
    instruction: "अपना सवाल पूछें या प्रोडक्ट बताएं...",
    micDenied: "माइक्रोफ़ोन की अनुमति अस्वीकार कर दी गई है। कृपया अपने ब्राउज़र में अनुमति दें।",
    micUnsupported: "आपका ब्राउज़र स्पीच रिकग्निशन को सपोर्ट नहीं करता है। कृपया Google Chrome का उपयोग करें।",
    micWaiting: "माइक्रोफ़ोन अनुमति की प्रतीक्षा की जा रही है...",
    errorServer: "क्षमा करें, सर्वर से जुड़ने में त्रुटि हुई। कृपया पुनः प्रयास करें।",
    welcomeTitle: "नमस्ते! मैं मानक-मित्र हूँ",
    welcomeDesc: "भारतीय मानक, ISI / CRS प्रमाणन, हॉलमार्क, लैब और उपभोक्ता प्रश्नों में मदद करता हूँ।",
    thinking: "मानक-मित्र सोच रहा है...",
    sources: "स्रोत",
    documents: "दस्तावेज़",
    highConf: "उच्च",
    medConf: "सत्यापन आवश्यक",
    lowConf: "अपर्याप्त साक्ष्य",
    followUp: "सुझाया गया अगला सवाल",
    contextHelper: "आधिकारिक लिंक",
    relatedStandards: "संबंधित मानक",
    certRoadmap: "प्रमाणन रोडमैप",
    understandingPurity: "हॉलमार्क शुद्धता चिह्न",
    huidLookup: "HUID सहायता",
    enterHuid: "HUID आधिकारिक BIS CARE ऐप में सत्यापित होता है",
    verifyJeweller: "BIS CARE / HUID सहायता खोलें",
    quickLinks: "त्वरित लिंक",
    recentChats: "हाल की बातचीत",
    shareConversation: "बातचीत साझा करें",
    shareNoContent: "साझा करने के लिए कोई बातचीत नहीं है।",
    shareSuccess: "बातचीत क्लिपबोर्ड पर कॉपी हो गई!",
    bookmarks: "बुकमार्क",
    noBookmarks: "अभी कोई सहेजा संदेश नहीं।",
    bookmarkAdded: "संदेश बुकमार्क हो गया!",
    bookmarkRemoved: "बुकमार्क हटाया गया।",
    offlineTitle: "ऑफ़लाइन / सीमित कनेक्टिवटी",
    offlineDesc: "आप ऑफ़लाइन हैं। नया सवाल भेजने के लिए कनेक्शन चाहिए।",
    cachedHistoryBadge: "ऑफ़लाइन",
    micListening: "सुन रहा हूँ... अब बोलिए",
    micNoSpeech: "कोई आवाज़ नहीं मिली। दोबारा बोलने के लिए माइक दबाएं।",
    micNetworkError: "आवाज़ पहचानने के लिए इंटरनेट कनेक्शन आवश्यक है।",
    composerPlaceholder: "मानक-मित्र से बात करें...",
    listeningPlaceholder: "बोलिए... आपकी आवाज़ टेक्स्ट में बदल रही है",
    stopDone: "सुनना बंद करें",
    jumpLatest: "नवीनतम",
    speakTitle: "बोलकर लिखें",
    writingResponse: "मानक-मित्र उत्तर तैयार कर रहा है...",
    internetRestored: "इंटरनेट कनेक्शन पुनः सक्रिय हो गया है।",
    sourceBacked: "स्रोत-आधारित उत्तर",
    emptyQuery: "कृपया अपना प्रश्न दर्ज करें।",
    catalogueLoadError: "अभी BIS कैटलॉग लोड नहीं हो पाया। कृपया फिर कोशिश करें या Know Your Standard इस्तेमाल करें।",
  }),
  bn: pack({
    disclaimer: "এটি পাবলিক BIS ক্যাটালগ মেটাডেটার উপর ভিত্তি করে। আইনি পরামর্শ নয়। ফি ও QCO স্ট্যাটাস লাইভ পোর্টালে দেখুন।",
    instruction: "আপনার প্রশ্ন লিখুন বা পণ্যের নাম বলুন...",
    micDenied: "মাইক্রোফোনের অনুমতি দেওয়া হয়নি। ব্রাউজার সেটিংসে অনুমতি দিন।",
    micUnsupported: "আপনার ব্রাউজার স্পিচ রিকগনিশন সাপোর্ট করে না। Google Chrome ব্যবহার করুন।",
    micWaiting: "মাইক্রোফোন অনুমতির অপেক্ষা...",
    errorServer: "সার্ভারের সাথে সংযোগে সমস্যা হয়েছে। আবার চেষ্টা করুন।",
    welcomeTitle: "নমস্কার! আমি মানক-মিত্র",
    welcomeDesc: "ভারতীয় স্ট্যান্ডার্ড, ISI / CRS সার্টিফিকেশন, হলমার্ক, ল্যাব ও ভোক্তা প্রশ্নে সাহায্য করি।",
    thinking: "মানক-মিত্র ভাবছে...",
    sources: "সূত্র",
    documents: "নথি",
    highConf: "উচ্চ",
    medConf: "যাচাই প্রয়োজন",
    lowConf: "পর্যাপ্ত প্রমাণ নেই",
    followUp: "পরবর্তী প্রশ্ন",
    contextHelper: "অফিসিয়াল লিংক",
    relatedStandards: "সম্পর্কিত স্ট্যান্ডার্ড",
    certRoadmap: "সার্টিফিকেশন রোডম্যাপ",
    understandingPurity: "হলমার্ক বিশুদ্ধতা চিহ্ন",
    huidLookup: "HUID সহায়তা",
    enterHuid: "HUID অফিসিয়াল BIS CARE অ্যাপে যাচাই হয়",
    verifyJeweller: "BIS CARE / HUID সহায়তা খুলুন",
    quickLinks: "দ্রুত লিংক",
    shareConversation: "কথোপকথন শেয়ার করুন",
    shareNoContent: "শেয়ার করার মতো কথোপকথন নেই।",
    shareSuccess: "কথোপকথন ক্লিপবোর্ডে কপি হয়েছে!",
    offlineTitle: "অফলাইন / সীমিত সংযোগ",
    offlineDesc: "আপনি অফলাইন। নতুন প্রশ্ন পাঠাতে সংযোগ দরকার।",
    cachedHistoryBadge: "অফলাইন",
    micListening: "শুনছি... এখন বলুন",
    micNoSpeech: "কোনো কথা শোনা যায়নি। আবার মাইক চাপুন।",
    micNetworkError: "কণ্ঠ চেনার জন্য ইন্টারনেট দরকার।",
    composerPlaceholder: "মানক-মিত্রের সাথে কথা বলুন...",
    listeningPlaceholder: "বলুন... আপনার কথা লেখায় আসবে",
    stopDone: "শোনা বন্ধ করুন",
    jumpLatest: "সর্বশেষ",
    speakTitle: "বলে লিখুন",
    writingResponse: "মানক-মিত্র উত্তর লিখছে...",
    internetRestored: "ইন্টারনেট সংযোগ ফিরেছে।",
    sourceBacked: "সূত্র-ভিত্তিক উত্তর",
    emptyQuery: "অনুগ্রহ করে আপনার প্রশ্ন লিখুন।",
    catalogueLoadError: "BIS ক্যাটালগ লোড হয়নি। আবার চেষ্টা করুন বা Know Your Standard ব্যবহার করুন।",
  }),
  ta: pack({
    disclaimer: "இது பொது BIS பட்டியல் மெட்டாடேட்டா. சட்ட ஆலோசனை அல்ல. கட்டணம் மற்றும் QCO நிலையை நேரடி போர்ட்டலில் பார்க்கவும்.",
    instruction: "உங்கள் கேள்வியை எழுதுங்கள் அல்லது பொருளை விவரிக்கவும்...",
    micDenied: "மைக்ரோஃபோன் அனுமதி மறுக்கப்பட்டது. உலாவி அமைப்புகளில் அனுமதிக்கவும்.",
    micUnsupported: "உங்கள் உலாவி பேச்சு அறிதலை ஆதரிக்காது. Google Chrome பயன்படுத்தவும்.",
    micWaiting: "மைக்ரோஃபோன் அனுமதிக்காக காத்திருக்கிறது...",
    errorServer: "சேவையகத்துடன் இணைப்பில் பிழை. மீண்டும் முயற்சிக்கவும்.",
    welcomeTitle: "வணக்கம்! நான் மாநக்-மித்ரா",
    welcomeDesc: "இந்திய தரங்கள், ISI / CRS சான்றிதழ், ஹால்மார்க், ஆய்வகங்கள் மற்றும் நுகர்வோர் கேள்விகளுக்கு உதவுகிறேன்.",
    thinking: "மாநக்-மித்ரா யோசிக்கிறது...",
    sources: "ஆதாரங்கள்",
    documents: "ஆவணங்கள்",
    highConf: "உயர்",
    medConf: "சரிபார்ப்பு தேவை",
    lowConf: "போதிய சான்று இல்லை",
    followUp: "அடுத்த கேள்வி",
    contextHelper: "அதிகாரப்பூர்வ இணைப்புகள்",
    relatedStandards: "தொடர்புடைய தரங்கள்",
    certRoadmap: "சான்றிதழ் வழி",
    understandingPurity: "ஹால்மார்க் தூய்மை குறியீடுகள்",
    huidLookup: "HUID உதவி",
    enterHuid: "HUID அதிகாரப்பூர்வ BIS CARE செயலியில் சரிபார்க்கப்படும்",
    verifyJeweller: "BIS CARE / HUID உதவியை திறக்கவும்",
    quickLinks: "விரைவு இணைப்புகள்",
    shareConversation: "உரையாடலைப் பகிரவும்",
    shareNoContent: "பகிர உரையாடல் இல்லை.",
    shareSuccess: "உரையாடல் நகலெடுக்கப்பட்டது!",
    offlineTitle: "ஆஃப்லைன் / வரம்புள்ள இணைப்பு",
    offlineDesc: "நீங்கள் ஆஃப்லைன். புதிய கேள்விக்கு இணைப்பு தேவை.",
    cachedHistoryBadge: "ஆஃப்லைன்",
    micListening: "கேட்கிறேன்... இப்போது பேசுங்கள்",
    micNoSpeech: "பேச்சு கிடைக்கவில்லை. மீண்டும் மைக்கை அழுத்தவும்.",
    micNetworkError: "பேச்சு அறிதலுக்கு இணையம் தேவை.",
    composerPlaceholder: "மாநக்-மித்ராவிடம் பேசுங்கள்...",
    listeningPlaceholder: "பேசுங்கள்... உங்கள் வார்த்தைகள் இங்கே வரும்",
    stopDone: "கேட்பதை நிறுத்து",
    jumpLatest: "சமீபத்திய",
    speakTitle: "பேசி எழுதவும்",
    writingResponse: "மாநக்-மித்ரா பதில் எழுதுகிறது...",
    internetRestored: "இணைய இணைப்பு மீண்டது.",
    sourceBacked: "ஆதார அடிப்படையிலான பதில்கள்",
    emptyQuery: "தயவுசெய்து உங்கள் கேள்வியை உள்ளிடவும்.",
    catalogueLoadError: "BIS பட்டியல் ஏற்றப்படவில்லை. மீண்டும் முயற்சிக்கவும் அல்லது Know Your Standard பயன்படுத்தவும்.",
  }),
  te: pack({
    disclaimer: "ఇది పబ్లిక్ BIS కేటలాగ్ మెటాడేటా. న్యాయ సలహా కాదు. ఫీజు మరియు QCO స్థితిని లైవ్ పోర్టల్‌లో చూడండి.",
    instruction: "మీ ప్రశ్న రాయండి లేదా ఉత్పత్తిని వివరించండి...",
    micDenied: "మైక్రోఫోన్ అనుమతి నిరాకరించబడింది. బ్రౌజర్ సెట్టింగ్‌లలో అనుమతించండి.",
    micUnsupported: "మీ బ్రౌజర్ స్పీచ్ రికగ్నిషన్‌ను సపోర్ట్ చేయదు. Google Chrome వాడండి.",
    micWaiting: "మైక్రోఫోన్ అనుమతి కోసం వేచి ఉంది...",
    errorServer: "సర్వర్‌తో కనెక్ట్ కాలేదు. మళ్లీ ప్రయత్నించండి.",
    welcomeTitle: "నమస్కారం! నేను మానక్-మిత్ర",
    welcomeDesc: "భారతీయ ప్రమాణాలు, ISI / CRS సర్టిఫికేషన్, హాల్‌మార్క్, ల్యాబ్‌లు మరియు వినియోగదారు ప్రశ్నల్లో సహాయం చేస్తాను.",
    thinking: "మానక్-మిత్ర ఆలోచిస్తోంది...",
    sources: "మూలాలు",
    documents: "పత్రాలు",
    highConf: "అధికం",
    medConf: "ధృవీకరణ అవసరం",
    lowConf: "తగిన సాక్ష్యం లేదు",
    followUp: "తర్వాతి ప్రశ్న",
    contextHelper: "అధికారిక లింకులు",
    relatedStandards: "సంబంధిత ప్రమాణాలు",
    certRoadmap: "సర్టిఫికేషన్ మార్గం",
    understandingPurity: "హాల్‌మార్క్ స్వచ్ఛత గుర్తులు",
    huidLookup: "HUID సహాయం",
    enterHuid: "HUID అధికారిక BIS CARE యాప్‌లో ధృవీకరించబడుతుంది",
    verifyJeweller: "BIS CARE / HUID సహాయం తెరవండి",
    quickLinks: "త్వరిత లింకులు",
    shareConversation: "సంభాషణను షేర్ చేయండి",
    shareNoContent: "షేర్ చేయడానికి సంభాషణ లేదు.",
    shareSuccess: "సంభాషణ కాపీ అయింది!",
    offlineTitle: "ఆఫ్‌లైన్ / పరిమిత కనెక్షన్",
    offlineDesc: "మీరు ఆఫ్‌లైన్. కొత్త ప్రశ్నకు కనెక్షన్ కావాలి.",
    cachedHistoryBadge: "ఆఫ్‌లైన్",
    micListening: "వింటున్నాను... ఇప్పుడు మాట్లాడండి",
    micNoSpeech: "మాట వినబడలేదు. మళ్లీ మైక్ నొక్కండి.",
    micNetworkError: "స్వర గుర్తింపుకు ఇంటర్నెట్ కావాలి.",
    composerPlaceholder: "మానక్-మిత్రతో మాట్లాడండి...",
    listeningPlaceholder: "మాట్లాడండి... మీ మాటలు ఇక్కడ కనిపిస్తాయి",
    stopDone: "వినడం ఆపండి",
    jumpLatest: "తాజా",
    speakTitle: "మాట్లాడి రాయండి",
    writingResponse: "మానక్-మిత్ర సమాధానం రాస్తోంది...",
    internetRestored: "ఇంటర్నెట్ కనెక్షన్ తిరిగి వచ్చింది.",
    sourceBacked: "మూలాధార సమాధానాలు",
    emptyQuery: "దయచేసి మీ ప్రశ్నను నమోదు చేయండి.",
    catalogueLoadError: "BIS కేటలాగ్ లోడ్ కాలేదు. మళ్లీ ప్రయత్నించండి లేదా Know Your Standard వాడండి.",
  }),
  mr: pack({
    disclaimer: "हे सार्वजनिक BIS कॅटलॉग मेटाडेटावर आधारित आहे. कायदेशीर सल्ला नाही. फी आणि QCO स्थिती लाइव्ह पोर्टलवर तपासा.",
    instruction: "तुमचा प्रश्न विचारा किंवा उत्पादन सांगा...",
    micDenied: "मायक्रोफोन परवानगी नाकारली. ब्राउझर सेटिंग्जमध्ये परवानगी द्या.",
    micUnsupported: "तुमचा ब्राउझर स्पीच रेकग्निशन सपोर्ट करत नाही. Google Chrome वापरा.",
    micWaiting: "मायक्रोफोन परवानगीची वाट पाहत आहे...",
    errorServer: "सर्व्हरशी जोडणी झाली नाही. पुन्हा प्रयत्न करा.",
    welcomeTitle: "नमस्कार! मी मानक-मित्र आहे",
    welcomeDesc: "भारतीय मानक, ISI / CRS प्रमाणन, हॉलमार्क, लॅब आणि ग्राहक प्रश्नांत मदत करतो.",
    thinking: "मानक-मित्र विचार करत आहे...",
    sources: "स्रोत",
    documents: "दस्तऐवज",
    highConf: "उच्च",
    medConf: "पडताळणी आवश्यक",
    lowConf: "पुरेसा पुरावा नाही",
    followUp: "पुढचा प्रश्न",
    contextHelper: "अधिकृत दुवे",
    relatedStandards: "संबंधित मानक",
    certRoadmap: "प्रमाणन मार्ग",
    understandingPurity: "हॉलमार्क शुद्धता चिन्हे",
    huidLookup: "HUID मदत",
    enterHuid: "HUID अधिकृत BIS CARE अॅपमध्ये पडताळला जातो",
    verifyJeweller: "BIS CARE / HUID मदत उघडा",
    quickLinks: "त्वरित दुवे",
    shareConversation: "संवाद शेअर करा",
    shareNoContent: "शेअर करण्यासाठी संवाद नाही.",
    shareSuccess: "संवाद कॉपी झाला!",
    offlineTitle: "ऑफलाइन / मर्यादित कनेक्शन",
    offlineDesc: "तुम्ही ऑफलाइन आहात. नवीन प्रश्नासाठी कनेक्शन हवे.",
    cachedHistoryBadge: "ऑफलाइन",
    micListening: "ऐकत आहे... आता बोला",
    micNoSpeech: "आवाज आला नाही. पुन्हा माइक दाबा.",
    micNetworkError: "आवाज ओळखण्यासाठी इंटरनेट हवे.",
    composerPlaceholder: "मानक-मित्रशी बोला...",
    listeningPlaceholder: "बोला... तुमचे शब्द येथे दिसतील",
    stopDone: "ऐकणे थांबवा",
    jumpLatest: "नवीनतम",
    speakTitle: "बोलून लिहा",
    writingResponse: "मानक-मित्र उत्तर लिहित आहे...",
    internetRestored: "इंटरनेट कनेक्शन परत आले.",
    sourceBacked: "स्रोत-आधारित उत्तरे",
    emptyQuery: "कृपया तुमचा प्रश्न लिहा.",
    catalogueLoadError: "BIS कॅटलॉग लोड झाला नाही. पुन्हा प्रयत्न करा किंवा Know Your Standard वापरा.",
  }),
  gu: pack({
    disclaimer: "આ પબ્લિક BIS કેટલોગ મેટાડેટા પર આધારિત છે. કાનૂની સલાહ નથી. ફી અને QCO સ્થિતિ લાઇવ પોર્ટલ પર ચકાસો.",
    instruction: "તમારો પ્રશ્ન પૂછો અથવા પ્રોડક્ટ જણાવો...",
    micDenied: "માઇક્રોફોન પરવાનગી નકારાઈ. બ્રાઉઝર સેટિંગ્સમાં પરવાનગી આપો.",
    micUnsupported: "તમારું બ્રાઉઝર સ્પીચ રેકગ્નિશન સપોર્ટ કરતું નથી. Google Chrome વાપરો.",
    micWaiting: "માઇક્રોફોન પરવાનગીની રાહ...",
    errorServer: "સર્વર સાથે જોડાણ થયું નહીં. ફરી પ્રયાસ કરો.",
    welcomeTitle: "નમસ્તે! હું માનક-મિત્ર છું",
    welcomeDesc: "ભારતીય ધોરણો, ISI / CRS પ્રમાણન, હોલમાર્ક, લેબ અને ગ્રાહક પ્રશ્નોમાં મદદ કરું છું.",
    thinking: "માનક-મિત્ર વિચારે છે...",
    sources: "સ્ત્રોત",
    documents: "દસ્તાવેજો",
    highConf: "ઉચ્ચ",
    medConf: "ચકાસણી જરૂરી",
    lowConf: "પૂરતો પુરાવો નથી",
    followUp: "આગળનો પ્રશ્ન",
    contextHelper: "અધિકૃત લિંક્સ",
    relatedStandards: "સંબંધિત ધોરણો",
    certRoadmap: "પ્રમાણન માર્ગ",
    understandingPurity: "હોલમાર્ક શુદ્ધતા ચિહ્નો",
    huidLookup: "HUID મદદ",
    enterHuid: "HUID અધિકૃત BIS CARE એપમાં ચકાસાય છે",
    verifyJeweller: "BIS CARE / HUID મદદ ખોલો",
    quickLinks: "ઝડપી લિંક્સ",
    shareConversation: "વાતચીત શેર કરો",
    shareNoContent: "શેર કરવા માટે વાતચીત નથી.",
    shareSuccess: "વાતચીત કૉપી થઈ!",
    offlineTitle: "ઑફલાઇન / મર્યાદિત કનેક્શન",
    offlineDesc: "તમે ઑફલાઇન છો. નવા પ્રશ્ન માટે કનેક્શન જોઈએ.",
    cachedHistoryBadge: "ઑફલાઇન",
    micListening: "સાંભળું છું... હવે બોલો",
    micNoSpeech: "અવાજ મળ્યો નહીં. ફરી માઇક દબાવો.",
    micNetworkError: "અવાજ ઓળખવા ઇન્ટરનેટ જોઈએ.",
    composerPlaceholder: "માનક-મિત્ર સાથે વાત કરો...",
    listeningPlaceholder: "બોલો... તમારા શબ્દો અહીં આવશે",
    stopDone: "સાંભળવાનું બંધ કરો",
    jumpLatest: "નવીનતમ",
    speakTitle: "બોલીને લખો",
    writingResponse: "માનક-મિત્ર જવાબ લખે છે...",
    internetRestored: "ઇન્ટરનેટ કનેક્શન પાછું આવ્યું.",
    sourceBacked: "સ્ત્રોત-આધારિત જવાબો",
    emptyQuery: "કૃપા કરીને તમારો પ્રશ્ન લખો.",
    catalogueLoadError: "BIS કેટલોગ લોડ થયો નહીં. ફરી પ્રયાસ કરો અથવા Know Your Standard વાપરો.",
  }),
  kn: pack({
    disclaimer: "ಇದು ಸಾರ್ವಜನಿಕ BIS ಕ್ಯಾಟಲಾಗ್ ಮೆಟಾಡೇಟಾ. ಕಾನೂನು ಸಲಹೆ ಅಲ್ಲ. ಶುಲ್ಕ ಮತ್ತು QCO ಸ್ಥಿತಿಯನ್ನು ಲೈವ್ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ನೋಡಿ.",
    instruction: "ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಕೇಳಿ ಅಥವಾ ಉತ್ಪನ್ನವನ್ನು ವಿವರಿಸಿ...",
    micDenied: "ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ. ಬ್ರೌಸರ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಅನುಮತಿಸಿ.",
    micUnsupported: "ನಿಮ್ಮ ಬ್ರೌಸರ್ ಸ್ಪೀಚ್ ರೆಕಗ್ನಿಷನ್ ಬೆಂಬಲಿಸುವುದಿಲ್ಲ. Google Chrome ಬಳಸಿ.",
    micWaiting: "ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿಗಾಗಿ ಕಾಯುತ್ತಿದೆ...",
    errorServer: "ಸರ್ವರ್ ಸಂಪರ್ಕ ದೋಷ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    welcomeTitle: "ನಮಸ್ಕಾರ! ನಾನು ಮಾನಕ್-ಮಿತ್ರ",
    welcomeDesc: "ಭಾರತೀಯ ಮಾನದಂಡಗಳು, ISI / CRS ಪ್ರಮಾಣೀಕರಣ, ಹಾಲ್‌ಮಾರ್ಕ್, ಲ್ಯಾಬ್‌ಗಳು ಮತ್ತು ಗ್ರಾಹಕ ಪ್ರಶ್ನೆಗಳಲ್ಲಿ ಸಹಾಯ ಮಾಡುತ್ತೇನೆ.",
    thinking: "ಮಾನಕ್-ಮಿತ್ರ ಯೋಚಿಸುತ್ತಿದೆ...",
    sources: "ಮೂಲಗಳು",
    documents: "ದಾಖಲೆಗಳು",
    highConf: "ಹೆಚ್ಚು",
    medConf: "ಪರಿಶೀಲನೆ ಬೇಕು",
    lowConf: "ಸಾಕಷ್ಟು ಸಾಕ್ಷಿ ಇಲ್ಲ",
    followUp: "ಮುಂದಿನ ಪ್ರಶ್ನೆ",
    contextHelper: "ಅಧಿಕೃತ ಲಿಂಕ್‌ಗಳು",
    relatedStandards: "ಸಂಬಂಧಿತ ಮಾನದಂಡಗಳು",
    certRoadmap: "ಪ್ರಮಾಣೀಕರಣ ಮಾರ್ಗ",
    understandingPurity: "ಹಾಲ್‌ಮಾರ್ಕ್ ಶುದ್ಧತೆ ಗುರುತುಗಳು",
    huidLookup: "HUID ಸಹಾಯ",
    enterHuid: "HUID ಅಧಿಕೃತ BIS CARE ಅನ್ವಯದಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ",
    verifyJeweller: "BIS CARE / HUID ಸಹಾಯ ತೆರೆಯಿರಿ",
    quickLinks: "ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು",
    shareConversation: "ಸಂಭಾಷಣೆ ಹಂಚಿಕೊಳ್ಳಿ",
    shareNoContent: "ಹಂಚಲು ಸಂಭಾಷಣೆ ಇಲ್ಲ.",
    shareSuccess: "ಸಂಭಾಷಣೆ ನಕಲಿಸಲಾಗಿದೆ!",
    offlineTitle: "ಆಫ್‌ಲೈನ್ / ಸೀಮಿತ ಸಂಪರ್ಕ",
    offlineDesc: "ನೀವು ಆಫ್‌ಲೈನ್. ಹೊಸ ಪ್ರಶ್ನೆಗೆ ಸಂಪರ್ಕ ಬೇಕು.",
    cachedHistoryBadge: "ಆಫ್‌ಲೈನ್",
    micListening: "ಕೇಳುತ್ತಿದ್ದೇನೆ... ಈಗ ಮಾತನಾಡಿ",
    micNoSpeech: "ಮಾತು ಸಿಗಲಿಲ್ಲ. ಮತ್ತೆ ಮೈಕ್ ಒತ್ತಿ.",
    micNetworkError: "ಧ್ವನಿ ಗುರುತಿಸಲು ಇಂಟರ್ನೆಟ್ ಬೇಕು.",
    composerPlaceholder: "ಮಾನಕ್-ಮಿತ್ರರೊಂದಿಗೆ ಮಾತನಾಡಿ...",
    listeningPlaceholder: "ಮಾತನಾಡಿ... ನಿಮ್ಮ ಮಾತುಗಳು ಇಲ್ಲಿ ಬರುತ್ತವೆ",
    stopDone: "ಕೇಳುವುದನ್ನು ನಿಲ್ಲಿಸಿ",
    jumpLatest: "ಇತ್ತೀಚಿನ",
    speakTitle: "ಮಾತನಾಡಿ ಬರೆಯಿರಿ",
    writingResponse: "ಮಾನಕ್-ಮಿತ್ರ ಉತ್ತರ ಬರೆಯುತ್ತಿದೆ...",
    internetRestored: "ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಮರಳಿದೆ.",
    sourceBacked: "ಮೂಲ-ಆಧಾರಿತ ಉತ್ತರಗಳು",
    emptyQuery: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪ್ರಶ್ನೆ ನಮೂದಿಸಿ.",
    catalogueLoadError: "BIS ಕ್ಯಾಟಲಾಗ್ ಲೋಡ್ ಆಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ Know Your Standard ಬಳಸಿ.",
  }),
  ml: pack({
    disclaimer: "ഇത് പൊതു BIS കാറ്റലോഗ് മെറ്റാഡാറ്റയാണ്. നിയമോപദേശമല്ല. ഫീസും QCO നിലയും ലൈവ് പോർട്ടലിൽ പരിശോധിക്കുക.",
    instruction: "നിങ്ങളുടെ ചോദ്യം ചോദിക്കുക അല്ലെങ്കിൽ ഉൽപ്പന്നം വിവരിക്കുക...",
    micDenied: "മൈക്രോഫോൺ അനുമതി നിരസിച്ചു. ബ്രൗസർ ക്രമീകരണത്തിൽ അനുവദിക്കുക.",
    micUnsupported: "നിങ്ങളുടെ ബ്രൗസർ സ്പീച്ച് റെക്കഗ്നിഷൻ പിന്തുണയ്ക്കുന്നില്ല. Google Chrome ഉപയോഗിക്കുക.",
    micWaiting: "മൈക്രോഫോൺ അനുമതിക്കായി കാത്തിരിക്കുന്നു...",
    errorServer: "സെർവറുമായി ബന്ധിപ്പിക്കാനായില്ല. വീണ്ടും ശ്രമിക്കുക.",
    welcomeTitle: "നമസ്കാരം! ഞാൻ മാനക്-മിത്ര",
    welcomeDesc: "ഇന്ത്യൻ സ്റ്റാൻഡേർഡുകൾ, ISI / CRS സർട്ടിഫിക്കേഷൻ, ഹാൾമാർക്ക്, ലാബുകൾ, ഉപഭോക്തൃ ചോദ്യങ്ങൾ എന്നിവയിൽ സഹായിക്കുന്നു.",
    thinking: "മാനക്-മിത്ര ചിന്തിക്കുന്നു...",
    sources: "ഉറവിടങ്ങൾ",
    documents: "രേഖകൾ",
    highConf: "ഉയർന്നത്",
    medConf: "പരിശോധന ആവശ്യം",
    lowConf: "മതിയായ തെളിവില്ല",
    followUp: "അടുത്ത ചോദ്യം",
    contextHelper: "ഔദ്യോഗിക ലിങ്കുകൾ",
    relatedStandards: "ബന്ധപ്പെട്ട സ്റ്റാൻഡേർഡുകൾ",
    certRoadmap: "സർട്ടിഫിക്കേഷൻ വഴി",
    understandingPurity: "ഹാൾമാർക്ക് ശുദ്ധി അടയാളങ്ങൾ",
    huidLookup: "HUID സഹായം",
    enterHuid: "HUID ഔദ്യോഗിക BIS CARE ആപ്പിൽ പരിശോധിക്കുന്നു",
    verifyJeweller: "BIS CARE / HUID സഹായം തുറക്കുക",
    quickLinks: "ദ്രുത ലിങ്കുകൾ",
    shareConversation: "സംഭാഷണം പങ്കിടുക",
    shareNoContent: "പങ്കിടാൻ സംഭാഷണമില്ല.",
    shareSuccess: "സംഭാഷണം പകർത്തി!",
    offlineTitle: "ഓഫ്‌ലൈൻ / പരിമിത കണക്ഷൻ",
    offlineDesc: "നിങ്ങൾ ഓഫ്‌ലൈനാണ്. പുതിയ ചോദ്യത്തിന് കണക്ഷൻ വേണം.",
    cachedHistoryBadge: "ഓഫ്‌ലൈൻ",
    micListening: "കേൾക്കുന്നു... ഇപ്പോൾ സംസാരിക്കുക",
    micNoSpeech: "ശബ്ദം കിട്ടിയില്ല. വീണ്ടും മൈക്ക് അമർത്തുക.",
    micNetworkError: "ശബ്ദം തിരിച്ചറിയാൻ ഇന്റർനെറ്റ് വേണം.",
    composerPlaceholder: "മാനക്-മിത്രയോട് സംസാരിക്കുക...",
    listeningPlaceholder: "സംസാരിക്കുക... നിങ്ങളുടെ വാക്കുകൾ ഇവിടെ വരും",
    stopDone: "കേൾക്കൽ നിർത്തുക",
    jumpLatest: "പുതിയത്",
    speakTitle: "സംസാരിച്ച് എഴുതുക",
    writingResponse: "മാനക്-മിത്ര മറുപടി എഴുതുന്നു...",
    internetRestored: "ഇന്റർനെറ്റ് കണക്ഷൻ തിരികെ വന്നു.",
    sourceBacked: "ഉറവിടാധിഷ്ഠിത മറുപടികൾ",
    emptyQuery: "ദയവായി നിങ്ങളുടെ ചോദ്യം നൽകുക.",
    catalogueLoadError: "BIS കാറ്റലോഗ് ലോഡ് ആയില്ല. വീണ്ടും ശ്രമിക്കുക അല്ലെങ്കിൽ Know Your Standard ഉപയോഗിക്കുക.",
  }),
  pa: pack({
    disclaimer: "ਇਹ ਪਬਲਿਕ BIS ਕੈਟਾਲਾਗ ਮੈਟਾਡੇਟਾ ਤੇ ਆਧਾਰਿਤ ਹੈ। ਕਾਨੂੰਨੀ ਸਲਾਹ ਨਹੀਂ। ਫੀਸ ਅਤੇ QCO ਸਥਿਤੀ ਲਾਈਵ ਪੋਰਟਲ ਤੇ ਚੈੱਕ ਕਰੋ।",
    instruction: "ਆਪਣਾ ਸਵਾਲ ਪੁੱਛੋ ਜਾਂ ਉਤਪਾਦ ਦੱਸੋ...",
    micDenied: "ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਇਜਾਜ਼ਤ ਰੱਦ ਹੋਈ। ਬ੍ਰਾਊਜ਼ਰ ਸੈਟਿੰਗਾਂ ਵਿੱਚ ਇਜਾਜ਼ਤ ਦਿਓ।",
    micUnsupported: "ਤੁਹਾਡਾ ਬ੍ਰਾਊਜ਼ਰ ਸਪੀਚ ਰਿਕਗਨਿਸ਼ਨ ਸਹਾਰਾ ਨਹੀਂ ਦਿੰਦਾ। Google Chrome ਵਰਤੋ।",
    micWaiting: "ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਇਜਾਜ਼ਤ ਦੀ ਉਡੀਕ...",
    errorServer: "ਸਰਵਰ ਨਾਲ ਕਨੈਕਸ਼ਨ ਨਹੀਂ ਹੋਇਆ। ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    welcomeTitle: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਮਾਨਕ-ਮਿੱਤਰ ਹਾਂ",
    welcomeDesc: "ਭਾਰਤੀ ਮਿਆਰ, ISI / CRS ਸਰਟੀਫਿਕੇਸ਼ਨ, ਹਾਲਮਾਰਕ, ਲੈਬਾਂ ਅਤੇ ਖਪਤਕਾਰ ਸਵਾਲਾਂ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹਾਂ।",
    thinking: "ਮਾਨਕ-ਮਿੱਤਰ ਸੋਚ ਰਿਹਾ ਹੈ...",
    sources: "ਸਰੋਤ",
    documents: "ਦਸਤਾਵੇਜ਼",
    highConf: "ਉੱਚ",
    medConf: "ਤਸਦੀਕ ਲੋੜੀਂਦੀ",
    lowConf: "ਲੋੜੀਂਦਾ ਸਬੂਤ ਨਹੀਂ",
    followUp: "ਅਗਲਾ ਸਵਾਲ",
    contextHelper: "ਅਧਿਕਾਰਤ ਲਿੰਕ",
    relatedStandards: "ਸਬੰਧਤ ਮਿਆਰ",
    certRoadmap: "ਸਰਟੀਫਿਕੇਸ਼ਨ ਰਾਹ",
    understandingPurity: "ਹਾਲਮਾਰਕ ਸ਼ੁੱਧਤਾ ਚਿੰਨ੍ਹ",
    huidLookup: "HUID ਮਦਦ",
    enterHuid: "HUID ਅਧਿਕਾਰਤ BIS CARE ਐਪ ਵਿੱਚ ਤਸਦੀਕ ਹੁੰਦਾ ਹੈ",
    verifyJeweller: "BIS CARE / HUID ਮਦਦ ਖੋਲ੍ਹੋ",
    quickLinks: "ਤੇਜ਼ ਲਿੰਕ",
    shareConversation: "ਗੱਲਬਾਤ ਸਾਂਝੀ ਕਰੋ",
    shareNoContent: "ਸਾਂਝੀ ਕਰਨ ਲਈ ਗੱਲਬਾਤ ਨਹੀਂ।",
    shareSuccess: "ਗੱਲਬਾਤ ਕਾਪੀ ਹੋ ਗਈ!",
    offlineTitle: "ਆਫਲਾਈਨ / ਸੀਮਿਤ ਕਨੈਕਸ਼ਨ",
    offlineDesc: "ਤੁਸੀਂ ਆਫਲਾਈਨ ਹੋ। ਨਵੇਂ ਸਵਾਲ ਲਈ ਕਨੈਕਸ਼ਨ ਚਾਹੀਦਾ ਹੈ।",
    cachedHistoryBadge: "ਆਫਲਾਈਨ",
    micListening: "ਸੁਣ ਰਿਹਾ ਹਾਂ... ਹੁਣ ਬੋਲੋ",
    micNoSpeech: "ਆਵਾਜ਼ ਨਹੀਂ ਮਿਲੀ। ਫਿਰ ਮਾਈਕ ਦਬਾਓ।",
    micNetworkError: "ਆਵਾਜ਼ ਪਛਾਣ ਲਈ ਇੰਟਰਨੈੱਟ ਚਾਹੀਦਾ ਹੈ।",
    composerPlaceholder: "ਮਾਨਕ-ਮਿੱਤਰ ਨਾਲ ਗੱਲ ਕਰੋ...",
    listeningPlaceholder: "ਬੋਲੋ... ਤੁਹਾਡੇ ਸ਼ਬਦ ਇੱਥੇ ਆਉਣਗੇ",
    stopDone: "ਸੁਣਨਾ ਰੋਕੋ",
    jumpLatest: "ਨਵੀਨਤਮ",
    speakTitle: "ਬੋਲ ਕੇ ਲਿਖੋ",
    writingResponse: "ਮਾਨਕ-ਮਿੱਤਰ ਜਵਾਬ ਲਿਖ ਰਿਹਾ ਹੈ...",
    internetRestored: "ਇੰਟਰਨੈੱਟ ਕਨੈਕਸ਼ਨ ਵਾਪਸ ਆ ਗਿਆ।",
    sourceBacked: "ਸਰੋਤ-ਆਧਾਰਿਤ ਜਵਾਬ",
    emptyQuery: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਸਵਾਲ ਲਿਖੋ।",
    catalogueLoadError: "BIS ਕੈਟਾਲਾਗ ਲੋਡ ਨਹੀਂ ਹੋਇਆ। ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ Know Your Standard ਵਰਤੋ।",
  }),
  ur: pack({
    disclaimer: "یہ پبلک BIS کیٹلاگ میٹا ڈیٹا پر مبنی ہے۔ قانونی مشورہ نہیں۔ فیس اور QCO کی صورتحال لائیو پورٹل پر چیک کریں۔",
    instruction: "اپنا سوال پوچھیں یا پروڈکٹ بتائیں...",
    micDenied: "مائیکروفون کی اجازت مسترد ہوگئی۔ براؤزر سیٹنگز میں اجازت دیں۔",
    micUnsupported: "آپ کا براؤزر اسپیچ ریکگنیشن سپورٹ نہیں کرتا। Google Chrome استعمال کریں۔",
    micWaiting: "مائیکروفون کی اجازت کا انتظار...",
    errorServer: "سرور سے کنکشن نہیں ہوا۔ دوبارہ کوشش کریں۔",
    welcomeTitle: "السلام علیکم! میں مانک-متر ہوں",
    welcomeDesc: "ہندوستانی معیارات، ISI / CRS سرٹیفیکیشن، ہال مارک، لیبز اور صارفین کے سوالات میں مدد کرتا ہوں۔",
    thinking: "مانک-متر سوچ رہا ہے...",
    sources: "ذرائع",
    documents: "دستاویزات",
    highConf: "اعلیٰ",
    medConf: "تصدیق درکار",
    lowConf: "ناکافی ثبوت",
    followUp: "اگلا سوال",
    contextHelper: "سرکاری لنکس",
    relatedStandards: "متعلقہ معیارات",
    certRoadmap: "سرٹیفیکیشن راستہ",
    understandingPurity: "ہال مارک پاکیزگی کے نشان",
    huidLookup: "HUID مدد",
    enterHuid: "HUID سرکاری BIS CARE ایپ میں تصدیق ہوتا ہے",
    verifyJeweller: "BIS CARE / HUID مدد کھولیں",
    quickLinks: "فوری لنکس",
    shareConversation: "گفتگو شیئر کریں",
    shareNoContent: "شیئر کرنے کے لیے گفتگو نہیں۔",
    shareSuccess: "گفتگو کاپی ہوگئی!",
    offlineTitle: "آف لائن / محدود کنکشن",
    offlineDesc: "آپ آف لائن ہیں۔ نئے سوال کے لیے کنکشن چاہیے۔",
    cachedHistoryBadge: "آف لائن",
    micListening: "سن رہا ہوں... اب بولیں",
    micNoSpeech: "آواز نہیں ملی۔ دوبارہ مائیک دبائیں۔",
    micNetworkError: "آواز پہچاننے کے لیے انٹرنیٹ چاہیے۔",
    composerPlaceholder: "مانک-متر سے بات کریں...",
    listeningPlaceholder: "بولیں... آپ کے الفاظ یہاں آئیں گے",
    stopDone: "سننا بند کریں",
    jumpLatest: "تازہ",
    speakTitle: "بول کر لکھیں",
    writingResponse: "مانک-متر جواب لکھ رہا ہے...",
    internetRestored: "انٹرنیٹ کنکشن بحال ہوگیا۔",
    sourceBacked: "ماخذ پر مبنی جوابات",
    emptyQuery: "براہ کرم اپنا سوال درج کریں۔",
    catalogueLoadError: "BIS کیٹلاگ لوڈ نہیں ہوا۔ دوبارہ کوشش کریں یا Know Your Standard استعمال کریں۔",
  }),
  or: pack({
    disclaimer: "ଏହା ସାର୍ବଜନୀନ BIS କ୍ୟାଟାଲଗ୍ ମେଟାଡାଟା ଉପରେ ଆଧାରିତ। ଆଇନଗତ ପରାମର୍ଶ ନୁହେଁ। ଫି ଏବଂ QCO ସ୍ଥିତି ଲାଇଭ୍ ପୋର୍ଟାଲରେ ଯାଞ୍ଚ କରନ୍ତୁ।",
    instruction: "ଆପଣଙ୍କ ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ କିମ୍ବା ଉତ୍ପାଦ ବର୍ଣ୍ଣନା କରନ୍ତୁ...",
    micDenied: "ମାଇକ୍ରୋଫୋନ୍ ଅନୁମତି ପ୍ରତ୍ୟାଖ୍ୟାନ। ବ୍ରାଉଜର୍ ସେଟିଂସରେ ଅନୁମତି ଦିଅନ୍ତୁ।",
    micUnsupported: "ଆପଣଙ୍କ ବ୍ରାଉଜର୍ ସ୍ପିଚ୍ ରେକଗନିସନ୍ ସପୋର୍ଟ କରେ ନାହିଁ। Google Chrome ବ୍ୟବହାର କରନ୍ତୁ।",
    micWaiting: "ମାଇକ୍ରୋଫୋନ୍ ଅନୁମତି ଅପେକ୍ଷା...",
    errorServer: "ସର୍ଭର୍ ସହ ସଂଯୋଗ ହୋଇନାହିଁ। ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।",
    welcomeTitle: "ନମସ୍କାର! ମୁଁ ମାନକ-ମିତ୍ର",
    welcomeDesc: "ଭାରତୀୟ ମାନକ, ISI / CRS ପ୍ରମାଣପତ୍ର, ହଲମାର୍କ, ଲ୍ୟାବ୍ ଏବଂ ଗ୍ରାହକ ପ୍ରଶ୍ନରେ ସାହାଯ୍ୟ କରେ।",
    thinking: "ମାନକ-ମିତ୍ର ଚିନ୍ତା କରୁଛି...",
    sources: "ଉତ୍ସ",
    documents: "ଦଲିଲ",
    highConf: "ଉଚ୍ଚ",
    medConf: "ଯାଞ୍ଚ ଆବଶ୍ୟକ",
    lowConf: "ପର୍ଯ୍ୟାପ୍ତ ପ୍ରମାଣ ନାହିଁ",
    followUp: "ପରବର୍ତ୍ତୀ ପ୍ରଶ୍ନ",
    contextHelper: "ସରକାରୀ ଲିଙ୍କ୍",
    relatedStandards: "ସମ୍ପର୍କିତ ମାନକ",
    certRoadmap: "ପ୍ରମାଣପତ୍ର ପଥ",
    understandingPurity: "ହଲମାର୍କ ଶୁଦ୍ଧତା ଚିହ୍ନ",
    huidLookup: "HUID ସାହାଯ୍ୟ",
    enterHuid: "HUID ସରକାରୀ BIS CARE ଆପ୍‌ରେ ଯାଞ୍ଚ ହୁଏ",
    verifyJeweller: "BIS CARE / HUID ସାହାଯ୍ୟ ଖୋଲନ୍ତୁ",
    quickLinks: "ଶୀଘ୍ର ଲିଙ୍କ୍",
    shareConversation: "କଥୋପକଥନ ସେୟାର୍ କରନ୍ତୁ",
    shareNoContent: "ସେୟାର୍ କରିବାକୁ କଥୋପକଥନ ନାହିଁ।",
    shareSuccess: "କଥୋପକଥନ କପି ହୋଇଛି!",
    offlineTitle: "ଅଫଲାଇନ୍ / ସୀମିତ ସଂଯୋଗ",
    offlineDesc: "ଆପଣ ଅଫଲାଇନ୍। ନୂଆ ପ୍ରଶ୍ନ ପାଇଁ ସଂଯୋଗ ଦରକାର।",
    cachedHistoryBadge: "ଅଫଲାଇନ୍",
    micListening: "ଶୁଣୁଛି... ଏବେ କୁହନ୍ତୁ",
    micNoSpeech: "ସ୍ୱର ମିଳିଲା ନାହିଁ। ପୁଣି ମାଇକ୍ ଦବାନ୍ତୁ।",
    micNetworkError: "ସ୍ୱର ଚିହ୍ନଟ ପାଇଁ ଇଣ୍ଟରନେଟ୍ ଦରକାର।",
    composerPlaceholder: "ମାନକ-ମିତ୍ର ସହ କଥା ହୁଅନ୍ତୁ...",
    listeningPlaceholder: "କୁହନ୍ତୁ... ଆପଣଙ୍କ ଶବ୍ଦ ଏଠାରେ ଆସିବ",
    stopDone: "ଶୁଣିବା ବନ୍ଦ କରନ୍ତୁ",
    jumpLatest: "ନବୀନ",
    speakTitle: "କହି ଲେଖନ୍ତୁ",
    writingResponse: "ମାନକ-ମିତ୍ର ଉତ୍ତର ଲେଖୁଛି...",
    internetRestored: "ଇଣ୍ଟରନେଟ୍ ସଂଯୋଗ ଫେରିଛି।",
    sourceBacked: "ଉତ୍ସ-ଆଧାରିତ ଉତ୍ତର",
    emptyQuery: "ଦୟାକରି ଆପଣଙ୍କ ପ୍ରଶ୍ନ ଲେଖନ୍ତୁ।",
    catalogueLoadError: "BIS କ୍ୟାଟାଲଗ୍ ଲୋଡ୍ ହୋଇନାହିଁ। ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ କିମ୍ବା Know Your Standard ବ୍ୟବହାର କରନ୍ତୁ।",
  }),
};

export const FALLBACK_SHELL: Record<AppLang, FallbackShell> = {
  en: {
    title: "ManakMitra — source-backed answer",
    refuse: "I do not have enough verified BIS evidence in the authorised catalogue for a complete product-to-standard mapping of this query.",
    kysHint: "Use the official Know Your Standard tool to look up the product, then return with the IS number.",
    headingApplicable: "Catalogue metadata",
    headingNot: "What this is not",
    notBody: "Catalogue metadata only — full clause text is not stored. This is not a licence and not legal advice.",
    schemePrefix: "Related scheme (from pack):",
    followYes: "Official ISI / CRS certification steps",
    followNo: "Know Your Standard catalogue lookup",
  },
  hi: {
    title: "मानक-मित्र — स्रोत-आधारित उत्तर",
    refuse: "आधिकारिक कैटलॉग में इस प्रश्न का पूरा उत्पाद-से-मानक मिलान नहीं मिला।",
    kysHint: "आधिकारिक खोज: Know Your Standard portal.",
    headingApplicable: "लागू (कैटलॉग मेटाडेटा)",
    headingNot: "यह क्या नहीं है",
    notBody: "यह कैटलॉग मेटाडेटा है, पूर्ण क्लॉज पाठ नहीं। यह लाइसेंस नहीं है और कानूनी सलाह नहीं है।",
    schemePrefix: "संबंधित योजना (पैक से):",
    followYes: "आधिकारिक ISI / CRS प्रमाणन चरण",
    followNo: "Know Your Standard पर IS संख्या",
  },
  bn: {
    title: "মানক-মিত্র — সূত্র-ভিত্তিক উত্তর",
    refuse: "অনুমোদিত ক্যাটালগে এই প্রশ্নের পূর্ণ পণ্য-থেকে-স্ট্যান্ডার্ড মিল পাওয়া যায়নি।",
    kysHint: "অফিসিয়াল Know Your Standard পোর্টালে খুঁজুন, তারপর IS নম্বর নিয়ে ফিরুন।",
    headingApplicable: "প্রযোজ্য (ক্যাটালগ মেটাডেটা)",
    headingNot: "এটি যা নয়",
    notBody: "শুধু ক্যাটালগ মেটাডেটা — পূর্ণ ক্লজ টেক্সট নেই। এটি লাইসেন্স বা আইনি পরামর্শ নয়।",
    schemePrefix: "সম্পর্কিত স্কিম (প্যাক থেকে):",
    followYes: "এই স্কিমের অফিসিয়াল সার্টিফিকেশন ধাপ / ফি FAQ দেখতে চান?",
    followNo: "পণ্যের স্পষ্ট নাম, বা IS নম্বর বলতে পারেন?",
  },
  ta: {
    title: "மாநக்-மித்ரா — ஆதார அடிப்படையிலான பதில்",
    refuse: "அங்கீகரிக்கப்பட்ட பட்டியலில் இந்த கேள்விக்கு முழு பொருள்-தர இணைப்பு இல்லை.",
    kysHint: "அதிகாரப்பூர்வ Know Your Standard கருவியில் தேடி IS எண்ணுடன் திரும்பவும்.",
    headingApplicable: "பொருந்தும் (பட்டியல் மெட்டாடேட்டா)",
    headingNot: "இது என்ன அல்ல",
    notBody: "பட்டியல் மெட்டாடேட்டா மட்டும் — முழு பிரிவு உரை இல்லை. இது உரிமமோ சட்ட ஆலோசனையோ அல்ல.",
    schemePrefix: "தொடர்புடைய திட்டம் (பேக்கிலிருந்து):",
    followYes: "இந்த திட்டத்தின் அதிகாரப்பூர்வ சான்றிதழ் படிகள் / கட்டண FAQ வேண்டுமா?",
    followNo: "பொருளின் தெளிவான பெயர் அல்லது IS எண் சொல்ல முடியுமா?",
  },
  te: {
    title: "మానక్-మిత్ర — మూలాధార సమాధానం",
    refuse: "అధికారిక కేటలాగ్‌లో ఈ ప్రశ్నకు పూర్తి ఉత్పత్తి-ప్రమాణ మ్యాపింగ్ లేదు.",
    kysHint: "అధికారిక Know Your Standardలో వెతికి IS నంబర్‌తో తిరిగి రండి.",
    headingApplicable: "వర్తించేవి (కేటలాగ్ మెటాడేటా)",
    headingNot: "ఇది కానిది",
    notBody: "కేటలాగ్ మెటాడేటా మాత్రమే — పూర్తి క్లాజ్ టెక్స్ట్ లేదు. ఇది లైసెన్స్ లేదా న్యాయ సలహా కాదు.",
    schemePrefix: "సంబంధిత స్కీమ్ (ప్యాక్ నుండి):",
    followYes: "ఈ స్కీమ్ అధికారిక సర్టిఫికేషన్ దశలు / ఫీ FAQ కావాలా?",
    followNo: "ఉత్పత్తి పేరు స్పష్టంగా లేదా IS నంబర్ చెప్పగలరా?",
  },
  mr: {
    title: "मानक-मित्र — स्रोत-आधारित उत्तर",
    refuse: "अधिकृत कॅटलॉगमध्ये या प्रश्नाचे पूर्ण उत्पादन-ते-मानक जुळणी सापडली नाही.",
    kysHint: "अधिकृत Know Your Standard वर शोधा, नंतर IS क्रमांकासह परत या.",
    headingApplicable: "लागू (कॅटलॉग मेटाडेटा)",
    headingNot: "हे काय नाही",
    notBody: "फक्त कॅटलॉग मेटाडेटा — पूर्ण कलम मजकूर नाही. हे परवाना किंवा कायदेशीर सल्ला नाही.",
    schemePrefix: "संबंधित योजना (पॅकमधून):",
    followYes: "या योजनेच्या अधिकृत प्रमाणन पायऱ्या / फी FAQ पाहू इच्छिता?",
    followNo: "उत्पादनाचे स्पष्ट नाव किंवा IS क्रमांक सांगू शकता का?",
  },
  gu: {
    title: "માનક-મિત્ર — સ્ત્રોત-આધારિત જવાબ",
    refuse: "અધિકૃત કેટલોગમાં આ પ્રશ્નનું પૂરું પ્રોડક્ટ-થી-ધોરણ મેપિંગ મળ્યું નથી.",
    kysHint: "અધિકૃત Know Your Standard પર શોધો, પછી IS નંબર સાથે પાછા આવો.",
    headingApplicable: "લાગુ (કેટલોગ મેટાડેટા)",
    headingNot: "આ શું નથી",
    notBody: "ફક્ત કેટલોગ મેટાડેટા — પૂરો કલમ લખાણ નથી. આ લાઇસન્સ કે કાનૂની સલાહ નથી.",
    schemePrefix: "સંબંધિત યોજના (પેકમાંથી):",
    followYes: "આ યોજનાના અધિકૃત પ્રમાણન પગલાં / ફી FAQ જોવા માંગો છો?",
    followNo: "પ્રોડક્ટનું સ્પષ્ટ નામ અથવા IS નંબર કહી શકો?",
  },
  kn: {
    title: "ಮಾನಕ್-ಮಿತ್ರ — ಮೂಲ-ಆಧಾರಿತ ಉತ್ತರ",
    refuse: "ಅಧಿಕೃತ ಕ್ಯಾಟಲಾಗ್‌ನಲ್ಲಿ ಈ ಪ್ರಶ್ನೆಗೆ ಪೂರ್ಣ ಉತ್ಪನ್ನ-ಮಾನದಂಡ ಹೊಂದಾಣಿಕೆ ಸಿಗಲಿಲ್ಲ.",
    kysHint: "ಅಧಿಕೃತ Know Your Standardನಲ್ಲಿ ಹುಡುಕಿ IS ಸಂಖ್ಯೆಯೊಂದಿಗೆ ಹಿಂತಿರುಗಿ.",
    headingApplicable: "ಅನ್ವಯ (ಕ್ಯಾಟಲಾಗ್ ಮೆಟಾಡೇಟಾ)",
    headingNot: "ಇದು ಏನಲ್ಲ",
    notBody: "ಕ್ಯಾಟಲಾಗ್ ಮೆಟಾಡೇಟಾ ಮಾತ್ರ — ಪೂರ್ಣ ಷರತ್ತು ಪಠ್ಯವಿಲ್ಲ. ಇದು ಪರವಾನಗಿ ಅಥವಾ ಕಾನೂನು ಸಲಹೆ ಅಲ್ಲ.",
    schemePrefix: "ಸಂಬಂಧಿತ ಯೋಜನೆ (ಪ್ಯಾಕ್‌ನಿಂದ):",
    followYes: "ಈ ಯೋಜನೆಯ ಅಧಿಕೃತ ಪ್ರಮಾಣೀಕರಣ ಹಂತಗಳು / ಶುಲ್ಕ FAQ ಬೇಕೇ?",
    followNo: "ಉತ್ಪನ್ನದ ಸ್ಪಷ್ಟ ಹೆಸರು ಅಥವಾ IS ಸಂಖ್ಯೆ ಹೇಳಬಹುದೇ?",
  },
  ml: {
    title: "മാനക്-മിത്ര — ഉറവിടാധിഷ്ഠിത മറുപടി",
    refuse: "അംഗീകൃത കാറ്റലോഗിൽ ഈ ചോദ്യത്തിന് പൂർണ ഉൽപ്പന്ന-മാനദണ്ഡ മാപ്പിംഗ് ഇല്ല.",
    kysHint: "ഔദ്യോഗിക Know Your Standard-ൽ തിരഞ്ഞ് IS നമ്പറുമായി മടങ്ങുക.",
    headingApplicable: "ബാധകം (കാറ്റലോഗ് മെറ്റാഡാറ്റ)",
    headingNot: "ഇത് അല്ലാത്തത്",
    notBody: "കാറ്റലോഗ് മെറ്റാഡാറ്റ മാത്രം — പൂർണ ക്ലോസ് ടെക്സ്റ്റ് ഇല്ല. ഇത് ലൈസൻസോ നിയമോപദേശമോ അല്ല.",
    schemePrefix: "ബന്ധപ്പെട്ട സ്കീം (പായ്ക്കിൽ നിന്ന്):",
    followYes: "ഈ സ്കീമിന്റെ ഔദ്യോഗിക സർട്ടിഫിക്കേഷൻ ഘട്ടങ്ങൾ / ഫീ FAQ വേണോ?",
    followNo: "ഉൽപ്പന്നത്തിന്റെ വ്യക്തമായ പേര് അല്ലെങ്കിൽ IS നമ്പർ പറയാമോ?",
  },
  pa: {
    title: "ਮਾਨਕ-ਮਿੱਤਰ — ਸਰੋਤ-ਆਧਾਰਿਤ ਜਵਾਬ",
    refuse: "ਅਧਿਕਾਰਤ ਕੈਟਾਲਾਗ ਵਿੱਚ ਇਸ ਸਵਾਲ ਦਾ ਪੂਰਾ ਉਤਪਾਦ-ਤੋਂ-ਮਿਆਰ ਮੇਲ ਨਹੀਂ ਮਿਲਿਆ।",
    kysHint: "ਅਧਿਕਾਰਤ Know Your Standard ਤੇ ਲੱਭੋ, ਫਿਰ IS ਨੰਬਰ ਨਾਲ ਵਾਪਸ ਆਓ।",
    headingApplicable: "ਲਾਗੂ (ਕੈਟਾਲਾਗ ਮੈਟਾਡੇਟਾ)",
    headingNot: "ਇਹ ਕੀ ਨਹੀਂ",
    notBody: "ਸਿਰਫ਼ ਕੈਟਾਲਾਗ ਮੈਟਾਡੇਟਾ — ਪੂਰਾ ਕਲਾਜ਼ ਟੈਕਸਟ ਨਹੀਂ। ਇਹ ਲਾਇਸੈਂਸ ਜਾਂ ਕਾਨੂੰਨੀ ਸਲਾਹ ਨਹੀਂ।",
    schemePrefix: "ਸਬੰਧਤ ਸਕੀਮ (ਪੈਕ ਤੋਂ):",
    followYes: "ਇਸ ਸਕੀਮ ਦੇ ਅਧਿਕਾਰਤ ਸਰਟੀਫਿਕੇਸ਼ਨ ਕਦਮ / ਫੀਸ FAQ ਚਾਹੁੰਦੇ ਹੋ?",
    followNo: "ਉਤਪਾਦ ਦਾ ਸਾਫ਼ ਨਾਮ ਜਾਂ IS ਨੰਬਰ ਦੱਸ ਸਕਦੇ ਹੋ?",
  },
  ur: {
    title: "مانک-متر — ماخذ پر مبنی جواب",
    refuse: "مجاز کیٹلاگ میں اس سوال کا مکمل پروڈکٹ سے معیار میپ نہیں ملا۔",
    kysHint: "سرکاری Know Your Standard پر تلاش کریں، پھر IS نمبر کے ساتھ واپس آئیں۔",
    headingApplicable: "قابل اطلاق (کیٹلاگ میٹا ڈیٹا)",
    headingNot: "یہ کیا نہیں ہے",
    notBody: "صرف کیٹلاگ میٹا ڈیٹا — مکمل شق کا متن نہیں۔ یہ لائسنس یا قانونی مشورہ نہیں۔",
    schemePrefix: "متعلقہ اسکیم (پیک سے):",
    followYes: "کیا آپ اس اسکیم کے سرکاری سرٹیفیکیشن مراحل / فیس FAQ دیکھنا چاہتے ہیں؟",
    followNo: "پروڈکٹ کا واضح نام یا IS نمبر بتا سکتے ہیں؟",
  },
  or: {
    title: "ମାନକ-ମିତ୍ର — ଉତ୍ସ-ଆଧାରିତ ଉତ୍ତର",
    refuse: "ଅନୁମୋଦିତ କ୍ୟାଟାଲଗ୍‌ରେ ଏହି ପ୍ରଶ୍ନର ସମ୍ପୂର୍ଣ୍ଣ ଉତ୍ପାଦ-ମାନକ ମେଳ ମିଳିଲା ନାହିଁ।",
    kysHint: "ସରକାରୀ Know Your Standardରେ ଖୋଜନ୍ତୁ, ତାପରେ IS ନମ୍ବର ସହିତ ଫେରନ୍ତୁ।",
    headingApplicable: "ପ୍ରଯୁଜ୍ୟ (କ୍ୟାଟାଲଗ୍ ମେଟାଡାଟା)",
    headingNot: "ଏହା କ’ଣ ନୁହେଁ",
    notBody: "କେବଳ କ୍ୟାଟାଲଗ୍ ମେଟାଡାଟା — ପୂରା ଧାରା ପାଠ ନାହିଁ। ଏହା ଲାଇସେନ୍ସ କିମ୍ବା ଆଇନଗତ ପରାମର୍ଶ ନୁହେଁ।",
    schemePrefix: "ସମ୍ପର୍କିତ ଯୋଜନା (ପ୍ୟାକ୍ ରୁ):",
    followYes: "ଏହି ଯୋଜନାର ସରକାରୀ ପ୍ରମାଣପତ୍ର ପଦକ୍ଷେପ / ଫି FAQ ଦେଖିବେ କି?",
    followNo: "ଉତ୍ପାଦର ସ୍ପଷ୍ଟ ନାମ କିମ୍ବା IS ନମ୍ବର କହିପାରିବେ କି?",
  },
};

const SOCIAL_TAIL = `\n\n[SOURCE] ManakMitra | assistant | 2026-09-07 | https://www.bis.gov.in`;

export const SOCIAL_COPY: Record<AppLang, { body: string; follow: string }> = {
  en: {
    body: `Namaste — I am ManakMitra.
I can help with Indian Standards, ISI/CRS, hallmarking, labs, and complaints.
Try a product lookup such as cement ISI, laptop CRS, or gold HUID.`,
    follow: "Verify HUID on gold jewellery",
  },
  hi: {
    body: `नमस्ते — मैं मानक-मित्र हूँ।
मैं भारतीय मानक, ISI/CRS, हॉलमार्क, लैब और शिकायतों में मदद करता हूँ।
सीमेंट ISI, लैपटॉप CRS, या सोने का HUID देख सकते हैं।`,
    follow: "सोने के गहने पर HUID जाँचें",
  },
  bn: {
    body: `নমস্কার — আমি মানক-মিত্র।
ভারতীয় স্ট্যান্ডার্ড, ISI/CRS, হলমার্ক, ল্যাব ও অভিযোগে সাহায্য করি।
কোন পণ্য বা BIS সেবা দেখব?`,
    follow: "কোন পণ্য দিয়ে শুরু করবেন — যেমন PET বোতল, ল্যাপটপ, সোনার গয়না?",
  },
  ta: {
    body: `வணக்கம் — நான் மாநக்-மித்ரா.
இந்திய தரங்கள், ISI/CRS, ஹால்மார்க், ஆய்வகம், புகார் உதவி.
எந்த பொருள் அல்லது BIS சேவையை பார்ப்போம்?`,
    follow: "எந்த பொருளில் தொடங்கலாம் — PET பாட்டில், மடிக்கணினி, தங்க நகை?",
  },
  te: {
    body: `నమస్కారం — నేను మానక్-మిత్ర.
భారతీయ ప్రమాణాలు, ISI/CRS, హాల్‌మార్క్, ల్యాబ్, ఫిర్యాదుల్లో సహాయం.
ఏ ఉత్పత్తి లేదా BIS సేవ చూద్దాం?`,
    follow: "ఏ ఉత్పత్తితో మొదలుపెడదాం — PET బాటిల్, ల్యాప్‌టాప్, బంగారు ఆభరణం?",
  },
  mr: {
    body: `नमस्कार — मी मानक-मित्र आहे.
भारतीय मानक, ISI/CRS, हॉलमार्क, लॅब आणि तक्रारींमध्ये मदत करतो.
कोणते उत्पादन किंवा BIS सेवा पाहू?`,
    follow: "कोणत्या उत्पादनापासून सुरू करायचे — PET बाटली, लॅपटॉप, सोन्याचे दागिने?",
  },
  gu: {
    body: `નમસ્તે — હું માનક-મિત્ર છું.
ભારતીય ધોરણો, ISI/CRS, હોલમાર્ક, લેબ અને ફરિયાદમાં મદદ કરું છું.
કઈ પ્રોડક્ટ અથવા BIS સેવા જોઈએ?`,
    follow: "કઈ પ્રોડક્ટથી શરૂ કરીએ — PET બોટલ, લેપટોપ, સોનાના ઘરેણાં?",
  },
  kn: {
    body: `ನಮಸ್ಕಾರ — ನಾನು ಮಾನಕ್-ಮಿತ್ರ.
ಭಾರತೀಯ ಮಾನದಂಡ, ISI/CRS, ಹಾಲ್‌ಮಾರ್ಕ್, ಲ್ಯಾಬ್, ದೂರುಗಳಲ್ಲಿ ಸಹಾಯ.
ಯಾವ ಉತ್ಪನ್ನ ಅಥವಾ BIS ಸೇವೆ ನೋಡೋಣ?`,
    follow: "ಯಾವ ಉತ್ಪನ್ನದಿಂದ ಪ್ರಾರಂಭಿಸೋಣ — PET ಬಾಟಲಿ, ಲ್ಯಾಪ್‌ಟಾಪ್, ಚಿನ್ನದ ಆಭರಣ?",
  },
  ml: {
    body: `നമസ്കാരം — ഞാൻ മാനക്-മിത്ര.
ഇന്ത്യൻ സ്റ്റാൻഡേർഡ്, ISI/CRS, ഹാൾമാർക്ക്, ലാബ്, പരാതിയിൽ സഹായം.
ഏത് ഉൽപ്പന്നം അല്ലെങ്കിൽ BIS സേവനം നോക്കാം?`,
    follow: "ഏത് ഉൽപ്പന്നത്തിൽ തുടങ്ങാം — PET കുപ്പി, ലാപ്‌ടോപ്പ്, സ്വർണാഭരണം?",
  },
  pa: {
    body: `ਸਤ ਸ੍ਰੀ ਅਕਾਲ — ਮੈਂ ਮਾਨਕ-ਮਿੱਤਰ ਹਾਂ।
ਭਾਰਤੀ ਮਿਆਰ, ISI/CRS, ਹਾਲਮਾਰਕ, ਲੈਬ ਅਤੇ ਸ਼ਿਕਾਇਤ ਵਿੱਚ ਮਦਦ।
ਕਿਹੜਾ ਉਤਪਾਦ ਜਾਂ BIS ਸੇਵਾ ਵੇਖੀਏ?`,
    follow: "ਕਿਹੜੇ ਉਤਪਾਦ ਤੋਂ ਸ਼ੁਰੂ ਕਰੀਏ — PET ਬੋਤਲ, ਲੈਪਟਾਪ, ਸੋਨੇ ਦਾ ਗਹਿਣਾ?",
  },
  ur: {
    body: `السلام علیکم — میں مانک-متر ہوں۔
ہندوستانی معیارات، ISI/CRS، ہال مارک، لیب اور شکایات میں مدد۔
کون سی پروڈکٹ یا BIS سروس دیکھیں؟`,
    follow: "کس پروڈکٹ سے شروع کریں — PET بوتل، لیپ ٹاپ، سونے کا زیور؟",
  },
  or: {
    body: `ନମସ୍କାର — ମୁଁ ମାନକ-ମିତ୍ର।
ଭାରତୀୟ ମାନକ, ISI/CRS, ହଲମାର୍କ, ଲ୍ୟାବ୍ ଓ ଅଭିଯୋଗରେ ସାହାଯ୍ୟ।
କେଉଁ ଉତ୍ପାଦ କିମ୍ବା BIS ସେବା ଦେଖିବା?`,
    follow: "କେଉଁ ଉତ୍ପାଦରୁ ଆରମ୍ଭ କରିବା — PET ବୋତଲ, ଲାପଟପ୍, ସୁନା ଗହଣା?",
  },
};

export const OFFTOPIC_COPY: Record<AppLang, { body: string; follow: string }> = {
  en: {
    body: `That is outside Indian Standards and BIS services.
Ask about a product, ISI/CRS, hallmarking, a lab, or a complaint and I will look it up.`,
    follow: "Want to try a BIS question — a product, hallmark, or laboratory?",
  },
  hi: {
    body: `यह भारतीय मानक / BIS सेवाओं से बाहर है।
कोई प्रोडक्ट, ISI/CRS, हॉलमार्क, लैब या शिकायत बताइए — कैटलॉग में देखूँगा।`,
    follow: "क्या आप BIS से जुड़ा सवाल पूछना चाहेंगे — जैसे प्रमाणन, हॉलमार्क या लैब?",
  },
  bn: {
    body: `এটি ভারতীয় স্ট্যান্ডার্ড / BIS সেবার বাইরে।
একটি পণ্য, ISI/CRS, হলমার্ক, ল্যাব বা অভিযোগ বলুন — ক্যাটালগে খুঁজব।`,
    follow: "BIS সম্পর্কিত প্রশ্ন করবেন — সার্টিফিকেশন, হলমার্ক বা ল্যাব?",
  },
  ta: {
    body: `இது இந்திய தரங்கள் / BIS சேவைகளுக்கு வெளியே.
ஒரு பொருள், ISI/CRS, ஹால்மார்க், ஆய்வகம் அல்லது புகார் சொல்லுங்கள்.`,
    follow: "BIS கேள்வி முயற்சிக்கலாமா — சான்றிதழ், ஹால்மார்க் அல்லது ஆய்வகம்?",
  },
  te: {
    body: `ఇది భారతీయ ప్రమాణాలు / BIS సేవల బయట.
ఒక ఉత్పత్తి, ISI/CRS, హాల్‌మార్క్, ల్యాబ్ లేదా ఫిర్యాదు చెప్పండి.`,
    follow: "BIS ప్రశ్న అడుగుతారా — సర్టిఫికేషన్, హాల్‌మార్క్ లేదా ల్యాబ్?",
  },
  mr: {
    body: `हे भारतीय मानक / BIS सेवांच्या बाहेर आहे.
उत्पादन, ISI/CRS, हॉलमार्क, लॅब किंवा तक्रार सांगा — कॅटलॉगमध्ये पाहतो.`,
    follow: "BIS संबंधित प्रश्न विचाराल का — प्रमाणन, हॉलमार्क किंवा लॅब?",
  },
  gu: {
    body: `આ ભારતીય ધોરણો / BIS સેવાઓની બહાર છે.
પ્રોડક્ટ, ISI/CRS, હોલમાર્ક, લેબ અથવા ફરિયાદ કહો — કેટલોગમાં જોઈશ.`,
    follow: "BISનો પ્રશ્ન પૂછશો — પ્રમાણન, હોલમાર્ક અથવા લેબ?",
  },
  kn: {
    body: `ಇದು ಭಾರತೀಯ ಮಾನದಂಡ / BIS ಸೇವೆಗಳ ಹೊರಗೆ.
ಉತ್ಪನ್ನ, ISI/CRS, ಹಾಲ್‌ಮಾರ್ಕ್, ಲ್ಯಾಬ್ ಅಥವಾ ದೂರು ಹೇಳಿ.`,
    follow: "BIS ಪ್ರಶ್ನೆ ಕೇಳುತ್ತೀರಾ — ಪ್ರಮಾಣೀಕರಣ, ಹಾಲ್‌ಮಾರ್ಕ್ ಅಥವಾ ಲ್ಯಾಬ್?",
  },
  ml: {
    body: `ഇത് ഇന്ത്യൻ സ്റ്റാൻഡേർഡ് / BIS സേവനങ്ങൾക്ക് പുറത്താണ്.
ഒരു ഉൽപ്പന്നം, ISI/CRS, ഹാൾമാർക്ക്, ലാബ് അല്ലെങ്കിൽ പരാതി പറയുക.`,
    follow: "BIS ചോദ്യം ചോദിക്കുമോ — സർട്ടിഫിക്കേഷൻ, ഹാൾമാർക്ക് അല്ലെങ്കിൽ ലാബ്?",
  },
  pa: {
    body: `ਇਹ ਭਾਰਤੀ ਮਿਆਰ / BIS ਸੇਵਾਵਾਂ ਤੋਂ ਬਾਹਰ ਹੈ।
ਉਤਪਾਦ, ISI/CRS, ਹਾਲਮਾਰਕ, ਲੈਬ ਜਾਂ ਸ਼ਿਕਾਇਤ ਦੱਸੋ — ਕੈਟਾਲਾਗ ਵਿੱਚ ਵੇਖਾਂਗਾ।`,
    follow: "BIS ਵਾਲਾ ਸਵਾਲ ਪੁੱਛੋਗੇ — ਸਰਟੀਫਿਕੇਸ਼ਨ, ਹਾਲਮਾਰਕ ਜਾਂ ਲੈਬ?",
  },
  ur: {
    body: `یہ ہندوستانی معیارات / BIS خدمات سے باہر ہے۔
پروڈکٹ، ISI/CRS، ہال مارک، لیب یا شکایت بتائیں — کیٹلاگ میں دیکھوں گا۔`,
    follow: "BIS سے متعلق سوال پوچھیں گے — سرٹیفیکیشن، ہال مارک یا لیب؟",
  },
  or: {
    body: `ଏହା ଭାରତୀୟ ମାନକ / BIS ସେବା ବାହାରେ।
ଏକ ଉତ୍ପାଦ, ISI/CRS, ହଲମାର୍କ, ଲ୍ୟାବ୍ କିମ୍ବା ଅଭିଯୋଗ କୁହନ୍ତୁ।`,
    follow: "BIS ପ୍ରଶ୍ନ ପଚାରିବେ କି — ପ୍ରମାଣପତ୍ର, ହଲମାର୍କ କିମ୍ବା ଲ୍ୟାବ୍?",
  },
};

export function socialCopy(lang: AppLang): string {
  const c = SOCIAL_COPY[lang] || SOCIAL_COPY.en;
  return `${c.body}${SOCIAL_TAIL}
[FOLLOW_UP] ${c.follow}
[META] high | general`;
}

export function offtopicCopy(lang: AppLang): string {
  const c = OFFTOPIC_COPY[lang] || OFFTOPIC_COPY.en;
  return `${c.body}${SOCIAL_TAIL}
[FOLLOW_UP] ${c.follow}
[META] low | general`;
}

const UI_EXTRA: Record<AppLang, Pick<UiPack, "exported" | "exportFailed" | "retry" | "copyLabel" | "copiedLabel" | "confidenceHint" | "you" | "attach" | "exportLabel" | "pngReadError" | "fileType" | "shareHeading" | "errorTitle" | "errorFallback" | "privacyHint" | "chipHuid" | "chipCement" | "chipLaptop" | "sendLabel">> = {
  en: {
    exported: EN.exported,
    exportFailed: EN.exportFailed,
    retry: EN.retry,
    copyLabel: EN.copyLabel,
    copiedLabel: EN.copiedLabel,
    confidenceHint: EN.confidenceHint,
    you: EN.you,
    attach: EN.attach,
    exportLabel: EN.exportLabel,
    pngReadError: EN.pngReadError,
    fileType: EN.fileType,
    shareHeading: EN.shareHeading,
    errorTitle: EN.errorTitle,
    errorFallback: EN.errorFallback,
    privacyHint: EN.privacyHint,
    chipHuid: EN.chipHuid,
    chipCement: EN.chipCement,
    chipLaptop: EN.chipLaptop,
    sendLabel: EN.sendLabel,
  },
  hi: {
    exported: "बातचीत सहेजी गई।",
    exportFailed: "निर्यात नहीं हो सका।",
    retry: "फिर कोशिश करें",
    copyLabel: "कॉपी",
    copiedLabel: "कॉपी हो गई",
    confidenceHint: "आधिकारिक BIS कैटलॉग के आधार पर",
    you: "आप",
    attach: "PNG या टेक्स्ट फ़ाइल जोड़ें",
    exportLabel: "निर्यात",
    pngReadError: "यह फ़ाइल पढ़ी नहीं जा सकी।",
    fileType: "केवल PNG या टेक्स्ट फ़ाइल (.txt, .md, .csv, .json) चलेगी।",
    shareHeading: "मानक-मित्र बातचीत",
    errorTitle: "कुछ गड़बड़ हो गई",
    errorFallback: "अनपेक्षित त्रुटि। पेज फिर से लोड करें।",
    privacyHint: "गोपनीय कागज़ या निजी जानकारी न चिपकाएँ।",
    chipHuid: "सोने के गहने पर HUID जाँचें",
    chipCement: "सीमेंट के लिए ISI लाइसेंस",
    chipLaptop: "लैपटॉप के लिए CRS पंजीकरण",
    sendLabel: "भेजें",
  },
  bn: {
    exported: "কথোপকথন সেভ হয়েছে।",
    exportFailed: "এক্সপোর্ট হয়নি।",
    retry: "আবার চেষ্টা",
    copyLabel: "কপি",
    copiedLabel: "কপি হয়েছে",
    confidenceHint: "অফিসিয়াল BIS ক্যাটালগের ভিত্তিতে",
    you: "আপনি",
    attach: "PNG বা টেক্সট ফাইল যোগ করুন",
    exportLabel: "এক্সপোর্ট",
    pngReadError: "ফাইলটি পড়া যায়নি।",
    fileType: "শুধু PNG বা টেক্সট ফাইল (.txt, .md, .csv, .json)।",
    shareHeading: "মানক-মিত্র কথোপকথন",
    errorTitle: "কিছু ভুল হয়েছে",
    errorFallback: "অপ্রত্যাশিত ত্রুটি। পাতাটি আবার লোড করুন।",
    privacyHint: "গোপন নথি বা ব্যক্তিগত তথ্য পেস্ট করবেন না।",
    chipHuid: "সোনার গয়নায় HUID যাচাই",
    chipCement: "সিমেন্টের ISI লাইসেন্স",
    chipLaptop: "ল্যাপটপের CRS নিবন্ধন",
    sendLabel: "পাঠান",
  },
  ta: {
    exported: "உரையாடல் சேமிக்கப்பட்டது.",
    exportFailed: "ஏற்றுமதி ஆகவில்லை.",
    retry: "மீண்டும் முயற்சி",
    copyLabel: "நகல்",
    copiedLabel: "நகலானது",
    confidenceHint: "அதிகாரப்பூர்வ BIS பட்டியலின் அடிப்படையில்",
    you: "நீங்கள்",
    attach: "PNG அல்லது உரை கோப்பை இணைக்கவும்",
    exportLabel: "ஏற்றுமதி",
    pngReadError: "அந்த கோப்பைப் படிக்க முடியவில்லை.",
    fileType: "PNG அல்லது உரை கோப்பு (.txt, .md, .csv, .json) மட்டும்.",
    shareHeading: "மாநக்-மித்ரா உரையாடல்",
    errorTitle: "ஏதோ தவறு நேர்ந்தது",
    errorFallback: "எதிர்பாராத பிழை. பக்கத்தை மீண்டும் ஏற்றவும்.",
    privacyHint: "ரகசிய ஆவணம் அல்லது தனிப்பட்ட தகவலை ஒட்ட வேண்டாம்.",
    chipHuid: "தங்க நகையில் HUID சரிபார்ப்பு",
    chipCement: "சிமெண்டிற்கு ISI உரிமம்",
    chipLaptop: "மடிக்கணினிக்கு CRS பதிவு",
    sendLabel: "அனுப்பு",
  },
  te: {
    exported: "సంభాషణ సేవ్ అయింది.",
    exportFailed: "ఎగుమతి కాలేదు.",
    retry: "మళ్లీ ప్రయత్నించండి",
    copyLabel: "కాపీ",
    copiedLabel: "కాపీ అయింది",
    confidenceHint: "అధికారిక BIS కేటలాగ్ ఆధారంగా",
    you: "మీరు",
    attach: "PNG లేదా టెక్స్ట్ ఫైల్ జోడించండి",
    exportLabel: "ఎగుమతి",
    pngReadError: "ఆ ఫైల్ చదవలేకపోయాం.",
    fileType: "PNG లేదా టెక్స్ట్ ఫైల్ (.txt, .md, .csv, .json) మాత్రమే.",
    shareHeading: "మానక్-మిత్ర సంభాషణ",
    errorTitle: "ఏదో తప్పు జరిగింది",
    errorFallback: "ఊహించని లోపం. పేజీని మళ్లీ లోడ్ చేయండి.",
    privacyHint: "రహస్య పత్రాలు లేదా వ్యక్తిగత సమాచారం అతికించవద్దు.",
    chipHuid: "బంగారు ఆభరణంపై HUID తనిఖీ",
    chipCement: "సిమెంట్‌కు ISI లైసెన్సు",
    chipLaptop: "ల్యాప్‌టాప్‌కు CRS నమోదు",
    sendLabel: "పంపండి",
  },
  mr: {
    exported: "संवाद जतन झाला.",
    exportFailed: "निर्यात झाले नाही.",
    retry: "पुन्हा प्रयत्न",
    copyLabel: "कॉपी",
    copiedLabel: "कॉपी झाले",
    confidenceHint: "अधिकृत BIS कॅटलॉगच्या आधारे",
    you: "तुम्ही",
    attach: "PNG किंवा मजकूर फाइल जोडा",
    exportLabel: "निर्यात",
    pngReadError: "ती फाइल वाचता आली नाही.",
    fileType: "फक्त PNG किंवा मजकूर फाइल (.txt, .md, .csv, .json).",
    shareHeading: "मानक-मित्र संवाद",
    errorTitle: "काही चूक झाली",
    errorFallback: "अनपेक्षित त्रुटी. पान पुन्हा लोड करा.",
    privacyHint: "गोपनीय कागदपत्रे किंवा खाजगी माहिती चिकटवू नका.",
    chipHuid: "सोन्याच्या दागिन्यावर HUID तपासा",
    chipCement: "सिमेंटसाठी ISI परवाना",
    chipLaptop: "लॅपटॉपसाठी CRS नोंदणी",
    sendLabel: "पाठवा",
  },
  gu: {
    exported: "વાતચીત સાચવાઈ.",
    exportFailed: "નિકાસ ન થઈ.",
    retry: "ફરી પ્રયાસ",
    copyLabel: "કૉપી",
    copiedLabel: "કૉપી થઈ",
    confidenceHint: "અધિકૃત BIS કેટલોગના આધારે",
    you: "તમે",
    attach: "PNG અથવા ટેક્સ્ટ ફાઇલ જોડો",
    exportLabel: "નિકાસ",
    pngReadError: "તે ફાઇલ વાંચી શકાઈ નહીં.",
    fileType: "ફક્ત PNG અથવા ટેક્સ્ટ ફાઇલ (.txt, .md, .csv, .json).",
    shareHeading: "માનક-મિત્ર વાતચીત",
    errorTitle: "કંઈક ખોટું થયું",
    errorFallback: "અણધારી ભૂલ. પાનું ફરી લોડ કરો.",
    privacyHint: "ગોપનીય દસ્તાવેજ કે અંગત માહિતી ચોંટાડશો નહીં.",
    chipHuid: "સોનાના ઘરેણાં પર HUID તપાસ",
    chipCement: "સિમેન્ટ માટે ISI લાઇસન્સ",
    chipLaptop: "લેપટોપ માટે CRS નોંધણી",
    sendLabel: "મોકલો",
  },
  kn: {
    exported: "ಸಂಭಾಷಣೆ ಉಳಿಸಲಾಗಿದೆ.",
    exportFailed: "ರಫ್ತು ಆಗಲಿಲ್ಲ.",
    retry: "ಮತ್ತೆ ಪ್ರಯತ್ನ",
    copyLabel: "ನಕಲು",
    copiedLabel: "ನಕಲಾಯಿತು",
    confidenceHint: "ಅಧಿಕೃತ BIS ಕ್ಯಾಟಲಾಗ್ ಆಧಾರದ ಮೇಲೆ",
    you: "ನೀವು",
    attach: "PNG ಅಥವಾ ಪಠ್ಯ ಕಡತ ಸೇರಿಸಿ",
    exportLabel: "ರಫ್ತು",
    pngReadError: "ಆ ಕಡತ ಓದಲಾಗಲಿಲ್ಲ.",
    fileType: "PNG ಅಥವಾ ಪಠ್ಯ ಕಡತ (.txt, .md, .csv, .json) ಮಾತ್ರ.",
    shareHeading: "ಮಾನಕ್-ಮಿತ್ರ ಸಂಭಾಷಣೆ",
    errorTitle: "ಏನೋ ತಪ್ಪಾಗಿದೆ",
    errorFallback: "ಅನಿರೀಕ್ಷಿತ ದೋಷ. ಪುಟವನ್ನು ಮತ್ತೆ ಲೋಡ್ ಮಾಡಿ.",
    privacyHint: "ಗೌಪ್ಯ ದಾಖಲೆ ಅಥವಾ ಖಾಸಗಿ ಮಾಹಿತಿ ಅಂಟಿಸಬೇಡಿ.",
    chipHuid: "ಚಿನ್ನದ ಆಭರಣದಲ್ಲಿ HUID ಪರಿಶೀಲನೆ",
    chipCement: "ಸಿಮೆಂಟ್‌ಗೆ ISI ಪರವಾನಗಿ",
    chipLaptop: "ಲ್ಯಾಪ್‌ಟಾಪ್‌ಗೆ CRS ನೋಂದಣಿ",
    sendLabel: "ಕಳುಹಿಸಿ",
  },
  ml: {
    exported: "സംഭാഷണം സേവ് ചെയ്തു.",
    exportFailed: "എക്സ്പോർട്ട് ആയില്ല.",
    retry: "വീണ്ടും ശ്രമിക്കുക",
    copyLabel: "പകർത്തുക",
    copiedLabel: "പകർത്തി",
    confidenceHint: "ഔദ്യോഗിക BIS കാറ്റലോഗിന്റെ അടിസ്ഥാനത്തിൽ",
    you: "നിങ്ങൾ",
    attach: "PNG അല്ലെങ്കിൽ ടെക്സ്റ്റ് ഫയൽ ചേർക്കുക",
    exportLabel: "എക്സ്പോർട്ട്",
    pngReadError: "ആ ഫയൽ വായിക്കാനായില്ല.",
    fileType: "PNG അല്ലെങ്കിൽ ടെക്സ്റ്റ് ഫയൽ (.txt, .md, .csv, .json) മാത്രം.",
    shareHeading: "മാനക്-മിത്ര സംഭാഷണം",
    errorTitle: "എന്തോ കുഴപ്പം സംഭവിച്ചു",
    errorFallback: "പ്രതീക്ഷിക്കാത്ത പിശക്. പേജ് വീണ്ടും ലോഡ് ചെയ്യുക.",
    privacyHint: "രഹസ്യ രേഖയോ വ്യക്തിഗത വിവരമോ ഒട്ടിക്കരുത്.",
    chipHuid: "സ്വർണാഭരണത്തിൽ HUID പരിശോധന",
    chipCement: "സിമന്റിന് ISI ലൈസൻസ്",
    chipLaptop: "ലാപ്‌ടോപ്പിന് CRS രജിസ്ട്രേഷൻ",
    sendLabel: "അയയ്ക്കുക",
  },
  pa: {
    exported: "ਗੱਲਬਾਤ ਸੰਭਾਲੀ ਗਈ।",
    exportFailed: "ਨਿਰਯਾਤ ਨਹੀਂ ਹੋਇਆ।",
    retry: "ਫਿਰ ਕੋਸ਼ਿਸ਼",
    copyLabel: "ਕਾਪੀ",
    copiedLabel: "ਕਾਪੀ ਹੋ ਗਈ",
    confidenceHint: "ਅਧਿਕਾਰਤ BIS ਕੈਟਾਲਾਗ ਦੇ ਆਧਾਰ ਤੇ",
    you: "ਤੁਸੀਂ",
    attach: "PNG ਜਾਂ ਟੈਕਸਟ ਫ਼ਾਈਲ ਜੋੜੋ",
    exportLabel: "ਨਿਰਯਾਤ",
    pngReadError: "ਉਹ ਫ਼ਾਈਲ ਪੜ੍ਹੀ ਨਹੀਂ ਗਈ।",
    fileType: "ਸਿਰਫ਼ PNG ਜਾਂ ਟੈਕਸਟ ਫ਼ਾਈਲ (.txt, .md, .csv, .json)।",
    shareHeading: "ਮਾਨਕ-ਮਿੱਤਰ ਗੱਲਬਾਤ",
    errorTitle: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ",
    errorFallback: "ਅਣਕਿਆਸੀ ਗਲਤੀ। ਸਫ਼ਾ ਦੁਬਾਰਾ ਲੋਡ ਕਰੋ।",
    privacyHint: "ਗੁਪਤ ਦਸਤਾਵੇਜ਼ ਜਾਂ ਨਿੱਜੀ ਜਾਣਕਾਰੀ ਨਾ ਚਿਪਕਾਓ।",
    chipHuid: "ਸੋਨੇ ਦੇ ਗਹਿਣੇ ਉੱਤੇ HUID ਜਾਂਚ",
    chipCement: "ਸੀਮਿੰਟ ਲਈ ISI ਲਾਇਸੰਸ",
    chipLaptop: "ਲੈਪਟਾਪ ਲਈ CRS ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    sendLabel: "ਭੇਜੋ",
  },
  ur: {
    exported: "گفتگو محفوظ ہوگئی۔",
    exportFailed: "برآمد نہیں ہوئی۔",
    retry: "دوبارہ کوشش",
    copyLabel: "کاپی",
    copiedLabel: "کاپی ہوگئی",
    confidenceHint: "سرکاری BIS کیٹلاگ کی بنیاد پر",
    you: "آپ",
    attach: "PNG یا ٹیکسٹ فائل لگائیں",
    exportLabel: "برآمد",
    pngReadError: "وہ فائل پڑھی نہیں جا سکی۔",
    fileType: "صرف PNG یا ٹیکسٹ فائل (.txt, .md, .csv, .json)۔",
    shareHeading: "مانک-متر گفتگو",
    errorTitle: "کچھ غلط ہوگیا",
    errorFallback: "غیر متوقع خرابی۔ صفحہ دوبارہ لوڈ کریں۔",
    privacyHint: "خفیہ دستاویز یا ذاتی معلومات نہ چسپاں کریں۔",
    chipHuid: "سونے کے زیور پر HUID کی جانچ",
    chipCement: "سیمنٹ کے لیے ISI لائسنس",
    chipLaptop: "لیپ ٹاپ کے لیے CRS رجسٹریشن",
    sendLabel: "بھیجیں",
  },
  or: {
    exported: "କଥୋପକଥନ ସାଇତାଗଲା।",
    exportFailed: "ରପ୍ତାନି ହେଲା ନାହିଁ।",
    retry: "ପୁଣି ଚେଷ୍ଟା",
    copyLabel: "କପି",
    copiedLabel: "କପି ହେଲା",
    confidenceHint: "ସରକାରୀ BIS କାଟାଲଗ ଆଧାରରେ",
    you: "ଆପଣ",
    attach: "PNG କିମ୍ବା ଟେକ୍ସଟ ଫାଇଲ ଯୋଡ଼ନ୍ତୁ",
    exportLabel: "ରପ୍ତାନି",
    pngReadError: "ସେହି ଫାଇଲ ପଢ଼ାଗଲା ନାହିଁ।",
    fileType: "କେବଳ PNG କିମ୍ବା ଟେକ୍ସଟ ଫାଇଲ (.txt, .md, .csv, .json)।",
    shareHeading: "ମାନକ-ମିତ୍ର କଥୋପକଥନ",
    errorTitle: "କିଛି ଭୁଲ ହେଲା",
    errorFallback: "ଅପ୍ରତ୍ୟାଶିତ ତ୍ରୁଟି। ପୃଷ୍ଠା ପୁଣି ଲୋଡ କରନ୍ତୁ।",
    privacyHint: "ଗୋପନୀୟ ଦଲିଲ କିମ୍ବା ବ୍ୟକ୍ତିଗତ ସୂଚନା ଲଗାନ୍ତୁ ନାହିଁ।",
    chipHuid: "ସୁନା ଗହଣାରେ HUID ଯାଞ୍ଚ",
    chipCement: "ସିମେଣ୍ଟ ପାଇଁ ISI ଲାଇସେନ୍ସ",
    chipLaptop: "ଲାପଟପ୍ ପାଇଁ CRS ପଞ୍ଜୀକରଣ",
    sendLabel: "ପଠାନ୍ତୁ",
  },
};

for (const id of Object.keys(UI_EXTRA) as AppLang[]) {
  Object.assign(UI_DICTIONARY[id], UI_EXTRA[id]);
}

export const getUIDisclaimers = (lang: AppLang): string => UI_DICTIONARY[lang].disclaimer;
export const getUIInstructions = (lang: AppLang): string => UI_DICTIONARY[lang].instruction;
