import type { AppLang } from "./language.ts";

export type MoreCopy = {
  more: string;
  huid: string;
  huidJob: string;
  hallmark: string;
  hallmarkJob: string;
  standards: string;
  standardsJob: string;
  certify: string;
  certifyJob: string;
  complaint: string;
  complaintJob: string;
  contact: string;
  contactJob: string;
  check: string;
  pick: string;
  huidEyebrow: string;
  huidH1: string;
  huidLede: string;
  huidLabel: string;
  huidPh: string;
  huidHelp: string;
  huidEmpty: string;
  huidOk: string;
  huidBad: string;
  huidLicence: string;
  huidSteps: string[];
  notLive: string;
  openHuid: string;
  hmEyebrow: string;
  hmH1: string;
  hmLede: string;
  hmLabel: string;
  hmPh: string;
  hmMiss: string;
  hmSteps: string[];
  hmJeweller: string;
  gold: string;
  silver: string;
  platinum: string;
  both900: string;
  gradeLine: string;
  stEyebrow: string;
  stH1: string;
  stLede: string;
  stLabel: string;
  stPh: string;
  stSteps: string[];
  stHit: string;
  stMiss: string;
  stClarify: string;
  stOpen: string;
  ceEyebrow: string;
  ceH1: string;
  ceLede: string;
  isi: string;
  crs: string;
  fmcs: string;
  isiSteps: string[];
  crsSteps: string[];
  fmcsSteps: string[];
  openManak: string;
  openCrs: string;
  openBis: string;
  coEyebrow: string;
  coH1: string;
  coLede: string;
  coSteps: string[];
  openComplaint: string;
  emailLine: string;
  contactSteps: string[];
  contactTitle: string;
};

const EN: MoreCopy = {
  more: "More",
  huid: "HUID verification",
  huidJob: "Enter the 6-character code on the jewellery.",
  hallmark: "Hallmark finder",
  hallmarkJob: "Fineness grades such as 916 and 22K.",
  standards: "Indian Standards finder",
  standardsJob: "Match a product to a catalogue title.",
  certify: "Certification process",
  certifyJob: "ISI, CRS, and FMCS in short steps.",
  complaint: "File a complaint",
  complaintJob: "What to keep, and the official desk.",
  contact: "Contact us",
  contactJob: "Published BIS contact, at the foot of this page.",
  check: "Check",
  pick: "Pick one",
  huidEyebrow: "Hallmark",
  huidH1: "HUID verification",
  huidLede: "Type the 6-character code from the jewellery. The note explains the shape, then the official page.",
  huidLabel: "HUID",
  huidPh: "AB12CD",
  huidHelp: "Six letters and digits, as printed on the piece.",
  huidEmpty: "Enter the code from the jewellery.",
  huidOk: "{code} has the 6-character HUID shape.",
  huidBad: "That code does not match a 6-character HUID.",
  huidLicence: "That is a licence or registration number, not a jewellery HUID. Use Verify product for CM/L and R-numbers.",
  huidSteps: [
    "A HUID identifies one hallmarked piece. It is not a factory licence.",
    "This desk checks the shape only. It does not see the BIS CARE register, so this is not a pass or a fail.",
    "Open the official hallmarking page and enter the same code.",
    "On the piece, also read the BIS mark, the fineness, and the jeweller's mark.",
  ],
  notLive: "Not a live register lookup.",
  openHuid: "Open hallmarking",
  hmEyebrow: "Hallmark",
  hmH1: "Hallmark finder",
  hmLede: "Type a fineness or a carat, such as 916 or 22K. The note says what that grade means. It does not prove the piece in your hand.",
  hmLabel: "Fineness or carat",
  hmPh: "916 or 22K",
  hmMiss: "Pick a grade below, or type 916, 22K, or 925.",
  hmSteps: [
    "Fineness is parts per 1000. 916 means 916 parts gold in 1000.",
    "A hallmark is the BIS mark, the fineness, a HUID, and the jeweller's mark together.",
    "A spoken claim of 22 carat is not the same as reading 916 on the piece.",
    "Confirm the HUID on the official hallmarking page.",
  ],
  hmJeweller: "A jeweller's hallmarking registration is filed on the official hallmarking portal. This desk does not register a jeweller.",
  gold: "Gold",
  silver: "Silver",
  platinum: "Platinum",
  both900: "900 is also used for platinum. The metal is named on the hallmark.",
  gradeLine: "{tag} · {metal} fineness {id}.",
  stEyebrow: "Catalogue",
  stH1: "Indian Standards finder",
  stLede: "Name a product. If the authorised catalogue has a row, the finder names it. If not, it says so.",
  stLabel: "Product",
  stPh: "Cement, helmet, laptop",
  stSteps: [
    "Use the product name, or an IS number if you already have one.",
    "A number appears only when that row is in the catalogue loaded here.",
    "No row means this desk does not have it. It does not mean the standard does not exist.",
    "Confirm the title on Know Your Standard before you print it.",
  ],
  stHit: "Catalogue title for this name. Not a licence.",
  stMiss: "No catalogue pin for that name.",
  stClarify: "One more detail is needed before a single standard is named.",
  stOpen: "Know Your Standard",
  ceEyebrow: "Certification",
  ceH1: "Certification process",
  ceLede: "Pick a scheme. The steps lead to the official desk. This page does not file the application.",
  isi: "ISI · Scheme-I",
  crs: "CRS · Scheme-II",
  fmcs: "FMCS",
  isiSteps: [
    "Find the Indian Standard for the product on Know Your Standard.",
    "If a Quality Control Order applies, re-check the live compulsory list. This page does not guess that status.",
    "The ISI application is filed on MANAK Online.",
    "Tests go to a BIS recognised laboratory. The scope of a named test stays on LIMS.",
    "After a grant, the CM/L number is printed with the ISI mark. This desk does not grant it.",
  ],
  crsSteps: [
    "Scheme-II is the Compulsory Registration Scheme for notified electronics.",
    "It is not an ISI CM/L licence and not a jewellery HUID.",
    "The registration is filed on the CRS portal.",
    "A registration number has the R- shape, such as R-41000001.",
    "This desk does not register the product and does not take a fee.",
  ],
  fmcsSteps: [
    "FMCS is for an overseas factory seeking the ISI mark.",
    "It is not the domestic Scheme-I form, and not CRS.",
    "The application stays on the official BIS desk.",
    "A catalogue title here is not an FMCS grant.",
    "This desk does not file the form or quote a fee.",
  ],
  openManak: "Open MANAK",
  openCrs: "Open CRS",
  openBis: "Official BIS",
  coEyebrow: "Complaint",
  coH1: "File a complaint",
  coLede: "A fake or misused Standard Mark is filed with BIS, not with this desk.",
  coSteps: [
    "Keep a photo of the mark, the number printed with it, and the bill if you have one.",
    "File it on the official BIS complaint page, or email complaints@bis.gov.in.",
    "ManakMitra does not receive the complaint and does not open a case.",
    "A shop's assurance is not a result. The official page is.",
  ],
  openComplaint: "Open the BIS complaint page",
  emailLine: "complaints@bis.gov.in",
  contactTitle: "Published BIS contact",
  contactSteps: [
    "The published address is Manak Bhavan, 9 Bahadur Shah Zafar Marg, New Delhi.",
    "Complaints go to complaints@bis.gov.in or the official complaint page.",
    "This desk does not receive licence applications.",
  ],
};

function pack(p: Partial<MoreCopy>): MoreCopy {
  return {
    ...EN,
    ...p,
    huidSteps: p.huidSteps ?? EN.huidSteps,
    hmSteps: p.hmSteps ?? EN.hmSteps,
    stSteps: p.stSteps ?? EN.stSteps,
    isiSteps: p.isiSteps ?? EN.isiSteps,
    crsSteps: p.crsSteps ?? EN.crsSteps,
    fmcsSteps: p.fmcsSteps ?? EN.fmcsSteps,
    coSteps: p.coSteps ?? EN.coSteps,
    contactSteps: p.contactSteps ?? EN.contactSteps,
  };
}

const HI = pack({
  more: "और",
  huid: "HUID जाँच",
  huidJob: "गहने पर छपा 6 अक्षर का कोड डालें।",
  hallmark: "हॉलमार्क खोज",
  hallmarkJob: "916 और 22K जैसी शुद्धता।",
  standards: "भारतीय मानक खोज",
  standardsJob: "उत्पाद को कैटलॉग शीर्षक से मिलाएँ।",
  certify: "प्रमाणन प्रक्रिया",
  certifyJob: "ISI, CRS और FMCS, छोटे चरणों में।",
  complaint: "शिकायत दर्ज करें",
  complaintJob: "क्या रखना है, और आधिकारिक डेस्क।",
  contact: "संपर्क करें",
  contactJob: "प्रकाशित BIS संपर्क, इस पेज के नीचे।",
  check: "जाँचें",
  pick: "एक चुनें",
  huidEyebrow: "हॉलमार्क",
  huidH1: "HUID जाँच",
  huidLede: "गहने से 6 अक्षर का कोड लिखें। नोट आकार बताता है, फिर आधिकारिक पेज।",
  huidLabel: "HUID",
  huidPh: "AB12CD",
  huidHelp: "टुकड़े पर छपे छह अक्षर और अंक।",
  huidEmpty: "गहने वाला कोड लिखें।",
  huidOk: "{code} का आकार 6 अक्षर वाले HUID जैसा है।",
  huidBad: "यह कोड 6 अक्षर वाले HUID से नहीं मिलता।",
  huidLicence: "यह लाइसेंस या रजिस्ट्रेशन नंबर है, गहनों का HUID नहीं। CM/L और R-नंबर के लिए उत्पाद जाँचें।",
  huidSteps: [
    "HUID एक हॉलमार्क किए टुकड़े की पहचान है। यह फ़ैक्टरी लाइसेंस नहीं है।",
    "यह डेस्क सिर्फ़ आकार देखती है। BIS CARE रजिस्टर नहीं खुलता, इसलिए यह पास या फेल नहीं है।",
    "आधिकारिक हॉलमार्किंग पेज खोलकर वही कोड डालें।",
    "टुकड़े पर BIS चिह्न, शुद्धता और जौहरी का चिह्न भी पढ़ें।",
  ],
  notLive: "लाइव रजिस्टर नहीं खोला गया।",
  openHuid: "हॉलमार्किंग खोलें",
  hmEyebrow: "हॉलमार्क",
  hmH1: "हॉलमार्क खोज",
  hmLede: "916 या 22K जैसी शुद्धता लिखें। नोट बताता है कि ग्रेड का क्या अर्थ है। हाथ के टुकड़े का प्रमाण नहीं।",
  hmLabel: "शुद्धता या कैरेट",
  hmPh: "916 या 22K",
  hmMiss: "नीचे से ग्रेड चुनें, या 916, 22K, या 925 लिखें।",
  hmSteps: [
    "शुद्धता प्रति 1000 भाग है। 916 का अर्थ है 1000 में 916 भाग सोना।",
    "हॉलमार्क में BIS चिह्न, शुद्धता, HUID और जौहरी का चिह्न साथ होते हैं।",
    "मुँह से कहा 22 कैरेट, टुकड़े पर छपा 916 नहीं है।",
    "HUID आधिकारिक हॉलमार्किंग पेज पर जाँचें।",
  ],
  hmJeweller: "जौहरी का हॉलमार्किंग पंजीकरण आधिकारिक पोर्टल पर होता है। यह डेस्क जौहरी दर्ज नहीं करती।",
  gold: "सोना",
  silver: "चाँदी",
  platinum: "प्लेटिनम",
  both900: "900 प्लेटिनम के लिए भी है। धातु हॉलमार्क पर लिखी होती है।",
  gradeLine: "{tag} · {metal} शुद्धता {id}।",
  stEyebrow: "कैटलॉग",
  stH1: "भारतीय मानक खोज",
  stLede: "उत्पाद का नाम लिखें। अधिकृत कैटलॉग में पंक्ति हो तो खोज उसे बताती है। नहीं हो तो साफ कहती है।",
  stLabel: "उत्पाद",
  stPh: "सीमेंट, हेलमेट, लैपटॉप",
  stSteps: [
    "उत्पाद का नाम लिखें, या IS नंबर अगर पहले से पता हो।",
    "नंबर तभी आता है जब वह पंक्ति इस कैटलॉग में हो।",
    "पंक्ति न होना मतलब यहाँ रिकॉर्ड नहीं। यह नहीं कि मानक है ही नहीं।",
    "उत्पाद पर छापने से पहले Know Your Standard पर शीर्षक जाँचें।",
  ],
  stHit: "इस नाम का कैटलॉग शीर्षक। लाइसेंस नहीं।",
  stMiss: "इस नाम का कैटलॉग पिन नहीं है।",
  stClarify: "एक मानक नामने से पहले एक और विवरण चाहिए।",
  stOpen: "Know Your Standard",
  ceEyebrow: "प्रमाणन",
  ceH1: "प्रमाणन प्रक्रिया",
  ceLede: "एक योजना चुनें। चरण आधिकारिक डेस्क तक ले जाते हैं। यह पेज आवेदन नहीं भरता।",
  isi: "ISI · योजना-I",
  crs: "CRS · योजना-II",
  fmcs: "FMCS",
  isiSteps: [
    "उत्पाद का भारतीय मानक Know Your Standard पर देखें।",
    "Quality Control Order हो तो लाइव अनिवार्य सूची फिर देखें। यह पेज वह स्थिति अनुमान नहीं लगाता।",
    "ISI आवेदन MANAK Online पर भरा जाता है।",
    "जाँच BIS मान्यता प्राप्त प्रयोगशाला में होती है। नाम वाले परीक्षण का दायरा LIMS पर है।",
    "मंजूरी के बाद CM/L नंबर ISI चिह्न के साथ छपता है। यह डेस्क मंजूरी नहीं देती।",
  ],
  crsSteps: [
    "योजना-II अधिसूचित इलेक्ट्रॉनिक्स की अनिवार्य पंजीकरण योजना है।",
    "यह ISI का CM/L लाइसेंस नहीं और गहनों का HUID नहीं।",
    "पंजीकरण CRS पोर्टल पर होता है।",
    "पंजीकरण नंबर R- आकार का होता है, जैसे R-41000001।",
    "यह डेस्क उत्पाद दर्ज नहीं करती और शुल्क नहीं लेती।",
  ],
  fmcsSteps: [
    "FMCS विदेश की फ़ैक्टरी के लिए है जो ISI चिह्न चाहती है।",
    "यह घरेलू योजना-I का फ़ॉर्म नहीं, और CRS नहीं।",
    "आवेदन आधिकारिक BIS डेस्क पर रहता है।",
    "यहाँ का कैटलॉग शीर्षक FMCS मंजूरी नहीं है।",
    "यह डेस्क फ़ॉर्म नहीं भरती और शुल्क नहीं बताती।",
  ],
  openManak: "MANAK खोलें",
  openCrs: "CRS खोलें",
  openBis: "आधिकारिक BIS",
  coEyebrow: "शिकायत",
  coH1: "शिकायत दर्ज करें",
  coLede: "नकली या दुरुपयोग किया मानक चिह्न BIS के पास दर्ज होता है, इस डेस्क पर नहीं।",
  coSteps: [
    "चिह्न की फ़ोटो, साथ छपा नंबर, और बिल रखें अगर हो।",
    "आधिकारिक BIS शिकायत पेज पर दर्ज करें, या complaints@bis.gov.in पर लिखें।",
    "मानक मित्र शिकायत नहीं लेता और केस नहीं खोलता।",
    "दुकान का आश्वासन नतीजा नहीं है। आधिकारिक पेज है।",
  ],
  openComplaint: "BIS शिकायत पेज खोलें",
  emailLine: "complaints@bis.gov.in",
  contactTitle: "प्रकाशित BIS संपर्क",
  contactSteps: [
    "प्रकाशित पता मानक भवन, 9 बहादुर शाह ज़फ़र मार्ग, नई दिल्ली है।",
    "शिकायत complaints@bis.gov.in या आधिकारिक शिकायत पेज पर जाती है।",
    "यह डेस्क लाइसेंस आवेदन नहीं लेती।",
  ],
});

const BN = pack({
  more: "আরও",
  huid: "HUID যাচাই",
  huidJob: "গয়নায় ছাপা ৬ অক্ষরের কোড দিন।",
  hallmark: "হলমার্ক খোঁজ",
  hallmarkJob: "৯১৬ ও 22K-এর মতো বিশুদ্ধতা।",
  standards: "ভারতীয় মান খোঁজ",
  standardsJob: "পণ্যকে ক্যাটালগ শিরোনামের সাথে মেলান।",
  certify: "সার্টিফিকেশন প্রক্রিয়া",
  certifyJob: "ISI, CRS ও FMCS — ছোট ধাপ।",
  complaint: "অভিযোগ জমা",
  complaintJob: "কী রাখবেন, এবং সরকারি ডেস্ক।",
  contact: "যোগাযোগ",
  contactJob: "প্রকাশিত BIS যোগাযোগ, এই পাতার নিচে।",
  check: "যাচাই",
  pick: "একটি বাছুন",
  huidEyebrow: "হলমার্ক",
  huidH1: "HUID যাচাই",
  huidLede: "গয়না থেকে ৬ অক্ষরের কোড লিখুন। নোট আকার বলে, তারপর সরকারি পাতা।",
  huidLabel: "HUID",
  huidHelp: "টুকরোতে ছাপা ছয়টি অক্ষর ও সংখ্যা।",
  huidEmpty: "গয়নার কোড লিখুন।",
  huidOk: "{code} ৬ অক্ষরের HUID আকারের।",
  huidBad: "এই কোড ৬ অক্ষরের HUID-এর সাথে মেলে না।",
  huidLicence: "এটি লাইসেন্স বা নিবন্ধন নম্বর, গয়নার HUID নয়। CM/L ও R-নম্বরের জন্য পণ্য যাচাই ব্যবহার করুন।",
  huidSteps: [
    "HUID একটি হলমার্ক করা টুকরোর পরিচয়। এটি কারখানার লাইসেন্স নয়।",
    "এই ডেস্ক শুধু আকার দেখে। BIS CARE রেজিস্টার খোলে না, তাই এটি পাস বা ফেল নয়।",
    "সরকারি হলমার্কিং পাতায় একই কোড দিন।",
    "টুকরোতে BIS চিহ্ন, বিশুদ্ধতা ও জুয়েলারের চিহ্নও পড়ুন।",
  ],
  notLive: "লাইভ রেজিস্টার খোলা হয়নি।",
  openHuid: "হলমার্কিং খুলুন",
  hmEyebrow: "হলমার্ক",
  hmH1: "হলমার্ক খোঁজ",
  hmLede: "৯১৬ বা 22K লিখুন। নোট গ्रेडের অর্থ বলে। হাতের টুকরোর প্রমাণ নয়।",
  hmLabel: "বিশুদ্ধতা বা ক্যারেট",
  hmPh: "916 বা 22K",
  hmMiss: "নিচ থেকে গ্রেড বাছুন, বা 916, 22K, বা 925 লিখুন।",
  hmSteps: [
    "বিশুদ্ধতা প্রতি ১০০০ ভাগ। ৯১৬ মানে ১০০০-এ ৯১৬ ভাগ সোনা।",
    "হলমার্কে BIS চিহ্ন, বিশুদ্ধতা, HUID ও জুয়েলারের চিহ্ন একসাথে থাকে।",
    "মুখে বলা ২২ ক্যারেট, টুকরোতে ছাপা ৯১৬ নয়।",
    "HUID সরকারি হলমার্কিং পাতায় দেখুন।",
  ],
  hmJeweller: "জুয়েলারের হলমার্ক নিবন্ধন সরকারি পোর্টালে হয়। এই ডেস্ক জুয়েলার নথিভুক্ত করে না।",
  gold: "সোনা",
  silver: "রূপা",
  platinum: "প্লাটিনাম",
  both900: "৯০০ প্লাটিনামেও ব্যবহৃত। ধাতুর নাম হলমার্কে থাকে।",
  gradeLine: "{tag} · {metal} বিশুদ্ধতা {id}।",
  stEyebrow: "ক্যাটালগ",
  stH1: "ভারতীয় মান খোঁজ",
  stLede: "পণ্যের নাম লিখুন। অনুমোদিত ক্যাটালগে সারি থাকলে খোঁজ সেটি বলে। না থাকলে স্পষ্ট বলে।",
  stLabel: "পণ্য",
  stPh: "সিমেন্ট, হেলমেট, ল্যাপটপ",
  stSteps: [
    "পণ্যের নাম লিখুন, বা IS নম্বর যদি জানা থাকে।",
    "নম্বর তখনই আসে যখন সারি এই ক্যাটালগে থাকে।",
    "সারি না থাকা মানে এখানে রেকর্ড নেই। মান নেই এমন নয়।",
    "ছাপার আগে Know Your Standard-এ শিরোনাম দেখুন।",
  ],
  stHit: "এই নামের ক্যাটালগ শিরোনাম। লাইসেন্স নয়।",
  stMiss: "এই নামের ক্যাটালগ পিন নেই।",
  stClarify: "একটি মান নাম দেওয়ার আগে আর একটি বিবরণ দরকার।",
  stOpen: "Know Your Standard",
  ceEyebrow: "সার্টিফিকেশন",
  ceH1: "সার্টিফিকেশন প্রক্রিয়া",
  ceLede: "একটি স্কিম বাছুন। ধাপ সরকারি ডেস্কে নিয়ে যায়। এই পাতা আবেদন জমা করে না।",
  isi: "ISI · স্কিম-I",
  crs: "CRS · স্কিম-II",
  fmcs: "FMCS",
  isiSteps: [
    "পণ্যের ভারতীয় মান Know Your Standard-এ দেখুন।",
    "Quality Control Order থাকলে লাইভ বাধ্যতামূলক তালিকা আবার দেখুন। এই পাতা অনুমান করে না।",
    "ISI আবেদন MANAK Online-এ জমা হয়।",
    "পরীক্ষা BIS স্বীকৃত ল্যাবে হয়। নাম করা পরীক্ষার পরিধি LIMS-এ।",
    "অনুমোদনের পর CM/L নম্বর ISI চিহ্নের সাথে ছাপা হয়। এই ডেস্ক অনুমোদন দেয় না।",
  ],
  crsSteps: [
    "স্কিম-II বিজ্ঞপ্তিকৃত ইলেকট্রনিক্সের বাধ্যতামূলক নিবন্ধন।",
    "এটি ISI-র CM/L লাইসেন্স নয় এবং গয়নার HUID নয়।",
    "নিবন্ধন CRS পোর্টালে হয়।",
    "নিবন্ধন নম্বর R- আকারের, যেমন R-41000001।",
    "এই ডেস্ক পণ্য নিবন্ধন করে না এবং ফি নেয় না।",
  ],
  fmcsSteps: [
    "FMCS বিদেশি কারখানার জন্য, যারা ISI চিহ্ন চায়।",
    "এটি দেশীয় স্কিম-I ফর্ম নয়, CRSও নয়।",
    "আবেদন সরকারি BIS ডেস্কে থাকে।",
    "এখানকার ক্যাটালগ শিরোনাম FMCS অনুমোদন নয়।",
    "এই ডেস্ক ফর্ম জমা করে না এবং ফি বলে না।",
  ],
  openManak: "MANAK খুলুন",
  openCrs: "CRS খুলুন",
  openBis: "সরকারি BIS",
  coEyebrow: "অভিযোগ",
  coH1: "অভিযোগ জমা",
  coLede: "নকল বা অপব্যবহার করা স্ট্যান্ডার্ড মার্ক BIS-এ জমা হয়, এই ডেস্কে নয়।",
  coSteps: [
    "চিহ্নের ছবি, সাথে ছাপা নম্বর, এবং বিল রাখুন।",
    "সরকারি BIS অভিযোগ পাতায় জমা দিন, বা complaints@bis.gov.in-এ লিখুন।",
    "মানক মিত্র অভিযোগ নেয় না এবং মামলা খোলে না।",
    "দোকানের আশ্বাস ফল নয়। সরকারি পাতাই ফল।",
  ],
  openComplaint: "BIS অভিযোগ পাতা খুলুন",
  contactTitle: "প্রকাশিত BIS যোগাযোগ",
  contactSteps: [
    "প্রকাশিত ঠিকানা মানক ভবন, ৯ বাহাদুর শাহ জাফর মার্গ, নতুন দিল্লি।",
    "অভিযোগ complaints@bis.gov.in বা সরকারি অভিযোগ পাতায় যায়।",
    "এই ডেস্ক লাইসেন্স আবেদন নেয় না।",
  ],
});

const TA = pack({
  more: "மேலும்",
  huid: "HUID சரிபார்ப்பு",
  huidJob: "நகையில் உள்ள 6 எழுத்துக் குறியீட்டை உள்ளிடவும்.",
  hallmark: "ஹால்மார்க் தேடல்",
  hallmarkJob: "916 மற்றும் 22K போன்ற தூய்மை.",
  standards: "இந்திய தரத் தேடல்",
  standardsJob: "பொருளை அட்டவணை தலைப்புடன் பொருத்தவும்.",
  certify: "சான்றிதழ் செயல்முறை",
  certifyJob: "ISI, CRS, FMCS — சிறிய படிகள்.",
  complaint: "புகார் பதிவு",
  complaintJob: "எதை வைத்திருக்க வேண்டும், அதிகாரப்பூர்வ மேசை.",
  contact: "தொடர்பு",
  contactJob: "வெளியிடப்பட்ட BIS தொடர்பு, இந்தப் பக்கத்தின் அடியில்.",
  check: "சரிபார்",
  pick: "ஒன்றைத் தேர்ந்தெடு",
  huidEyebrow: "ஹால்மார்க்",
  huidH1: "HUID சரிபார்ப்பு",
  huidLede: "நகையிலிருந்து 6 எழுத்துக் குறியீட்டை எழுதவும். குறிப்பு வடிவத்தைச் சொல்லும், பிறகு அதிகாரப்பூர்வ பக்கம்.",
  huidHelp: "பொருளில் அச்சிடப்பட்ட ஆறு எழுத்துகளும் எண்களும்.",
  huidEmpty: "நகைக் குறியீட்டை உள்ளிடவும்.",
  huidOk: "{code} 6 எழுத்து HUID வடிவம்.",
  huidBad: "இந்தக் குறியீடு 6 எழுத்து HUID உடன் பொருந்தவில்லை.",
  huidLicence: "இது உரிமம் அல்லது பதிவு எண், நகை HUID அல்ல. CM/L மற்றும் R-எண்களுக்கு பொருள் சரிபார்ப்பைப் பயன்படுத்தவும்.",
  huidSteps: [
    "HUID ஒரு ஹால்மார்க் செய்யப்பட்ட பொருளின் அடையாளம். தொழிற்சாலை உரிமம் அல்ல.",
    "இந்த மேசை வடிவத்தை மட்டும் பார்க்கும். BIS CARE பதிவேட்டைத் திறக்காது. இது தேர்ச்சி அல்லது தோல்வி அல்ல.",
    "அதிகாரப்பூர்வ ஹால்மார்க் பக்கத்தில் அதே குறியீட்டை உள்ளிடவும்.",
    "பொருளில் BIS குறி, தூய்மை, நகைக்கடை குறியையும் படிக்கவும்.",
  ],
  notLive: "நேரடி பதிவேடு திறக்கப்படவில்லை.",
  openHuid: "ஹால்மார்க்கிங் திற",
  hmEyebrow: "ஹால்மார்க்",
  hmH1: "ஹால்மார்க் தேடல்",
  hmLede: "916 அல்லது 22K எழுதவும். குறிப்பு தரத்தின் பொருளைச் சொல்லும். கையில் உள்ள பொருளின் சான்று அல்ல.",
  hmLabel: "தூய்மை அல்லது கேரட்",
  hmPh: "916 அல்லது 22K",
  hmMiss: "கீழிருந்து தரத்தைத் தேர்ந்தெடுக்கவும், அல்லது 916, 22K, அல்லது 925 எழுதவும்.",
  hmSteps: [
    "தூய்மை 1000-க்கு பங்கு. 916 என்றால் 1000-ல் 916 பங்கு தங்கம்.",
    "ஹால்மார்க்கில் BIS குறி, தூய்மை, HUID, நகைக்கடை குறி இணைந்து இருக்கும்.",
    "வாயில் சொன்ன 22 கேரட், பொருளில் படித்த 916 அல்ல.",
    "HUID-ஐ அதிகாரப்பூர்வ ஹால்மார்க் பக்கத்தில் உறுதிசெய்யவும்.",
  ],
  hmJeweller: "நகைக்கடை ஹால்மார்க் பதிவு அதிகாரப்பூர்வ தளத்தில். இந்த மேசை நகைக்கடையைப் பதிவு செய்யாது.",
  gold: "தங்கம்",
  silver: "வெள்ளி",
  platinum: "பிளாட்டினம்",
  both900: "900 பிளாட்டினத்துக்கும் உண்டு. உலோகப் பெயர் ஹால்மார்க்கில் இருக்கும்.",
  gradeLine: "{tag} · {metal} தூய்மை {id}.",
  stEyebrow: "அட்டவணை",
  stH1: "இந்திய தரத் தேடல்",
  stLede: "பொருளின் பெயரை எழுதவும். அங்கீகரிக்கப்பட்ட அட்டவணையில் வரிசை இருந்தால் தேடல் அதைச் சொல்லும். இல்லையென்றால் தெளிவாகச் சொல்லும்.",
  stLabel: "பொருள்",
  stPh: "சிமெண்ட், ஹெல்மெட், மடிக்கணினி",
  stSteps: [
    "பொருளின் பெயர், அல்லது தெரிந்தால் IS எண்.",
    "வரிசை இந்த அட்டவணையில் இருந்தால் மட்டுமே எண் வரும்.",
    "வரிசை இல்லை என்றால் இங்கே பதிவு இல்லை. தரம் இல்லை என்று அர்த்தமல்ல.",
    "அச்சிடுவதற்கு முன் Know Your Standard-ல் தலைப்பைப் பார்க்கவும்.",
  ],
  stHit: "இந்தப் பெயரின் அட்டவணைத் தலைப்பு. உரிமம் அல்ல.",
  stMiss: "இந்தப் பெயருக்கு அட்டவணைப் பின் இல்லை.",
  stClarify: "ஒரு தரத்தைக் குறிக்க இன்னும் ஒரு விவரம் வேண்டும்.",
  ceEyebrow: "சான்றிதழ்",
  ceH1: "சான்றிதழ் செயல்முறை",
  ceLede: "ஒரு திட்டத்தைத் தேர்ந்தெடுக்கவும். படிகள் அதிகாரப்பூர்வ மேசைக்கு இட்டுச் செல்லும். இந்தப் பக்கம் விண்ணப்பத்தைச் சமர்ப்பிக்காது.",
  isi: "ISI · திட்டம்-I",
  crs: "CRS · திட்டம்-II",
  isiSteps: [
    "பொருளின் இந்திய தரத்தை Know Your Standard-ல் பார்க்கவும்.",
    "Quality Control Order இருந்தால் நேரடி கட்டாயப் பட்டியலை மீண்டும் பார்க்கவும். இந்தப் பக்கம் ஊகிக்காது.",
    "ISI விண்ணப்பம் MANAK Online-ல் தாக்கல் செய்யப்படும்.",
    "சோதனை BIS அங்கீகரித்த ஆய்வகத்தில். பெயரிட்ட சோதனை வரம்பு LIMS-ல்.",
    "வழங்கலுக்குப் பின் CM/L எண் ISI குறியுடன் அச்சிடப்படும். இந்த மேசை வழங்காது.",
  ],
  crsSteps: [
    "திட்டம்-II அறிவிக்கப்பட்ட மின்னணுவியலுக்கான கட்டாயப் பதிவு.",
    "இது ISI CM/L உரிமம் அல்ல, நகை HUID அல்ல.",
    "பதிவு CRS தளத்தில்.",
    "பதிவு எண் R- வடிவம், எடுத்துக்காட்டு R-41000001.",
    "இந்த மேசை பொருளைப் பதிவு செய்யாது, கட்டணம் வாங்காது.",
  ],
  fmcsSteps: [
    "FMCS வெளிநாட்டுத் தொழிற்சாலைக்கு, ISI குறி வேண்டுமென்றால்.",
    "இது உள்நாட்டு திட்டம்-I படிவம் அல்ல, CRS அல்ல.",
    "விண்ணப்பம் அதிகாரப்பூர்வ BIS மேசையில் இருக்கும்.",
    "இங்குள்ள அட்டவணைத் தலைப்பு FMCS வழங்கல் அல்ல.",
    "இந்த மேசை படிவத்தைத் தாக்கல் செய்யாது, கட்டணம் சொல்லாது.",
  ],
  openManak: "MANAK திற",
  openCrs: "CRS திற",
  openBis: "அதிகாரப்பூர்வ BIS",
  coEyebrow: "புகார்",
  coH1: "புகார் பதிவு",
  coLede: "போலி அல்லது தவறாகப் பயன்படுத்திய தரக் குறி BIS-இல் பதிவாகும், இந்த மேசையில் அல்ல.",
  coSteps: [
    "குறியின் புகைப்படம், அச்சிட்ட எண், இருக்கும் பட்சத்தில் ரசீதை வைத்திருக்கவும்.",
    "அதிகாரப்பூர்வ BIS புகார் பக்கத்தில் பதிவு செய்யவும், அல்லது complaints@bis.gov.in-க்கு எழுதவும்.",
    "மானக்மித்ரா புகாரைப் பெறாது, வழக்கைத் திறக்காது.",
    "கடையின் உறுதி முடிவு அல்ல. அதிகாரப்பூர்வப் பக்கம்தான்.",
  ],
  openComplaint: "BIS புகார் பக்கத்தைத் திற",
  contactTitle: "வெளியிடப்பட்ட BIS தொடர்பு",
  contactSteps: [
    "வெளியிடப்பட்ட முகவரி மானக் பவன், 9 பகதூர் ஷா சஃபர் மார்க், புது தில்லி.",
    "புகார் complaints@bis.gov.in அல்லது அதிகாரப்பூர்வ புகார் பக்கத்துக்குச் செல்லும்.",
    "இந்த மேசை உரிம விண்ணப்பத்தைப் பெறாது.",
  ],
});

const TE = pack({
  more: "మరిన్ని",
  huid: "HUID తనిఖీ",
  huidJob: "ఆభరణంపై ఉన్న 6 అక్షరాల కోడ్ ఇవ్వండి.",
  hallmark: "హాల్‌మార్క్ వెతకడం",
  hallmarkJob: "916 మరియు 22K వంటి స్వచ్ఛత.",
  standards: "భారతీయ ప్రమాణ శోధన",
  standardsJob: "ఉత్పత్తిని కేటలాగ్ శీర్షికతో జోడించండి.",
  certify: "ధృవీకరణ ప్రక్రియ",
  certifyJob: "ISI, CRS, FMCS — చిన్న అడుగులు.",
  complaint: "ఫిర్యాదు",
  complaintJob: "ఏమి ఉంచాలి, అధికారిక డెస్క్.",
  contact: "సంప్రదించండి",
  contactJob: "ప్రచురిత BIS సంప్రదింపు, ఈ పేజీ కింద.",
  check: "తనిఖీ",
  pick: "ఒకటి ఎంచుకోండి",
  huidEyebrow: "హాల్‌మార్క్",
  huidH1: "HUID తనిఖీ",
  huidLede: "ఆభరణం నుండి 6 అక్షరాల కోడ్ రాయండి. నోట్ ఆకారం చెబుతుంది, తర్వాత అధికార పేజీ.",
  huidHelp: "ముక్కపై ముద్రించిన ఆరు అక్షరాలు మరియు అంకెలు.",
  huidEmpty: "ఆభరణపు కోడ్ రాయండి.",
  huidOk: "{code} 6 అక్షరాల HUID ఆకారం.",
  huidBad: "ఈ కోడ్ 6 అక్షరాల HUID తో కుదరదు.",
  huidLicence: "ఇది లైసెన్స్ లేదా నమోదు సంఖ్య, ఆభరణపు HUID కాదు. CM/L మరియు R-సంఖ్యలకు ఉత్పత్తి తనిఖీ వాడండి.",
  huidSteps: [
    "HUID ఒక హాల్‌మార్క్ ముక్క గుర్తు. ఫ్యాక్టరీ లైసెన్స్ కాదు.",
    "ఈ డెస్క్ ఆకారం మాత్రమే చూస్తుంది. BIS CARE రిజిస్టర్ తెరవదు. ఇది పాస్ లేదా ఫెయిల్ కాదు.",
    "అధికారిక హాల్‌మార్క్ పేజీలో అదే కోడ్ ఇవ్వండి.",
    "ముక్కపై BIS గుర్తు, స్వచ్ఛత, వర్తకుని గుర్తు కూడా చదవండి.",
  ],
  notLive: "లైవ్ రిజిస్టర్ తెరవలేదు.",
  openHuid: "హాల్‌మార్కింగ్ తెరవండి",
  hmEyebrow: "హాల్‌మార్క్",
  hmH1: "హాల్‌మార్క్ వెతకడం",
  hmLede: "916 లేదా 22K రాయండి. నోట్ గ్రేడ్ అర్థం చెబుతుంది. చేతిలోని ముక్కకు రుజువు కాదు.",
  hmLabel: "స్వచ్ఛత లేదా క్యారెట్",
  hmPh: "916 లేదా 22K",
  hmMiss: "కింద నుండి గ్రేడ్ ఎంచుకోండి, లేదా 916, 22K, లేదా 925 రాయండి.",
  hmSteps: [
    "స్వచ్ఛత 1000కి భాగాలు. 916 అంటే 1000లో 916 భాగాలు బంగారం.",
    "హాల్‌మార్క్‌లో BIS గుర్తు, స్వచ్ఛత, HUID, వర్తకుని గుర్తు కలిసి ఉంటాయి.",
    "నోటితో చెప్పిన 22 క్యారెట్, ముక్కపై ఉన్న 916 కాదు.",
    "HUIDని అధికారిక హాల్‌మార్క్ పేజీలో నిర్ధారించండి.",
  ],
  hmJeweller: "వర్తకుని హాల్‌మార్క్ నమోదు అధికారిక పోర్టల్‌లో. ఈ డెస్క్ వర్తకుని నమోదు చేయదు.",
  gold: "బంగారం",
  silver: "వెండి",
  platinum: "ప్లాటినం",
  both900: "900 ప్లాటినానికి కూడా వాడతారు. లోహం పేరు హాల్‌మార్క్‌పై ఉంటుంది.",
  gradeLine: "{tag} · {metal} స్వచ్ఛత {id}.",
  stEyebrow: "కేటలాగ్",
  stH1: "భారతీయ ప్రమాణ శోధన",
  stLede: "ఉత్పత్తి పేరు రాయండి. అధికార కేటలాగ్‌లో వరుస ఉంటే శోధన చెబుతుంది. లేకపోతే స్పష్టంగా చెబుతుంది.",
  stLabel: "ఉత్పత్తి",
  stPh: "సిమెంట్, హెల్మెట్, ల్యాప్‌టాప్",
  stSteps: [
    "ఉత్పత్తి పేరు, లేదా తెలిస్తే IS సంఖ్య.",
    "వరుస ఈ కేటలాగ్‌లో ఉంటేనే సంఖ్య వస్తుంది.",
    "వరుస లేకపోవడం ఇక్కడ రికార్డు లేదని. ప్రమాణం లేదని కాదు.",
    "ముద్రించే ముందు Know Your Standardలో శీర్షిక చూడండి.",
  ],
  stHit: "ఈ పేరు కేటలాగ్ శీర్షిక. లైసెన్స్ కాదు.",
  stMiss: "ఈ పేరుకు కేటలాగ్ పిన్ లేదు.",
  stClarify: "ఒక ప్రమాణం పేరు పెట్టే ముందు ఇంకో వివరం కావాలి.",
  ceEyebrow: "ధృవీకరణ",
  ceH1: "ధృవీకరణ ప్రక్రియ",
  ceLede: "ఒక పథకం ఎంచుకోండి. అడుగులు అధికారిక డెస్క్‌కు తీసుకెళ్తాయి. ఈ పేజీ దరఖాస్తు పంపదు.",
  isi: "ISI · పథకం-I",
  crs: "CRS · పథకం-II",
  isiSteps: [
    "ఉత్పత్తి భారతీయ ప్రమాణం Know Your Standardలో చూడండి.",
    "Quality Control Order ఉంటే లైవ్ తప్పనిసరి జాబితా మళ్లీ చూడండి. ఈ పేజీ ఊహించదు.",
    "ISI దరఖాస్తు MANAK Onlineలో.",
    "పరీక్ష BIS గుర్తింపు ప్రయోగశాలలో. పేరున్న పరీక్ష పరిధి LIMSలో.",
    "మంజూరు తర్వాత CM/L సంఖ్య ISI గుర్తుతో ముద్రిస్తారు. ఈ డెస్క్ మంజూరు చేయదు.",
  ],
  crsSteps: [
    "పథకం-II నోటిఫై చేసిన ఎలక్ట్రానిక్స్ తప్పనిసరి నమోదు.",
    "ఇది ISI CM/L లైసెన్స్ కాదు, ఆభరణ HUID కాదు.",
    "నమోదు CRS పోర్టల్‌లో.",
    "నమోదు సంఖ్య R- ఆకారం, ఉదాహరణ R-41000001.",
    "ఈ డెస్క్ ఉత్పత్తిని నమోదు చేయదు, రుసుము తీసుకోదు.",
  ],
  fmcsSteps: [
    "FMCS విదేశీ ఫ్యాక్టరీకి, ISI గుర్తు కావాలంటే.",
    "ఇది దేశీయ పథకం-I ఫారం కాదు, CRS కాదు.",
    "దరఖాస్తు అధికారిక BIS డెస్క్‌లో ఉంటుంది.",
    "ఇక్కడి కేటలాగ్ శీర్షిక FMCS మంజూరు కాదు.",
    "ఈ డెస్క్ ఫారం పంపదు, రుసుము చెప్పదు.",
  ],
  openManak: "MANAK తెరవండి",
  openCrs: "CRS తెరవండి",
  openBis: "అధికారిక BIS",
  coEyebrow: "ఫిర్యాదు",
  coH1: "ఫిర్యాదు దాఖలు",
  coLede: "నకిలీ లేదా దుర్వినియోగ ప్రమాణ గుర్తు BIS వద్ద దాఖలవుతుంది, ఈ డెస్క్ వద్ద కాదు.",
  coSteps: [
    "గుర్తు ఫోటో, ముద్రిత సంఖ్య, ఉంటే బిల్లు ఉంచండి.",
    "అధికారిక BIS ఫిర్యాదు పేజీలో దాఖలు చేయండి, లేదా complaints@bis.gov.in కు రాయండి.",
    "మానక్ మిత్ర ఫిర్యాదు తీసుకోదు, కేసు తెరవదు.",
    "దుకాణం హామీ ఫలితం కాదు. అధికార పేజీ ఫలితం.",
  ],
  openComplaint: "BIS ఫిర్యాదు పేజీ తెరవండి",
  contactTitle: "ప్రచురిత BIS సంప్రదింపు",
  contactSteps: [
    "ప్రచురిత చిరునామా మానక్ భవన్, 9 బహదూర్ షా జఫర్ మార్గ్, న్యూ ఢిల్లీ.",
    "ఫిర్యాదు complaints@bis.gov.in లేదా అధికారిక ఫిర్యాదు పేజీకి వెళ్తుంది.",
    "ఈ డెస్క్ లైసెన్సు దరఖాస్తులు తీసుకోదు.",
  ],
});

const MR = pack({
  more: "अधिक",
  huid: "HUID तपासणी",
  huidJob: "दागिन्यावरील 6 अक्षरी कोड टाका.",
  hallmark: "हॉलमार्क शोध",
  hallmarkJob: "916 आणि 22K सारखी शुद्धता.",
  standards: "भारतीय मानक शोध",
  standardsJob: "उत्पादन कॅटलॉग शीर्षकाशी जुळवा.",
  certify: "प्रमाणन प्रक्रिया",
  certifyJob: "ISI, CRS आणि FMCS — छोटे टप्पे.",
  complaint: "तक्रार नोंदवा",
  complaintJob: "काय ठेवायचे, आणि अधिकृत डेस्क.",
  contact: "संपर्क",
  contactJob: "प्रकाशित BIS संपर्क, या पानाच्या खाली.",
  check: "तपासा",
  pick: "एक निवडा",
  huidEyebrow: "हॉलमार्क",
  huidH1: "HUID तपासणी",
  huidLede: "दागिन्यावरील 6 अक्षरी कोड लिहा. नोंद आकार सांगते, मग अधिकृत पान.",
  huidHelp: "वस्तूवर छापलेले सहा अक्षर आणि अंक.",
  huidEmpty: "दागिन्याचा कोड लिहा.",
  huidOk: "{code} चा आकार 6 अक्षरी HUID सारखा आहे.",
  huidBad: "हा कोड 6 अक्षरी HUID शी जुळत नाही.",
  huidLicence: "हा परवाना किंवा नोंदणी क्रमांक आहे, दागिन्याचा HUID नाही. CM/L आणि R-क्रमांकासाठी उत्पादन तपासा.",
  huidSteps: [
    "HUID एका हॉलमार्क केलेल्या वस्तूची ओळख आहे. कारखाना परवाना नाही.",
    "ही डेस्क फक्त आकार पाहते. BIS CARE नोंदवही उघडत नाही. हे पास किंवा फेल नाही.",
    "अधिकृत हॉलमार्किंग पानावर तोच कोड टाका.",
    "वस्तूवर BIS चिन्ह, शुद्धता आणि सोनाराचे चिन्हही वाचा.",
  ],
  notLive: "थेट नोंदवही उघडली नाही.",
  openHuid: "हॉलमार्किंग उघडा",
  hmEyebrow: "हॉलमार्क",
  hmH1: "हॉलमार्क शोध",
  hmLede: "916 किंवा 22K लिहा. नोंद ग्रेडचा अर्थ सांगते. हातातील वस्तूचा पुरावा नाही.",
  hmLabel: "शुद्धता किंवा कॅरेट",
  hmPh: "916 किंवा 22K",
  hmMiss: "खालील ग्रेड निवडा, किंवा 916, 22K, किंवा 925 लिहा.",
  hmSteps: [
    "शुद्धता प्रति 1000 भाग. 916 म्हणजे 1000 मध्ये 916 भाग सोने.",
    "हॉलमार्कमध्ये BIS चिन्ह, शुद्धता, HUID आणि सोनाराचे चिन्ह एकत्र असतात.",
    "तोंडाने सांगितलेले 22 कॅरेट, वस्तूवरचे 916 नाही.",
    "HUID अधिकृत हॉलमार्किंग पानावर तपासा.",
  ],
  hmJeweller: "सोनाऱ्याची हॉलमार्क नोंदणी अधिकृत पोर्टलवर होते. ही डेस्क सोनार नोंदवत नाही.",
  gold: "सोने",
  silver: "चांदी",
  platinum: "प्लॅटिनम",
  both900: "900 प्लॅटिनमसाठीही वापरले जाते. धातूचे नाव हॉलमार्कवर असते.",
  gradeLine: "{tag} · {metal} शुद्धता {id}.",
  stEyebrow: "कॅटलॉग",
  stH1: "भारतीय मानक शोध",
  stLede: "उत्पादनाचे नाव लिहा. अधिकृत कॅटलॉगमध्ये ओळ असेल तर शोध सांगतो. नसेल तर स्पष्ट सांगतो.",
  stLabel: "उत्पादन",
  stPh: "सिमेंट, हेल्मेट, लॅपटॉप",
  stSteps: [
    "उत्पादनाचे नाव, किंवा IS क्रमांक माहीत असल्यास.",
    "ओळ या कॅटलॉगमध्ये असेल तरच क्रमांक येतो.",
    "ओळ नसणे म्हणजे येथे नोंद नाही. मानक नाही असे नाही.",
    "छापण्यापूर्वी Know Your Standard वर शीर्षक पाहा.",
  ],
  stHit: "या नावाचे कॅटलॉग शीर्षक. परवाना नाही.",
  stMiss: "या नावाचा कॅटलॉग पिन नाही.",
  stClarify: "एक मानक सांगण्यापूर्वी आणखी एक तपशील हवा.",
  ceEyebrow: "प्रमाणन",
  ceH1: "प्रमाणन प्रक्रिया",
  ceLede: "एक योजना निवडा. टप्पे अधिकृत डेस्ककडे नेतात. हे पान अर्ज भरत नाही.",
  isi: "ISI · योजना-I",
  crs: "CRS · योजना-II",
  isiSteps: [
    "उत्पादनाचे भारतीय मानक Know Your Standard वर पाहा.",
    "Quality Control Order असेल तर थेट अनिवार्य यादी पुन्हा पाहा. हे पान अंदाज करत नाही.",
    "ISI अर्ज MANAK Online वर भरतो.",
    "चाचणी BIS मान्यताप्राप्त प्रयोगशाळेत. नामित चाचणीची व्याप्ती LIMS वर.",
    "मंजुरीनंतर CM/L क्रमांक ISI चिन्हासह छापतो. ही डेस्क मंजुरी देत नाही.",
  ],
  crsSteps: [
    "योजना-II अधिसूचित इलेक्ट्रॉनिक्सची अनिवार्य नोंदणी.",
    "हा ISI चा CM/L परवाना नाही आणि दागिन्याचा HUID नाही.",
    "नोंदणी CRS पोर्टलवर होते.",
    "नोंदणी क्रमांक R- आकाराचा, उदाहरण R-41000001.",
    "ही डेस्क उत्पादन नोंदवत नाही आणि शुल्क घेत नाही.",
  ],
  fmcsSteps: [
    "FMCS परदेशी कारखान्यासाठी आहे ज्याला ISI चिन्ह हवे.",
    "हा देशांतर्गत योजना-I फॉर्म नाही, आणि CRS नाही.",
    "अर्ज अधिकृत BIS डेस्कवर राहतो.",
    "येथील कॅटलॉग शीर्षक FMCS मंजुरी नाही.",
    "ही डेस्क फॉर्म भरत नाही आणि शुल्क सांगत नाही.",
  ],
  openManak: "MANAK उघडा",
  openCrs: "CRS उघडा",
  openBis: "अधिकृत BIS",
  coEyebrow: "तक्रार",
  coH1: "तक्रार नोंदवा",
  coLede: "खोटे किंवा गैरवापरलेले मानक चिन्ह BIS कडे नोंदते, या डेस्ककडे नाही.",
  coSteps: [
    "चिन्हाचा फोटो, सोबतचा क्रमांक, आणि बिल असल्यास ठेवा.",
    "अधिकृत BIS तक्रार पानावर नोंदवा, किंवा complaints@bis.gov.in वर लिहा.",
    "मानक मित्र तक्रार घेत नाही आणि खटला उघडत नाही.",
    "दुकानाचे आश्वासन निकाल नाही. अधिकृत पान आहे.",
  ],
  openComplaint: "BIS तक्रार पान उघडा",
  contactTitle: "प्रकाशित BIS संपर्क",
  contactSteps: [
    "प्रकाशित पत्ता मानक भवन, 9 बहादूर शाह झफर मार्ग, नवी दिल्ली.",
    "तक्रार complaints@bis.gov.in किंवा अधिकृत तक्रार पानावर जाते.",
    "ही डेस्क परवाना अर्ज घेत नाही.",
  ],
});

const GU = pack({
  more: "વધુ",
  huid: "HUID તપાસ",
  huidJob: "ઘરેણાં પરનો 6 અક્ષરનો કોડ લખો.",
  hallmark: "હોલમાર્ક શોધ",
  hallmarkJob: "916 અને 22K જેવી શુદ્ધતા.",
  standards: "ભારતીય ધોરણ શોધ",
  standardsJob: "ઉત્પાદનને કેટલોગ શીર્ષક સાથે મેળવો.",
  certify: "પ્રમાણન પ્રક્રિયા",
  certifyJob: "ISI, CRS અને FMCS — ટૂંકા પગલાં.",
  complaint: "ફરિયાદ નોંધો",
  complaintJob: "શું રાખવું, અને અધિકૃત ડેસ્ક.",
  contact: "સંપર્ક",
  contactJob: "પ્રકાશિત BIS સંપર્ક, આ પાનાના તળિયે.",
  check: "તપાસો",
  pick: "એક પસંદ કરો",
  huidEyebrow: "હોલમાર્ક",
  huidH1: "HUID તપાસ",
  huidLede: "ઘરેણાં પરથી 6 અક્ષરનો કોડ લખો. નોંધ આકાર કહે છે, પછી અધિકૃત પાનું.",
  huidHelp: "ટુકડા પર છપાયેલા છ અક્ષર અને અંક.",
  huidEmpty: "ઘરેણાંનો કોડ લખો.",
  huidOk: "{code} 6 અક્ષરના HUID જેવો આકાર ધરાવે છે.",
  huidBad: "આ કોડ 6 અક્ષરના HUID સાથે મળતો નથી.",
  huidLicence: "આ લાઇસન્સ અથવા નોંધણી નંબર છે, ઘરેણાંનો HUID નથી. CM/L અને R-નંબર માટે ઉત્પાદન તપાસો.",
  huidSteps: [
    "HUID એક હોલમાર્ક થયેલા ટુકડાની ઓળખ છે. ફેક્ટરી લાઇસન્સ નથી.",
    "આ ડેસ્ક ફક્ત આકાર જુએ છે. BIS CARE રજિસ્ટર ખોલતી નથી. આ પાસ કે ફેલ નથી.",
    "અધિકૃત હોલમાર્કિંગ પાના પર એ જ કોડ લખો.",
    "ટુકડા પર BIS ચિહ્ન, શુદ્ધતા અને જ્વેલરનું ચિહ્ન પણ વાંચો.",
  ],
  notLive: "લાઇવ રજિસ્ટર ખોલાયું નથી.",
  openHuid: "હોલમાર્કિંગ ખોલો",
  hmEyebrow: "હોલમાર્ક",
  hmH1: "હોલમાર્ક શોધ",
  hmLede: "916 અથવા 22K લખો. નોંધ ગ્રેડનો અર્થ કહે છે. હાથના ટુકડાનો પુરાવો નથી.",
  hmLabel: "શુદ્ધતા અથવા કેરેટ",
  hmPh: "916 અથવા 22K",
  hmMiss: "નીચેથી ગ્રેડ પસંદ કરો, અથવા 916, 22K, અથવા 925 લખો.",
  hmSteps: [
    "શુદ્ધતા પ્રતિ 1000 ભાગ. 916 એટલે 1000માં 916 ભાગ સોનું.",
    "હોલમાર્કમાં BIS ચિહ્ન, શુદ્ધતા, HUID અને જ્વેલરનું ચિહ્ન સાથે હોય છે.",
    "મોઢે કહેલું 22 કેરેટ, ટુકડા પરનું 916 નથી.",
    "HUID અધિકૃત હોલમાર્કિંગ પાના પર ચકાસો.",
  ],
  hmJeweller: "જ્વેલરની હોલમાર્ક નોંધણી અધિકૃત પોર્ટલ પર થાય છે. આ ડેસ્ક જ્વેલર નોંધતી નથી.",
  gold: "સોનું",
  silver: "ચાંદી",
  platinum: "પ્લેટિનમ",
  both900: "900 પ્લેટિનમ માટે પણ વપરાય છે. ધાતુનું નામ હોલમાર્ક પર હોય છે.",
  gradeLine: "{tag} · {metal} શુદ્ધતા {id}.",
  stEyebrow: "કેટલોગ",
  stH1: "ભારતીય ધોરણ શોધ",
  stLede: "ઉત્પાદનનું નામ લખો. અધિકૃત કેટલોગમાં હરોળ હોય તો શોધ કહે છે. ન હોય તો સ્પષ્ટ કહે છે.",
  stLabel: "ઉત્પાદન",
  stPh: "સિમેન્ટ, હેલ્મેટ, લેપટોપ",
  stSteps: [
    "ઉત્પાદનનું નામ, અથવા IS નંબર જાણતા હો તો.",
    "હરોળ આ કેટલોગમાં હોય ત્યારે જ નંબર આવે.",
    "હરોળ ન હોવી એટલે અહીં રેકોર્ડ નથી. ધોરણ નથી એવું નહીં.",
    "છાપતા પહેલાં Know Your Standard પર શીર્ષક જુઓ.",
  ],
  stHit: "આ નામનું કેટલોગ શીર્ષક. લાઇસન્સ નથી.",
  stMiss: "આ નામનો કેટલોગ પિન નથી.",
  stClarify: "એક ધોરણ નામ આપતા પહેલાં વધુ એક વિગત જોઈએ.",
  ceEyebrow: "પ્રમાણન",
  ceH1: "પ્રમાણન પ્રક્રિયા",
  ceLede: "એક યોજના પસંદ કરો. પગલાં અધિકૃત ડેસ્ક સુધી લઈ જાય. આ પાનું અરજી ભરતું નથી.",
  isi: "ISI · યોજના-I",
  crs: "CRS · યોજના-II",
  isiSteps: [
    "ઉત્પાદનનું ભારતીય ધોરણ Know Your Standard પર જુઓ.",
    "Quality Control Order હોય તો લાઇવ ફરજિયાત યાદી ફરી જુઓ. આ પાનું અનુમાન નથી કરતું.",
    "ISI અરજી MANAK Online પર ભરાય છે.",
    "કસોટી BIS માન્ય પ્રયોગશાળામાં. નામની કસોટીનો વ્યાપ LIMS પર.",
    "મંજૂરી પછી CM/L નંબર ISI ચિહ્ન સાથે છપાય છે. આ ડેસ્ક મંજૂરી આપતી નથી.",
  ],
  crsSteps: [
    "યોજના-II અધિસૂચિત ઇલેક્ટ્રોનિક્સની ફરજિયાત નોંધણી.",
    "આ ISIનો CM/L લાઇસન્સ નથી અને ઘરેણાંનો HUID નથી.",
    "નોંધણી CRS પોર્ટલ પર થાય છે.",
    "નોંધણી નંબર R- આકારનો, જેમ કે R-41000001.",
    "આ ડેસ્ક ઉત્પાદન નોંધતી નથી અને ફી લેતી નથી.",
  ],
  fmcsSteps: [
    "FMCS વિદેશી ફેક્ટરી માટે છે જે ISI ચિહ્ન માંગે છે.",
    "આ ઘરેલું યોજના-I ફોર્મ નથી, અને CRS નથી.",
    "અરજી અધિકૃત BIS ડેસ્ક પર રહે છે.",
    "અહીંનું કેટલોગ શીર્ષક FMCS મંજૂરી નથી.",
    "આ ડેસ્ક ફોર્મ ભરતી નથી અને ફી કહેતી નથી.",
  ],
  openManak: "MANAK ખોલો",
  openCrs: "CRS ખોલો",
  openBis: "અધિકૃત BIS",
  coEyebrow: "ફરિયાદ",
  coH1: "ફરિયાદ નોંધો",
  coLede: "નકલી અથવા દુરુપયોગ થયેલું ધોરણ ચિહ્ન BIS પાસે નોંધાય છે, આ ડેસ્ક પર નહીં.",
  coSteps: [
    "ચિહ્નનો ફોટો, સાથેનો નંબર, અને બિલ હોય તો રાખો.",
    "અધિકૃત BIS ફરિયાદ પાના પર નોંધો, અથવા complaints@bis.gov.in પર લખો.",
    "માનક મિત્ર ફરિયાદ લેતો નથી અને કેસ ખોલતો નથી.",
    "દુકાનનો આશ્વાસન પરિણામ નથી. અધિકૃત પાનું છે.",
  ],
  openComplaint: "BIS ફરિયાદ પાનું ખોલો",
  contactTitle: "પ્રકાશિત BIS સંપર્ક",
  contactSteps: [
    "પ્રકાશિત સરનામું માનક ભવન, 9 બહાદુર શાહ ઝફર માર્ગ, નવી દિલ્હી.",
    "ફરિયાદ complaints@bis.gov.in અથવા અધિકૃત ફરિયાદ પાના પર જાય છે.",
    "આ ડેસ્ક લાઇસન્સ અરજી લેતી નથી.",
  ],
});

const KN = pack({
  more: "ಇನ್ನಷ್ಟು",
  huid: "HUID ಪರಿಶೀಲನೆ",
  huidJob: "ಆಭರಣದ ಮೇಲಿನ 6 ಅಕ್ಷರದ ಕೋಡ್ ನಮೂದಿಸಿ.",
  hallmark: "ಹಾಲ್‌ಮಾರ್ಕ್ ಹುಡುಕಾಟ",
  hallmarkJob: "916 ಮತ್ತು 22K ನಂತಹ ಶುದ್ಧತೆ.",
  standards: "ಭಾರತೀಯ ಮಾನದಂಡ ಹುಡುಕಾಟ",
  standardsJob: "ಉತ್ಪನ್ನವನ್ನು ಕ್ಯಾಟಲಾಗ್ ಶೀರ್ಷಿಕೆಗೆ ಹೊಂದಿಸಿ.",
  certify: "ಪ್ರಮಾಣೀಕರಣ ಪ್ರಕ್ರಿಯೆ",
  certifyJob: "ISI, CRS ಮತ್ತು FMCS — ಚಿಕ್ಕ ಹೆಜ್ಜೆಗಳು.",
  complaint: "ದೂರು ಸಲ್ಲಿಸಿ",
  complaintJob: "ಏನು ಇಡಬೇಕು, ಮತ್ತು ಅಧಿಕೃತ ಮೇಜು.",
  contact: "ಸಂಪರ್ಕ",
  contactJob: "ಪ್ರಕಟಿತ BIS ಸಂಪರ್ಕ, ಈ ಪುಟದ ಕೆಳಗೆ.",
  check: "ಪರಿಶೀಲಿಸಿ",
  pick: "ಒಂದನ್ನು ಆರಿಸಿ",
  huidEyebrow: "ಹಾಲ್‌ಮಾರ್ಕ್",
  huidH1: "HUID ಪರಿಶೀಲನೆ",
  huidLede: "ಆಭರಣದಿಂದ 6 ಅಕ್ಷರದ ಕೋಡ್ ಬರೆಯಿರಿ. ಟಿಪ್ಪಣಿ ಆಕಾರ ಹೇಳುತ್ತದೆ, ನಂತರ ಅಧಿಕೃತ ಪುಟ.",
  huidHelp: "ತುಂಡಿನ ಮೇಲೆ ಮುದ್ರಿತ ಆರು ಅಕ್ಷರ ಮತ್ತು ಅಂಕೆಗಳು.",
  huidEmpty: "ಆಭರಣದ ಕೋಡ್ ನಮೂದಿಸಿ.",
  huidOk: "{code} 6 ಅಕ್ಷರದ HUID ಆಕಾರ.",
  huidBad: "ಈ ಕೋಡ್ 6 ಅಕ್ಷರದ HUID ಗೆ ಹೊಂದುವುದಿಲ್ಲ.",
  huidLicence: "ಇದು ಪರವಾನಗಿ ಅಥವಾ ನೋಂದಣಿ ಸಂಖ್ಯೆ, ಆಭರಣದ HUID ಅಲ್ಲ. CM/L ಮತ್ತು R-ಸಂಖ್ಯೆಗಳಿಗೆ ಉತ್ಪನ್ನ ಪರಿಶೀಲನೆ ಬಳಸಿ.",
  huidSteps: [
    "HUID ಒಂದು ಹಾಲ್‌ಮಾರ್ಕ್ ತುಂಡಿನ ಗುರುತು. ಕಾರ್ಖಾನೆ ಪರವಾನಗಿ ಅಲ್ಲ.",
    "ಈ ಮೇಜು ಆಕಾರ ಮಾತ್ರ ನೋಡುತ್ತದೆ. BIS CARE ದಾಖಲೆ ತೆರೆಯುವುದಿಲ್ಲ. ಇದು ಪಾಸ್ ಅಥವಾ ಫೇಲ್ ಅಲ್ಲ.",
    "ಅಧಿಕೃತ ಹಾಲ್‌ಮಾರ್ಕ್ ಪುಟದಲ್ಲಿ ಅದೇ ಕೋಡ್ ನಮೂದಿಸಿ.",
    "ತುಂಡಿನ ಮೇಲೆ BIS ಗುರುತು, ಶುದ್ಧತೆ ಮತ್ತು ವ್ಯಾಪಾರಿ ಗುರುತನ್ನೂ ಓದಿ.",
  ],
  notLive: "ಲೈವ್ ದಾಖಲೆ ತೆರೆಯಲಿಲ್ಲ.",
  openHuid: "ಹಾಲ್‌ಮಾರ್ಕಿಂಗ್ ತೆರೆಯಿರಿ",
  hmEyebrow: "ಹಾಲ್‌ಮಾರ್ಕ್",
  hmH1: "ಹಾಲ್‌ಮಾರ್ಕ್ ಹುಡುಕಾಟ",
  hmLede: "916 ಅಥವಾ 22K ಬರೆಯಿರಿ. ಟಿಪ್ಪಣಿ ದರ್ಜೆಯ ಅರ್ಥ ಹೇಳುತ್ತದೆ. ಕೈಯಲ್ಲಿರುವ ತುಂಡಿನ ಸಾಕ್ಷ್ಯ ಅಲ್ಲ.",
  hmLabel: "ಶುದ್ಧತೆ ಅಥವಾ ಕ್ಯಾರೆಟ್",
  hmPh: "916 ಅಥವಾ 22K",
  hmMiss: "ಕೆಳಗಿನ ದರ್ಜೆ ಆರಿಸಿ, ಅಥವಾ 916, 22K, ಅಥವಾ 925 ಬರೆಯಿರಿ.",
  hmSteps: [
    "ಶುದ್ಧತೆ 1000ಕ್ಕೆ ಭಾಗಗಳು. 916 ಎಂದರೆ 1000ರಲ್ಲಿ 916 ಭಾಗ ಚಿನ್ನ.",
    "ಹಾಲ್‌ಮಾರ್ಕ್‌ನಲ್ಲಿ BIS ಗುರುತು, ಶುದ್ಧತೆ, HUID ಮತ್ತು ವ್ಯಾಪಾರಿ ಗುರುತು ಒಟ್ಟಿಗೆ ಇರುತ್ತವೆ.",
    "ಬಾಯಿಂದ ಹೇಳಿದ 22 ಕ್ಯಾರೆಟ್, ತುಂಡಿನ ಮೇಲಿನ 916 ಅಲ್ಲ.",
    "HUID ಅನ್ನು ಅಧಿಕೃತ ಹಾಲ್‌ಮಾರ್ಕ್ ಪುಟದಲ್ಲಿ ಖಚಿತಪಡಿಸಿ.",
  ],
  hmJeweller: "ವ್ಯಾಪಾರಿಯ ಹಾಲ್‌ಮಾರ್ಕ್ ನೋಂದಣಿ ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ. ಈ ಮೇಜು ವ್ಯಾಪಾರಿಯನ್ನು ನೋಂದಾಯಿಸುವುದಿಲ್ಲ.",
  gold: "ಚಿನ್ನ",
  silver: "ಬೆಳ್ಳಿ",
  platinum: "ಪ್ಲಾಟಿನಂ",
  both900: "900 ಪ್ಲಾಟಿನಂಗೂ ಬಳಕೆಯಾಗುತ್ತದೆ. ಲೋಹದ ಹೆಸರು ಹಾಲ್‌ಮಾರ್ಕ್ ಮೇಲೆ ಇರುತ್ತದೆ.",
  gradeLine: "{tag} · {metal} ಶುದ್ಧತೆ {id}.",
  stEyebrow: "ಕ್ಯಾಟಲಾಗ್",
  stH1: "ಭಾರತೀಯ ಮಾನದಂಡ ಹುಡುಕಾಟ",
  stLede: "ಉತ್ಪನ್ನದ ಹೆಸರು ಬರೆಯಿರಿ. ಅಧಿಕೃತ ಕ್ಯಾಟಲಾಗ್‌ನಲ್ಲಿ ಸಾಲು ಇದ್ದರೆ ಹುಡುಕಾಟ ಹೇಳುತ್ತದೆ. ಇಲ್ಲದಿದ್ದರೆ ಸ್ಪಷ್ಟವಾಗಿ ಹೇಳುತ್ತದೆ.",
  stLabel: "ಉತ್ಪನ್ನ",
  stPh: "ಸಿಮೆಂಟ್, ಹೆಲ್ಮೆಟ್, ಲ್ಯಾಪ್‌ಟಾಪ್",
  stSteps: [
    "ಉತ್ಪನ್ನದ ಹೆಸರು, ಅಥವಾ ತಿಳಿದಿದ್ದರೆ IS ಸಂಖ್ಯೆ.",
    "ಸಾಲು ಈ ಕ್ಯಾಟಲಾಗ್‌ನಲ್ಲಿ ಇದ್ದರೆ ಮಾತ್ರ ಸಂಖ್ಯೆ ಬರುತ್ತದೆ.",
    "ಸಾಲು ಇಲ್ಲದಿರುವುದು ಇಲ್ಲಿ ದಾಖಲೆ ಇಲ್ಲ ಎಂದು. ಮಾನದಂಡವೇ ಇಲ್ಲ ಎಂದಲ್ಲ.",
    "ಮುದ್ರಿಸುವ ಮೊದಲು Know Your Standard ನಲ್ಲಿ ಶೀರ್ಷಿಕೆ ನೋಡಿ.",
  ],
  stHit: "ಈ ಹೆಸರಿನ ಕ್ಯಾಟಲಾಗ್ ಶೀರ್ಷಿಕೆ. ಪರವಾನಗಿ ಅಲ್ಲ.",
  stMiss: "ಈ ಹೆಸರಿಗೆ ಕ್ಯಾಟಲಾಗ್ ಪಿನ್ ಇಲ್ಲ.",
  stClarify: "ಒಂದು ಮಾನದಂಡ ಹೆಸರಿಸುವ ಮೊದಲು ಇನ್ನೊಂದು ವಿವರ ಬೇಕು.",
  ceEyebrow: "ಪ್ರಮಾಣೀಕರಣ",
  ceH1: "ಪ್ರಮಾಣೀಕರಣ ಪ್ರಕ್ರಿಯೆ",
  ceLede: "ಒಂದು ಯೋಜನೆ ಆರಿಸಿ. ಹೆಜ್ಜೆಗಳು ಅಧಿಕೃತ ಮೇಜಿಗೆ ಕೊಂಡೊಯ್ಯುತ್ತವೆ. ಈ ಪುಟ ಅರ್ಜಿ ಸಲ್ಲಿಸುವುದಿಲ್ಲ.",
  isi: "ISI · ಯೋಜನೆ-I",
  crs: "CRS · ಯೋಜನೆ-II",
  isiSteps: [
    "ಉತ್ಪನ್ನದ ಭಾರತೀಯ ಮಾನದಂಡವನ್ನು Know Your Standard ನಲ್ಲಿ ನೋಡಿ.",
    "Quality Control Order ಇದ್ದರೆ ಲೈವ್ ಕಡ್ಡಾಯ ಪಟ್ಟಿ ಮತ್ತೆ ನೋಡಿ. ಈ ಪುಟ ಊಹಿಸುವುದಿಲ್ಲ.",
    "ISI ಅರ್ಜಿ MANAK Online ನಲ್ಲಿ ಸಲ್ಲಿಸಲಾಗುತ್ತದೆ.",
    "ಪರೀಕ್ಷೆ BIS ಮಾನ್ಯ ಪ್ರಯೋಗಾಲಯದಲ್ಲಿ. ಹೆಸರಿಸಿದ ಪರೀಕ್ಷೆಯ ವ್ಯಾಪ್ತಿ LIMS ನಲ್ಲಿ.",
    "ಮಂಜೂರಾತಿಯ ನಂತರ CM/L ಸಂಖ್ಯೆ ISI ಗುರುತಿನೊಂದಿಗೆ ಮುದ್ರಿತವಾಗುತ್ತದೆ. ಈ ಮೇಜು ಮಂಜೂರು ಮಾಡುವುದಿಲ್ಲ.",
  ],
  crsSteps: [
    "ಯೋಜನೆ-II ಅಧಿಸೂಚಿತ ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್‌ನ ಕಡ್ಡಾಯ ನೋಂದಣಿ.",
    "ಇದು ISI CM/L ಪರವಾನಗಿ ಅಲ್ಲ, ಆಭರಣ HUID ಅಲ್ಲ.",
    "ನೋಂದಣಿ CRS ಪೋರ್ಟಲ್‌ನಲ್ಲಿ.",
    "ನೋಂದಣಿ ಸಂಖ್ಯೆ R- ಆಕಾರ, ಉದಾಹರಣೆ R-41000001.",
    "ಈ ಮೇಜು ಉತ್ಪನ್ನವನ್ನು ನೋಂದಾಯಿಸುವುದಿಲ್ಲ, ಶುಲ್ಕ ತೆಗೆದುಕೊಳ್ಳುವುದಿಲ್ಲ.",
  ],
  fmcsSteps: [
    "FMCS ವಿದೇಶಿ ಕಾರ್ಖಾನೆಗೆ, ISI ಗುರುತು ಬೇಕಾದರೆ.",
    "ಇದು ದೇಶೀಯ ಯೋಜನೆ-I ಅರ್ಜಿ ಅಲ್ಲ, CRS ಅಲ್ಲ.",
    "ಅರ್ಜಿ ಅಧಿಕೃತ BIS ಮೇಜಿನಲ್ಲೇ ಇರುತ್ತದೆ.",
    "ಇಲ್ಲಿನ ಕ್ಯಾಟಲಾಗ್ ಶೀರ್ಷಿಕೆ FMCS ಮಂಜೂರಾತಿ ಅಲ್ಲ.",
    "ಈ ಮೇಜು ಅರ್ಜಿ ಸಲ್ಲಿಸುವುದಿಲ್ಲ, ಶುಲ್ಕ ಹೇಳುವುದಿಲ್ಲ.",
  ],
  openManak: "MANAK ತೆರೆಯಿರಿ",
  openCrs: "CRS ತೆರೆಯಿರಿ",
  openBis: "ಅಧಿಕೃತ BIS",
  coEyebrow: "ದೂರು",
  coH1: "ದೂರು ಸಲ್ಲಿಸಿ",
  coLede: "ನಕಲಿ ಅಥವಾ ದುರುಪಯೋಗದ ಮಾನದಂಡ ಗುರುತು BIS ನಲ್ಲಿ ಸಲ್ಲಿಸಲಾಗುತ್ತದೆ, ಈ ಮೇಜಿನಲ್ಲಿ ಅಲ್ಲ.",
  coSteps: [
    "ಗುರುತಿನ ಫೋಟೋ, ಮುದ್ರಿತ ಸಂಖ್ಯೆ, ಇದ್ದರೆ ಬಿಲ್ ಇಡಿ.",
    "ಅಧಿಕೃತ BIS ದೂರು ಪುಟದಲ್ಲಿ ಸಲ್ಲಿಸಿ, ಅಥವಾ complaints@bis.gov.in ಗೆ ಬರೆಯಿರಿ.",
    "ಮಾನಕ್ ಮಿತ್ರ ದೂರು ಸ್ವೀಕರಿಸುವುದಿಲ್ಲ, ಪ್ರಕರಣ ತೆರೆಯುವುದಿಲ್ಲ.",
    "ಅಂಗಡಿಯ ಭರವಸೆ ಫಲಿತಾಂಶ ಅಲ್ಲ. ಅಧಿಕೃತ ಪುಟ ಫಲಿತಾಂಶ.",
  ],
  openComplaint: "BIS ದೂರು ಪುಟ ತೆರೆಯಿರಿ",
  contactTitle: "ಪ್ರಕಟಿತ BIS ಸಂಪರ್ಕ",
  contactSteps: [
    "ಪ್ರಕಟಿತ ವಿಳಾಸ ಮಾನಕ್ ಭವನ, 9 ಬಹದೂರ್ ಷಾ ಜಫರ್ ಮಾರ್ಗ, ನವದೆಹಲಿ.",
    "ದೂರು complaints@bis.gov.in ಅಥವಾ ಅಧಿಕೃತ ದೂರು ಪುಟಕ್ಕೆ ಹೋಗುತ್ತದೆ.",
    "ಈ ಮೇಜು ಪರವಾನಗಿ ಅರ್ಜಿ ಸ್ವೀಕರಿಸುವುದಿಲ್ಲ.",
  ],
});

const ML = pack({
  more: "കൂടുതൽ",
  huid: "HUID പരിശോധന",
  huidJob: "ആഭരണത്തിലെ 6 അക്ഷര കോഡ് നൽകുക.",
  hallmark: "ഹാൾമാർക്ക് തിരയൽ",
  hallmarkJob: "916, 22K പോലുള്ള ശുദ്ധി.",
  standards: "ഇന്ത്യൻ മാനദണ്ഡ തിരയൽ",
  standardsJob: "ഉൽപ്പന്നത്തെ കാറ്റലോഗ് തലക്കെട്ടുമായി ചേർക്കുക.",
  certify: "സർട്ടിഫിക്കേഷൻ പ്രക്രിയ",
  certifyJob: "ISI, CRS, FMCS — ചെറിയ ഘട്ടങ്ങൾ.",
  complaint: "പരാതി നൽകുക",
  complaintJob: "എന്ത് സൂക്ഷിക്കണം, ഔദ്യോഗിക ഡെസ്ക്.",
  contact: "ബന്ധപ്പെടുക",
  contactJob: "പ്രസിദ്ധീകരിച്ച BIS ബന്ധം, ഈ പേജിന്റെ അടിയിൽ.",
  check: "പരിശോധിക്കുക",
  pick: "ഒന്ന് തിരഞ്ഞെടുക്കുക",
  huidEyebrow: "ഹാൾമാർക്ക്",
  huidH1: "HUID പരിശോധന",
  huidLede: "ആഭരണത്തിൽ നിന്ന് 6 അക്ഷര കോഡ് എഴുതുക. കുറിപ്പ് ആകൃതി പറയും, പിന്നെ ഔദ്യോഗിക പേജ്.",
  huidHelp: "കഷണത്തിൽ അച്ചടിച്ച ആറ് അക്ഷരങ്ങളും അക്കങ്ങളും.",
  huidEmpty: "ആഭരണത്തിന്റെ കോഡ് എഴുതുക.",
  huidOk: "{code} 6 അക്ഷര HUID ആകൃതി.",
  huidBad: "ഈ കോഡ് 6 അക്ഷര HUID ആയി പൊരുത്തപ്പെടുന്നില്ല.",
  huidLicence: "ഇത് ലൈസൻസ് അല്ലെങ്കിൽ രജിസ്ട്രേഷൻ നമ്പർ, ആഭരണ HUID അല്ല. CM/L, R-നമ്പറുകൾക്ക് ഉൽപ്പന്ന പരിശോധന ഉപയോഗിക്കുക.",
  huidSteps: [
    "HUID ഒരു ഹാൾമാർക്ക് കഷണത്തിന്റെ തിരിച്ചറിയൽ. ഫാക്ടറി ലൈസൻസ് അല്ല.",
    "ഈ ഡെസ്ക് ആകൃതി മാത്രം നോക്കും. BIS CARE രജിസ്റ്റർ തുറക്കില്ല. ഇത് പാസോ ഫെയിലോ അല്ല.",
    "ഔദ്യോഗിക ഹാൾമാർക്ക് പേജിൽ അതേ കോഡ് നൽകുക.",
    "കഷണത്തിൽ BIS അടയാളം, ശുദ്ധി, ജ്വല്ലറി അടയാളം എന്നിവയും വായിക്കുക.",
  ],
  notLive: "ലൈവ് രജിസ്റ്റർ തുറന്നില്ല.",
  openHuid: "ഹാൾമാർക്കിങ് തുറക്കുക",
  hmEyebrow: "ഹാൾമാർക്ക്",
  hmH1: "ഹാൾമാർക്ക് തിരയൽ",
  hmLede: "916 അല്ലെങ്കിൽ 22K എഴുതുക. കുറിപ്പ് ഗ്രേഡിന്റെ അർത്ഥം പറയും. കയ്യിലെ കഷണത്തിന്റെ തെളിവല്ല.",
  hmLabel: "ശുദ്ധി അല്ലെങ്കിൽ കാരറ്റ്",
  hmPh: "916 അല്ലെങ്കിൽ 22K",
  hmMiss: "താഴെ നിന്ന് ഗ്രേഡ് തിരഞ്ഞെടുക്കുക, അല്ലെങ്കിൽ 916, 22K, അല്ലെങ്കിൽ 925 എഴുതുക.",
  hmSteps: [
    "ശുദ്ധി 1000-ൽ ഭാഗങ്ങൾ. 916 എന്നാൽ 1000-ൽ 916 ഭാഗം സ്വർണം.",
    "ഹാൾമാർക്കിൽ BIS അടയാളം, ശുദ്ധി, HUID, ജ്വല്ലറി അടയാളം ഒന്നിച്ച് ഉണ്ട്.",
    "വായിൽ പറഞ്ഞ 22 കാരറ്റ്, കഷണത്തിലെ 916 അല്ല.",
    "HUID ഔദ്യോഗിക ഹാൾമാർക്ക് പേജിൽ ഉറപ്പാക്കുക.",
  ],
  hmJeweller: "ജ്വല്ലറിയുടെ ഹാൾമാർക്ക് രജിസ്ട്രേഷൻ ഔദ്യോഗിക പോർട്ടലിലാണ്. ഈ ഡെസ്ക് ജ്വല്ലറിയെ രജിസ്റ്റർ ചെയ്യില്ല.",
  gold: "സ്വർണം",
  silver: "വെള്ളി",
  platinum: "പ്ലാറ്റിനം",
  both900: "900 പ്ലാറ്റിനത്തിനും ഉപയോഗിക്കും. ലോഹത്തിന്റെ പേര് ഹാൾമാർക്കിൽ ഉണ്ടാകും.",
  gradeLine: "{tag} · {metal} ശുദ്ധി {id}.",
  stEyebrow: "കാറ്റലോഗ്",
  stH1: "ഇന്ത്യൻ മാനദണ്ഡ തിരയൽ",
  stLede: "ഉൽപ്പന്നത്തിന്റെ പേര് എഴുതുക. അംഗീകൃത കാറ്റലോഗിൽ വരി ഉണ്ടെങ്കിൽ തിരയൽ പറയും. ഇല്ലെങ്കിൽ വ്യക്തമായി പറയും.",
  stLabel: "ഉൽപ്പന്നം",
  stPh: "സിമൻറ്, ഹെൽമെറ്റ്, ലാപ്‌ടോപ്പ്",
  stSteps: [
    "ഉൽപ്പന്നത്തിന്റെ പേര്, അല്ലെങ്കിൽ അറിയാമെങ്കിൽ IS നമ്പർ.",
    "വരി ഈ കാറ്റലോഗിൽ ഉണ്ടെങ്കിൽ മാത്രമേ നമ്പർ വരൂ.",
    "വരി ഇല്ലെന്നാൽ ഇവിടെ രേഖയില്ല. മാനദണ്ഡം ഇല്ല എന്നല്ല.",
    "അച്ചടിക്കുന്നതിന് മുമ്പ് Know Your Standard-ൽ തലക്കെട്ട് നോക്കുക.",
  ],
  stHit: "ഈ പേരിന്റെ കാറ്റലോഗ് തലക്കെട്ട്. ലൈസൻസ് അല്ല.",
  stMiss: "ഈ പേരിന് കാറ്റലോഗ് പിൻ ഇല്ല.",
  stClarify: "ഒരു മാനദണ്ഡം പേരിടുന്നതിന് മുമ്പ് ഒരു വിവരം കൂടി വേണം.",
  ceEyebrow: "സർട്ടിഫിക്കേഷൻ",
  ceH1: "സർട്ടിഫിക്കേഷൻ പ്രക്രിയ",
  ceLede: "ഒരു സ്കീം തിരഞ്ഞെടുക്കുക. ഘട്ടങ്ങൾ ഔദ്യോഗിക ഡെസ്കിലേക്ക് കൊണ്ടുപോകും. ഈ പേജ് അപേക്ഷ സമർപ്പിക്കില്ല.",
  isi: "ISI · സ്കീം-I",
  crs: "CRS · സ്കീം-II",
  isiSteps: [
    "ഉൽപ്പന്നത്തിന്റെ ഇന്ത്യൻ മാനദണ്ഡം Know Your Standard-ൽ നോക്കുക.",
    "Quality Control Order ഉണ്ടെങ്കിൽ ലൈവ് നിർബന്ധിത പട്ടിക വീണ്ടും നോക്കുക. ഈ പേജ് ഊഹിക്കില്ല.",
    "ISI അപേക്ഷ MANAK Online-ൽ സമർപ്പിക്കും.",
    "പരിശോധന BIS അംഗീകൃത ലാബിൽ. പേരിട്ട പരിശോധനയുടെ പരിധി LIMS-ൽ.",
    "അനുവാദത്തിന് ശേഷം CM/L നമ്പർ ISI അടയാളത്തോടൊപ്പം അച്ചടിക്കും. ഈ ഡെസ്ക് അനുവാദം നൽകില്ല.",
  ],
  crsSteps: [
    "സ്കീം-II അറിയിപ്പുള്ള ഇലക്ട്രോണിക്സിന്റെ നിർബന്ധിത രജിസ്ട്രേഷൻ.",
    "ഇത് ISI CM/L ലൈസൻസ് അല്ല, ആഭരണ HUID അല്ല.",
    "രജിസ്ട്രേഷൻ CRS പോർട്ടലിൽ.",
    "രജിസ്ട്രേഷൻ നമ്പർ R- ആകൃതി, ഉദാഹരണം R-41000001.",
    "ഈ ഡെസ്ക് ഉൽപ്പന്നം രജിസ്റ്റർ ചെയ്യില്ല, ഫീസ് വാങ്ങില്ല.",
  ],
  fmcsSteps: [
    "FMCS വിദേശ ഫാക്ടറിക്ക്, ISI അടയാളം വേണമെങ്കിൽ.",
    "ഇത് ആഭ്യന്തര സ്കീം-I ഫോം അല്ല, CRS അല്ല.",
    "അപേക്ഷ ഔദ്യോഗിക BIS ഡെസ്കിൽ നിൽക്കും.",
    "ഇവിടുത്തെ കാറ്റലോഗ് തലക്കെട്ട് FMCS അനുവാദമല്ല.",
    "ഈ ഡെസ്ക് ഫോം സമർപ്പിക്കില്ല, ഫീസ് പറയില്ല.",
  ],
  openManak: "MANAK തുറക്കുക",
  openCrs: "CRS തുറക്കുക",
  openBis: "ഔദ്യോഗിക BIS",
  coEyebrow: "പരാതി",
  coH1: "പരാതി നൽകുക",
  coLede: "വ്യാജ അല്ലെങ്കിൽ ദുരുപയോഗ മാനദണ്ഡ അടയാളം BIS-ൽ സമർപ്പിക്കും, ഈ ഡെസ്കിൽ അല്ല.",
  coSteps: [
    "അടയാളത്തിന്റെ ഫോട്ടോ, അച്ചടിച്ച നമ്പർ, ബിൽ ഉണ്ടെങ്കിൽ സൂക്ഷിക്കുക.",
    "ഔദ്യോഗിക BIS പരാതി പേജിൽ സമർപ്പിക്കുക, അല്ലെങ്കിൽ complaints@bis.gov.in-ലേക്ക് എഴുതുക.",
    "മാനക് മിത്ര പരാതി സ്വീകരിക്കില്ല, കേസ് തുറക്കില്ല.",
    "കടയുടെ ഉറപ്പ് ഫലമല്ല. ഔദ്യോഗിക പേജാണ് ഫലം.",
  ],
  openComplaint: "BIS പരാതി പേജ് തുറക്കുക",
  contactTitle: "പ്രസിദ്ധീകരിച്ച BIS ബന്ധം",
  contactSteps: [
    "പ്രസിദ്ധീകരിച്ച വിലാസം മാനക് ഭവൻ, 9 ബഹാദൂർ ഷാ സഫർ മാർഗ്, ന്യൂ ഡൽഹി.",
    "പരാതി complaints@bis.gov.in അല്ലെങ്കിൽ ഔദ്യോഗിക പരാതി പേജിലേക്ക് പോകും.",
    "ഈ ഡെസ്ക് ലൈസൻസ് അപേക്ഷ സ്വീകരിക്കില്ല.",
  ],
});

const PA = pack({
  more: "ਹੋਰ",
  huid: "HUID ਜਾਂਚ",
  huidJob: "ਗਹਿਣੇ ਉੱਤੇ ਛਪਿਆ 6 ਅੱਖਰਾਂ ਦਾ ਕੋਡ ਲਿਖੋ।",
  hallmark: "ਹਾਲਮਾਰਕ ਖੋਜ",
  hallmarkJob: "916 ਅਤੇ 22K ਵਰਗੀ ਸ਼ੁੱਧਤਾ।",
  standards: "ਭਾਰਤੀ ਮਿਆਰ ਖੋਜ",
  standardsJob: "ਉਤਪਾਦ ਨੂੰ ਕੈਟਾਲਾਗ ਸਿਰਲੇਖ ਨਾਲ ਮਿਲਾਓ।",
  certify: "ਸਰਟੀਫਿਕੇਸ਼ਨ ਪ੍ਰਕਿਰਿਆ",
  certifyJob: "ISI, CRS ਅਤੇ FMCS — ਛੋਟੇ ਕਦਮ।",
  complaint: "ਸ਼ਿਕਾਇਤ ਦਰਜ",
  complaintJob: "ਕੀ ਰੱਖਣਾ ਹੈ, ਅਤੇ ਅਧਿਕਾਰਤ ਡੈਸਕ।",
  contact: "ਸੰਪਰਕ",
  contactJob: "ਪ੍ਰਕਾਸ਼ਿਤ BIS ਸੰਪਰਕ, ਇਸ ਪੰਨੇ ਦੇ ਹੇਠਾਂ।",
  check: "ਜਾਂਚੋ",
  pick: "ਇੱਕ ਚੁਣੋ",
  huidEyebrow: "ਹਾਲਮਾਰਕ",
  huidH1: "HUID ਜਾਂਚ",
  huidLede: "ਗਹਿਣੇ ਤੋਂ 6 ਅੱਖਰਾਂ ਦਾ ਕੋਡ ਲਿਖੋ। ਨੋਟ ਆਕਾਰ ਦੱਸਦਾ ਹੈ, ਫਿਰ ਅਧਿਕਾਰਤ ਪੰਨਾ।",
  huidHelp: "ਟੁਕੜੇ ਉੱਤੇ ਛਪੇ ਛੇ ਅੱਖਰ ਅਤੇ ਅੰਕ।",
  huidEmpty: "ਗਹਿਣੇ ਦਾ ਕੋਡ ਲਿਖੋ।",
  huidOk: "{code} 6 ਅੱਖਰਾਂ ਵਾਲੇ HUID ਵਰਗਾ ਆਕਾਰ।",
  huidBad: "ਇਹ ਕੋਡ 6 ਅੱਖਰਾਂ ਵਾਲੇ HUID ਨਾਲ ਨਹੀਂ ਮਿਲਦਾ।",
  huidLicence: "ਇਹ ਲਾਇਸੈਂਸ ਜਾਂ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਨੰਬਰ ਹੈ, ਗਹਿਣੇ ਦਾ HUID ਨਹੀਂ। CM/L ਅਤੇ R-ਨੰਬਰ ਲਈ ਉਤਪਾਦ ਜਾਂਚੋ।",
  huidSteps: [
    "HUID ਇੱਕ ਹਾਲਮਾਰਕ ਟੁਕੜੇ ਦੀ ਪਛਾਣ ਹੈ। ਫੈਕਟਰੀ ਲਾਇਸੈਂਸ ਨਹੀਂ।",
    "ਇਹ ਡੈਸਕ ਸਿਰਫ਼ ਆਕਾਰ ਦੇਖਦੀ ਹੈ। BIS CARE ਰਜਿਸਟਰ ਨਹੀਂ ਖੋਲ੍ਹਦੀ। ਇਹ ਪਾਸ ਜਾਂ ਫੇਲ ਨਹੀਂ।",
    "ਅਧਿਕਾਰਤ ਹਾਲਮਾਰਕਿੰਗ ਪੰਨੇ ਉੱਤੇ ਉਹੀ ਕੋਡ ਲਿਖੋ।",
    "ਟੁਕੜੇ ਉੱਤੇ BIS ਚਿੰਨ੍ਹ, ਸ਼ੁੱਧਤਾ ਅਤੇ ਜੌਹਰੀ ਦਾ ਚਿੰਨ੍ਹ ਵੀ ਪੜ੍ਹੋ।",
  ],
  notLive: "ਲਾਈਵ ਰਜਿਸਟਰ ਨਹੀਂ ਖੁਲ੍ਹਿਆ।",
  openHuid: "ਹਾਲਮਾਰਕਿੰਗ ਖੋਲ੍ਹੋ",
  hmEyebrow: "ਹਾਲਮਾਰਕ",
  hmH1: "ਹਾਲਮਾਰਕ ਖੋਜ",
  hmLede: "916 ਜਾਂ 22K ਲਿਖੋ। ਨੋਟ ਗ੍ਰੇਡ ਦਾ ਅਰਥ ਦੱਸਦਾ ਹੈ। ਹੱਥ ਦੇ ਟੁਕੜੇ ਦਾ ਸਬੂਤ ਨਹੀਂ।",
  hmLabel: "ਸ਼ੁੱਧਤਾ ਜਾਂ ਕੈਰੇਟ",
  hmPh: "916 ਜਾਂ 22K",
  hmMiss: "ਹੇਠਾਂ ਤੋਂ ਗ੍ਰੇਡ ਚੁਣੋ, ਜਾਂ 916, 22K, ਜਾਂ 925 ਲਿਖੋ।",
  hmSteps: [
    "ਸ਼ੁੱਧਤਾ ਪ੍ਰਤੀ 1000 ਹਿੱਸੇ। 916 ਦਾ ਅਰਥ 1000 ਵਿੱਚ 916 ਹਿੱਸੇ ਸੋਨਾ।",
    "ਹਾਲਮਾਰਕ ਵਿੱਚ BIS ਚਿੰਨ੍ਹ, ਸ਼ੁੱਧਤਾ, HUID ਅਤੇ ਜੌਹਰੀ ਦਾ ਚਿੰਨ੍ਹ ਇਕੱਠੇ ਹੁੰਦੇ ਹਨ।",
    "ਮੂੰਹੋਂ ਕਿਹਾ 22 ਕੈਰੇਟ, ਟੁਕੜੇ ਉੱਤੇ ਛਪਿਆ 916 ਨਹੀਂ।",
    "HUID ਅਧਿਕਾਰਤ ਹਾਲਮਾਰਕਿੰਗ ਪੰਨੇ ਉੱਤੇ ਪੁਸ਼ਟੀ ਕਰੋ।",
  ],
  hmJeweller: "ਜੌਹਰੀ ਦੀ ਹਾਲਮਾਰਕ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਧਿਕਾਰਤ ਪੋਰਟਲ ਉੱਤੇ ਹੁੰਦੀ ਹੈ। ਇਹ ਡੈਸਕ ਜੌਹਰੀ ਦਰਜ ਨਹੀਂ ਕਰਦੀ।",
  gold: "ਸੋਨਾ",
  silver: "ਚਾਂਦੀ",
  platinum: "ਪਲੈਟੀਨਮ",
  both900: "900 ਪਲੈਟੀਨਮ ਲਈ ਵੀ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ। ਧਾਤ ਦਾ ਨਾਮ ਹਾਲਮਾਰਕ ਉੱਤੇ ਹੁੰਦਾ ਹੈ।",
  gradeLine: "{tag} · {metal} ਸ਼ੁੱਧਤਾ {id}।",
  stEyebrow: "ਕੈਟਾਲਾਗ",
  stH1: "ਭਾਰਤੀ ਮਿਆਰ ਖੋਜ",
  stLede: "ਉਤਪਾਦ ਦਾ ਨਾਮ ਲਿਖੋ। ਅਧਿਕਾਰਤ ਕੈਟਾਲਾਗ ਵਿੱਚ ਕਤਾਰ ਹੋਵੇ ਤਾਂ ਖੋਜ ਦੱਸਦੀ ਹੈ। ਨਾ ਹੋਵੇ ਤਾਂ ਸਾਫ਼ ਦੱਸਦੀ ਹੈ।",
  stLabel: "ਉਤਪਾਦ",
  stPh: "ਸੀਮਿੰਟ, ਹੈਲਮੇਟ, ਲੈਪਟਾਪ",
  stSteps: [
    "ਉਤਪਾਦ ਦਾ ਨਾਮ, ਜਾਂ IS ਨੰਬਰ ਜੇ ਪਹਿਲਾਂ ਤੋਂ ਪਤਾ ਹੋਵੇ।",
    "ਨੰਬਰ ਤਦ ਹੀ ਆਉਂਦਾ ਹੈ ਜਦੋਂ ਕਤਾਰ ਇਸ ਕੈਟਾਲਾਗ ਵਿੱਚ ਹੋਵੇ।",
    "ਕਤਾਰ ਨਾ ਹੋਣਾ ਇੱਥੇ ਰਿਕਾਰਡ ਨਹੀਂ। ਇਹ ਨਹੀਂ ਕਿ ਮਿਆਰ ਹੈ ਹੀ ਨਹੀਂ।",
    "ਛਾਪਣ ਤੋਂ ਪਹਿਲਾਂ Know Your Standard ਉੱਤੇ ਸਿਰਲੇਖ ਵੇਖੋ।",
  ],
  stHit: "ਇਸ ਨਾਮ ਦਾ ਕੈਟਾਲਾਗ ਸਿਰਲੇਖ। ਲਾਇਸੈਂਸ ਨਹੀਂ।",
  stMiss: "ਇਸ ਨਾਮ ਦਾ ਕੈਟਾਲਾਗ ਪਿੰਨ ਨਹੀਂ।",
  stClarify: "ਇੱਕ ਮਿਆਰ ਨਾਮਣ ਤੋਂ ਪਹਿਲਾਂ ਇੱਕ ਹੋਰ ਵੇਰਵਾ ਚਾਹੀਦਾ ਹੈ।",
  ceEyebrow: "ਸਰਟੀਫਿਕੇਸ਼ਨ",
  ceH1: "ਸਰਟੀਫਿਕੇਸ਼ਨ ਪ੍ਰਕਿਰਿਆ",
  ceLede: "ਇੱਕ ਯੋਜਨਾ ਚੁਣੋ। ਕਦਮ ਅਧਿਕਾਰਤ ਡੈਸਕ ਤੱਕ ਲੈ ਜਾਂਦੇ ਹਨ। ਇਹ ਪੰਨਾ ਅਰਜ਼ੀ ਨਹੀਂ ਭਰਦਾ।",
  isi: "ISI · ਯੋਜਨਾ-I",
  crs: "CRS · ਯੋਜਨਾ-II",
  isiSteps: [
    "ਉਤਪਾਦ ਦਾ ਭਾਰਤੀ ਮਿਆਰ Know Your Standard ਉੱਤੇ ਵੇਖੋ।",
    "Quality Control Order ਹੋਵੇ ਤਾਂ ਲਾਈਵ ਲਾਜ਼ਮੀ ਸੂਚੀ ਫਿਰ ਵੇਖੋ। ਇਹ ਪੰਨਾ ਅੰਦਾਜ਼ਾ ਨਹੀਂ ਲਗਾਉਂਦਾ।",
    "ISI ਅਰਜ਼ੀ MANAK Online ਉੱਤੇ ਭਰੀ ਜਾਂਦੀ ਹੈ।",
    "ਜਾਂਚ BIS ਮਾਨਤਾ ਪ੍ਰਾਪਤ ਪ੍ਰਯੋਗਸ਼ਾਲਾ ਵਿੱਚ। ਨਾਮ ਵਾਲੀ ਜਾਂਚ ਦਾ ਦਾਇਰਾ LIMS ਉੱਤੇ।",
    "ਇਜਾਜ਼ਤ ਤੋਂ ਬਾਅਦ CM/L ਨੰਬਰ ISI ਚਿੰਨ੍ਹ ਨਾਲ ਛਪਦਾ ਹੈ। ਇਹ ਡੈਸਕ ਇਜਾਜ਼ਤ ਨਹੀਂ ਦਿੰਦੀ।",
  ],
  crsSteps: [
    "ਯੋਜਨਾ-II ਅਧਿਸੂਚਿਤ ਇਲੈਕਟ੍ਰਾਨਿਕਸ ਦੀ ਲਾਜ਼ਮੀ ਰਜਿਸਟ੍ਰੇਸ਼ਨ।",
    "ਇਹ ISI ਦਾ CM/L ਲਾਇਸੈਂਸ ਨਹੀਂ ਅਤੇ ਗਹਿਣੇ ਦਾ HUID ਨਹੀਂ।",
    "ਰਜਿਸਟ੍ਰੇਸ਼ਨ CRS ਪੋਰਟਲ ਉੱਤੇ ਹੁੰਦੀ ਹੈ।",
    "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਨੰਬਰ R- ਆਕਾਰ ਦਾ, ਜਿਵੇਂ R-41000001।",
    "ਇਹ ਡੈਸਕ ਉਤਪਾਦ ਦਰਜ ਨਹੀਂ ਕਰਦੀ ਅਤੇ ਫੀਸ ਨਹੀਂ ਲੈਂਦੀ।",
  ],
  fmcsSteps: [
    "FMCS ਵਿਦੇਸ਼ੀ ਫੈਕਟਰੀ ਲਈ ਹੈ ਜੋ ISI ਚਿੰਨ੍ਹ ਚਾਹੁੰਦੀ ਹੈ।",
    "ਇਹ ਘਰੇਲੂ ਯੋਜਨਾ-I ਫਾਰਮ ਨਹੀਂ, ਅਤੇ CRS ਨਹੀਂ।",
    "ਅਰਜ਼ੀ ਅਧਿਕਾਰਤ BIS ਡੈਸਕ ਉੱਤੇ ਰਹਿੰਦੀ ਹੈ।",
    "ਇੱਥੋਂ ਦਾ ਕੈਟਾਲਾਗ ਸਿਰਲੇਖ FMCS ਇਜਾਜ਼ਤ ਨਹੀਂ।",
    "ਇਹ ਡੈਸਕ ਫਾਰਮ ਨਹੀਂ ਭਰਦੀ ਅਤੇ ਫੀਸ ਨਹੀਂ ਦੱਸਦੀ।",
  ],
  openManak: "MANAK ਖੋਲ੍ਹੋ",
  openCrs: "CRS ਖੋਲ੍ਹੋ",
  openBis: "ਅਧਿਕਾਰਤ BIS",
  coEyebrow: "ਸ਼ਿਕਾਇਤ",
  coH1: "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
  coLede: "ਨਕਲੀ ਜਾਂ ਗਲਤ ਵਰਤਿਆ ਮਿਆਰ ਚਿੰਨ੍ਹ BIS ਕੋਲ ਦਰਜ ਹੁੰਦਾ ਹੈ, ਇਸ ਡੈਸਕ ਉੱਤੇ ਨਹੀਂ।",
  coSteps: [
    "ਚਿੰਨ੍ਹ ਦੀ ਫੋਟੋ, ਨਾਲ ਛਪਿਆ ਨੰਬਰ, ਅਤੇ ਬਿੱਲ ਹੋਵੇ ਤਾਂ ਰੱਖੋ।",
    "ਅਧਿਕਾਰਤ BIS ਸ਼ਿਕਾਇਤ ਪੰਨੇ ਉੱਤੇ ਦਰਜ ਕਰੋ, ਜਾਂ complaints@bis.gov.in ਉੱਤੇ ਲਿਖੋ।",
    "ਮਾਨਕ ਮਿੱਤਰ ਸ਼ਿਕਾਇਤ ਨਹੀਂ ਲੈਂਦਾ ਅਤੇ ਕੇਸ ਨਹੀਂ ਖੋਲ੍ਹਦਾ।",
    "ਦੁਕਾਨ ਦਾ ਭਰੋਸਾ ਨਤੀਜਾ ਨਹੀਂ। ਅਧਿਕਾਰਤ ਪੰਨਾ ਹੈ।",
  ],
  openComplaint: "BIS ਸ਼ਿਕਾਇਤ ਪੰਨਾ ਖੋਲ੍ਹੋ",
  contactTitle: "ਪ੍ਰਕਾਸ਼ਿਤ BIS ਸੰਪਰਕ",
  contactSteps: [
    "ਪ੍ਰਕਾਸ਼ਿਤ ਪਤਾ ਮਾਨਕ ਭਵਨ, 9 ਬਹਾਦੁਰ ਸ਼ਾਹ ਜ਼ਫਰ ਮਾਰਗ, ਨਵੀਂ ਦਿੱਲੀ।",
    "ਸ਼ਿਕਾਇਤ complaints@bis.gov.in ਜਾਂ ਅਧਿਕਾਰਤ ਸ਼ਿਕਾਇਤ ਪੰਨੇ ਉੱਤੇ ਜਾਂਦੀ ਹੈ।",
    "ਇਹ ਡੈਸਕ ਲਾਇਸੈਂਸ ਅਰਜ਼ੀ ਨਹੀਂ ਲੈਂਦੀ।",
  ],
});

const UR = pack({
  more: "مزید",
  huid: "HUID تصدیق",
  huidJob: "زیور پر چھپا 6 حرفی کوڈ لکھیں۔",
  hallmark: "ہال مارک تلاش",
  hallmarkJob: "916 اور 22K جیسی پاکیزگی۔",
  standards: "بھارتی معیار تلاش",
  standardsJob: "مصنوع کو کیٹلاگ عنوان سے ملائیں۔",
  certify: "سرٹیفیکیشن طریقہ",
  certifyJob: "ISI، CRS اور FMCS — مختصر قدم۔",
  complaint: "شکایت درج کریں",
  complaintJob: "کیا رکھیں، اور سرکاری ڈیسک۔",
  contact: "رابطہ",
  contactJob: "شائع شدہ BIS رابطہ، اس صفحے کے نیچے۔",
  check: "جانچیں",
  pick: "ایک چنیں",
  huidEyebrow: "ہال مارک",
  huidH1: "HUID تصدیق",
  huidLede: "زیور سے 6 حرفی کوڈ لکھیں۔ نوٹ شکل بتاتا ہے، پھر سرکاری صفحہ۔",
  huidHelp: "ٹکڑے پر چھپے چھ حروف اور ہندسے۔",
  huidEmpty: "زیور کا کوڈ لکھیں۔",
  huidOk: "{code} کی شکل 6 حرفی HUID جیسی ہے۔",
  huidBad: "یہ کوڈ 6 حرفی HUID سے نہیں ملتا۔",
  huidLicence: "یہ لائسنس یا رجسٹریشن نمبر ہے، زیور کا HUID نہیں۔ CM/L اور R-نمبر کے لیے مصنوع جانچیں۔",
  huidSteps: [
    "HUID ایک ہال مارک ٹکڑے کی پہچان ہے۔ فیکٹری لائسنس نہیں۔",
    "یہ ڈیسک صرف شکل دیکھتی ہے۔ BIS CARE رجسٹر نہیں کھلتا۔ یہ پاس یا فیل نہیں۔",
    "سرکاری ہال مارکنگ صفحے پر وہی کوڈ لکھیں۔",
    "ٹکڑے پر BIS نشان، پاکیزگی اور جوہری کا نشان بھی پڑھیں۔",
  ],
  notLive: "لائیو رجسٹر نہیں کھلا۔",
  openHuid: "ہال مارکنگ کھولیں",
  hmEyebrow: "ہال مارک",
  hmH1: "ہال مارک تلاش",
  hmLede: "916 یا 22K لکھیں۔ نوٹ گریڈ کا مطلب بتاتا ہے۔ ہاتھ کے ٹکڑے کا ثبوت نہیں۔",
  hmLabel: "پاکیزگی یا کیرٹ",
  hmPh: "916 یا 22K",
  hmMiss: "نیچے سے گریڈ چنیں، یا 916، 22K، یا 925 لکھیں۔",
  hmSteps: [
    "پاکیزگی فی 1000 حصے۔ 916 کا مطلب 1000 میں 916 حصے سونا۔",
    "ہال مارک میں BIS نشان، پاکیزگی، HUID اور جوہری کا نشان ساتھ ہوتے ہیں۔",
    "منہ سے کہا 22 کیرٹ، ٹکڑے پر چھپا 916 نہیں۔",
    "HUID سرکاری ہال مارکنگ صفحے پر تصدیق کریں۔",
  ],
  hmJeweller: "جوہری کی ہال مارک رجسٹریشن سرکاری پورٹل پر ہوتی ہے۔ یہ ڈیسک جوہری درج نہیں کرتی۔",
  gold: "سونا",
  silver: "چاندی",
  platinum: "پلاٹینم",
  both900: "900 پلاٹینم کے لیے بھی ہے۔ دھات کا نام ہال مارک پر ہوتا ہے۔",
  gradeLine: "{tag} · {metal} پاکیزگی {id}۔",
  stEyebrow: "کیٹلاگ",
  stH1: "بھارتی معیار تلاش",
  stLede: "مصنوع کا نام لکھیں۔ مجاز کیٹلاگ میں قطار ہو تو تلاش بتاتی ہے۔ نہ ہو تو صاف کہتی ہے۔",
  stLabel: "مصنوع",
  stPh: "سیمنٹ، ہیلمٹ، لیپ ٹاپ",
  stSteps: [
    "مصنوع کا نام لکھیں، یا IS نمبر اگر پہلے سے معلوم ہو۔",
    "نمبر تبھی آتا ہے جب قطار اس کیٹلاگ میں ہو۔",
    "قطار نہ ہونا یہاں ریکارڈ نہیں۔ یہ نہیں کہ معیار ہے ہی نہیں۔",
    "چھاپنے سے پہلے Know Your Standard پر عنوان دیکھیں۔",
  ],
  stHit: "اس نام کا کیٹلاگ عنوان۔ لائسنس نہیں۔",
  stMiss: "اس نام کا کیٹلاگ پن نہیں۔",
  stClarify: "ایک معیار نامنے سے پہلے ایک اور تفصیل چاہیے۔",
  ceEyebrow: "سرٹیفیکیشن",
  ceH1: "سرٹیفیکیشن طریقہ",
  ceLede: "ایک اسکیم چنیں۔ قدم سرکاری ڈیسک تک لے جاتے ہیں۔ یہ صفحہ درخواست نہیں بھرتا۔",
  isi: "ISI · اسکیم-I",
  crs: "CRS · اسکیم-II",
  isiSteps: [
    "مصنوع کا بھارتی معیار Know Your Standard پر دیکھیں۔",
    "Quality Control Order ہو تو لائیو لازمی فہرست دوبارہ دیکھیں۔ یہ صفحہ اندازہ نہیں لگاتا۔",
    "ISI درخواست MANAK Online پر بھری جاتی ہے۔",
    "جانچ BIS تسلیم شدہ تجربہ گاہ میں۔ نام والی جانچ کا دائرہ LIMS پر۔",
    "منظوری کے بعد CM/L نمبر ISI نشان کے ساتھ چھپتا ہے۔ یہ ڈیسک منظوری نہیں دیتی۔",
  ],
  crsSteps: [
    "اسکیم-II مطلع شدہ الیکٹرانکس کی لازمی رجسٹریشن ہے۔",
    "یہ ISI کا CM/L لائسنس نہیں اور زیور کا HUID نہیں۔",
    "رجسٹریشن CRS پورٹل پر ہوتی ہے۔",
    "رجسٹریشن نمبر R- شکل کا ہوتا ہے، جیسے R-41000001۔",
    "یہ ڈیسک مصنوع درج نہیں کرتی اور فیس نہیں لیتی۔",
  ],
  fmcsSteps: [
    "FMCS غیر ملکی فیکٹری کے لیے ہے جو ISI نشان چاہتی ہے۔",
    "یہ ملکی اسکیم-I فارم نہیں، اور CRS نہیں۔",
    "درخواست سرکاری BIS ڈیسک پر رہتی ہے۔",
    "یہاں کا کیٹلاگ عنوان FMCS منظوری نہیں۔",
    "یہ ڈیسک فارم نہیں بھرتی اور فیس نہیں بتاتی۔",
  ],
  openManak: "MANAK کھولیں",
  openCrs: "CRS کھولیں",
  openBis: "سرکاری BIS",
  coEyebrow: "شکایت",
  coH1: "شکایت درج کریں",
  coLede: "جعلی یا غلط استعمال شدہ معیار نشان BIS کے پاس درج ہوتا ہے، اس ڈیسک پر نہیں۔",
  coSteps: [
    "نشان کی تصویر، ساتھ چھپا نمبر، اور بل ہو تو رکھیں۔",
    "سرکاری BIS شکایت صفحے پر درج کریں، یا complaints@bis.gov.in پر لکھیں۔",
    "مانک متر شکایت نہیں لیتا اور مقدمہ نہیں کھولتا۔",
    "دکان کا یقین نتیجہ نہیں۔ سرکاری صفحہ ہے۔",
  ],
  openComplaint: "BIS شکایت صفحہ کھولیں",
  contactTitle: "شائع شدہ BIS رابطہ",
  contactSteps: [
    "شائع شدہ پتہ مانک بھون، 9 بہادر شاہ ظفر مارگ، نئی دہلی۔",
    "شکایت complaints@bis.gov.in یا سرکاری شکایت صفحے پر جاتی ہے۔",
    "یہ ڈیسک لائسنس درخواست نہیں لیتی۔",
  ],
});

const ORC = pack({
  more: "ଅଧିକ",
  huid: "HUID ଯାଞ୍ଚ",
  huidJob: "ଗହଣାରେ ଥିବା 6 ଅକ୍ଷର କୋଡ୍ ଲେଖନ୍ତୁ।",
  hallmark: "ହଲମାର୍କ ଖୋଜ",
  hallmarkJob: "916 ଓ 22K ପରି ଶୁଦ୍ଧତା।",
  standards: "ଭାରତୀୟ ମାନକ ଖୋଜ",
  standardsJob: "ଉତ୍ପାଦକୁ କାଟାଲଗ ଶୀର୍ଷକ ସହ ମିଳାନ୍ତୁ।",
  certify: "ପ୍ରମାଣପତ୍ର ପ୍ରକ୍ରିୟା",
  certifyJob: "ISI, CRS ଓ FMCS — ଛୋଟ ପଦକ୍ଷେପ।",
  complaint: "ଅଭିଯୋଗ",
  complaintJob: "କଣ ରଖିବେ, ଓ ସରକାରୀ ଡେସ୍କ।",
  contact: "ଯୋଗାଯୋଗ",
  contactJob: "ପ୍ରକାଶିତ BIS ଯୋଗାଯୋଗ, ଏହି ପୃଷ୍ଠା ତଳେ।",
  check: "ଯାଞ୍ଚ",
  pick: "ଗୋଟିଏ ବାଛନ୍ତୁ",
  huidEyebrow: "ହଲମାର୍କ",
  huidH1: "HUID ଯାଞ୍ଚ",
  huidLede: "ଗହଣାରୁ 6 ଅକ୍ଷର କୋଡ୍ ଲେଖନ୍ତୁ। ନୋଟ୍ ଆକାର କହେ, ତାପରେ ସରକାରୀ ପୃଷ୍ଠା।",
  huidHelp: "ଟୁକୁଡ଼ାରେ ଛପା ଛଅ ଅକ୍ଷର ଓ ସଂଖ୍ୟା।",
  huidEmpty: "ଗହଣାର କୋଡ୍ ଲେଖନ୍ତୁ।",
  huidOk: "{code} 6 ଅକ୍ଷର HUID ଆକାର।",
  huidBad: "ଏହି କୋଡ୍ 6 ଅକ୍ଷର HUID ସହ ମିଳେ ନାହିଁ।",
  huidLicence: "ଏହା ଲାଇସେନ୍ସ କିମ୍ବା ପଞ୍ଜୀକରଣ ସଂଖ୍ୟା, ଗହଣା HUID ନୁହେଁ। CM/L ଓ R-ସଂଖ୍ୟା ପାଇଁ ଉତ୍ପାଦ ଯାଞ୍ଚ।",
  huidSteps: [
    "HUID ଗୋଟିଏ ହଲମାର୍କ ଟୁକୁଡ଼ାର ପରିଚୟ। କାରଖାନା ଲାଇସେନ୍ସ ନୁହେଁ।",
    "ଏହି ଡେସ୍କ କେବଳ ଆକାର ଦେଖେ। BIS CARE ରେଜିଷ୍ଟର ଖୋଲେ ନାହିଁ। ଏହା ପାସ୍ କି ଫେଲ୍ ନୁହେଁ।",
    "ସରକାରୀ ହଲମାର୍କିଂ ପୃଷ୍ଠାରେ ସେହି କୋଡ୍ ଦିଅନ୍ତୁ।",
    "ଟୁକୁଡ଼ାରେ BIS ଚିହ୍ନ, ଶୁଦ୍ଧତା ଓ ଜୁଏଲର ଚିହ୍ନ ମଧ୍ୟ ପଢ଼ନ୍ତୁ।",
  ],
  notLive: "ଲାଇଭ୍ ରେଜିଷ୍ଟର ଖୋଲାଯାଇ ନାହିଁ।",
  openHuid: "ହଲମାର୍କିଂ ଖୋଲନ୍ତୁ",
  hmEyebrow: "ହଲମାର୍କ",
  hmH1: "ହଲମାର୍କ ଖୋଜ",
  hmLede: "916 କିମ୍ବା 22K ଲେଖନ୍ତୁ। ନୋଟ୍ ଗ୍ରେଡ୍ ଅର୍ଥ କହେ। ହାତର ଟୁକୁଡ଼ାର ପ୍ରମାଣ ନୁହେଁ।",
  hmLabel: "ଶୁଦ୍ଧତା କିମ୍ବା କ୍ୟାରେଟ୍",
  hmPh: "916 କିମ୍ବା 22K",
  hmMiss: "ତଳୁ ଗ୍ରେଡ୍ ବାଛନ୍ତୁ, କିମ୍ବା 916, 22K, କିମ୍ବା 925 ଲେଖନ୍ତୁ।",
  hmSteps: [
    "ଶୁଦ୍ଧତା ପ୍ରତି 1000 ଭାଗ। 916 ଅର୍ଥ 1000ରେ 916 ଭାଗ ସୁନା।",
    "ହଲମାର୍କରେ BIS ଚିହ୍ନ, ଶୁଦ୍ଧତା, HUID ଓ ଜୁଏଲର ଚିହ୍ନ ଏକାଠି।",
    "ମୁହଁରେ କହା 22 କ୍ୟାରେଟ୍, ଟୁକୁଡ଼ାରେ 916 ନୁହେଁ।",
    "HUID ସରକାରୀ ହଲମାର୍କିଂ ପୃଷ୍ଠାରେ ନିଶ୍ଚିତ କରନ୍ତୁ।",
  ],
  hmJeweller: "ଜୁଏଲରଙ୍କ ହଲମାର୍କ ପଞ୍ଜୀକରଣ ସରକାରୀ ପୋର୍ଟାଲରେ। ଏହି ଡେସ୍କ ଜୁଏଲର ପଞ୍ଜିକୃତ କରେ ନାହିଁ।",
  gold: "ସୁନା",
  silver: "ରୂପା",
  platinum: "ପ୍ଲାଟିନମ୍",
  both900: "900 ପ୍ଲାଟିନମ୍ ପାଇଁ ମଧ୍ୟ। ଧାତୁ ନାମ ହଲମାର୍କରେ ଥାଏ।",
  gradeLine: "{tag} · {metal} ଶୁଦ୍ଧତା {id}।",
  stEyebrow: "କାଟାଲଗ",
  stH1: "ଭାରତୀୟ ମାନକ ଖୋଜ",
  stLede: "ଉତ୍ପାଦ ନାମ ଲେଖନ୍ତୁ। ଅଧିକୃତ କାଟାଲଗରେ ଧାଡ଼ି ଥିଲେ ଖୋଜ କହେ। ନଥିଲେ ସ୍ପଷ୍ଟ କହେ।",
  stLabel: "ଉତ୍ପାଦ",
  stPh: "ସିମେଣ୍ଟ, ହେଲମେଟ, ଲାପଟପ",
  stSteps: [
    "ଉତ୍ପାଦ ନାମ, କିମ୍ବା IS ସଂଖ୍ୟା ଜଣାଥିଲେ।",
    "ଧାଡ଼ି ଏହି କାଟାଲଗରେ ଥିଲେ ହିଁ ସଂଖ୍ୟା ଆସେ।",
    "ଧାଡ଼ି ନଥିବା ଅର୍ଥ ଏଠାରେ ରେକର୍ଡ ନାହିଁ। ମାନକ ନାହିଁ ବୋଲି ନୁହେଁ।",
    "ଛାପିବା ପୂର୍ବରୁ Know Your Standardରେ ଶୀର୍ଷକ ଦେଖନ୍ତୁ।",
  ],
  stHit: "ଏହି ନାମର କାଟାଲଗ ଶୀର୍ଷକ। ଲାଇସେନ୍ସ ନୁହେଁ।",
  stMiss: "ଏହି ନାମର କାଟାଲଗ ପିନ୍ ନାହିଁ।",
  stClarify: "ଗୋଟିଏ ମାନକ ନାମିବା ପୂର୍ବରୁ ଆଉ ଗୋଟିଏ ବିବରଣୀ ଦରକାର।",
  ceEyebrow: "ପ୍ରମାଣପତ୍ର",
  ceH1: "ପ୍ରମାଣପତ୍ର ପ୍ରକ୍ରିୟା",
  ceLede: "ଗୋଟିଏ ଯୋଜନା ବାଛନ୍ତୁ। ପଦକ୍ଷେପ ସରକାରୀ ଡେସ୍କକୁ ନେଇଯାଏ। ଏହି ପୃଷ୍ଠା ଆବେଦନ ଭରେ ନାହିଁ।",
  isi: "ISI · ଯୋଜନା-I",
  crs: "CRS · ଯୋଜନା-II",
  isiSteps: [
    "ଉତ୍ପାଦର ଭାରତୀୟ ମାନକ Know Your Standardରେ ଦେଖନ୍ତୁ।",
    "Quality Control Order ଥିଲେ ଲାଇଭ୍ ବାଧ୍ୟତାମୂଳକ ତାଲିକା ପୁଣି ଦେଖନ୍ତୁ। ଏହି ପୃଷ୍ଠା ଅନୁମାନ କରେ ନାହିଁ।",
    "ISI ଆବେଦନ MANAK Onlineରେ।",
    "ପରୀକ୍ଷା BIS ସ୍ୱୀକୃତ ଲ୍ୟାବରେ। ନାମିତ ପରୀକ୍ଷା ପରିସର LIMSରେ।",
    "ଅନୁମୋଦନ ପରେ CM/L ସଂଖ୍ୟା ISI ଚିହ୍ନ ସହ ଛପେ। ଏହି ଡେସ୍କ ଅନୁମୋଦନ ଦେଇ ନଥାଏ।",
  ],
  crsSteps: [
    "ଯୋଜନା-II ବିଜ୍ଞପ୍ତ ଇଲେକ୍ଟ୍ରୋନିକ୍ସର ବାଧ୍ୟତାମୂଳକ ପଞ୍ଜୀକରଣ।",
    "ଏହା ISI CM/L ଲାଇସେନ୍ସ ନୁହେଁ, ଗହଣା HUID ନୁହେଁ।",
    "ପଞ୍ଜୀକରଣ CRS ପୋର୍ଟାଲରେ।",
    "ପଞ୍ଜୀକରଣ ସଂଖ୍ୟା R- ଆକାର, ଯେପରି R-41000001।",
    "ଏହି ଡେସ୍କ ଉତ୍ପାଦ ପଞ୍ଜିକୃତ କରେ ନାହିଁ, ଶୁଳ୍କ ନିଏ ନାହିଁ।",
  ],
  fmcsSteps: [
    "FMCS ବିଦେଶୀ କାରଖାନା ପାଇଁ, ISI ଚିହ୍ନ ଚାହିଁଲେ।",
    "ଏହା ଘରୋଇ ଯୋଜନା-I ଫର୍ମ ନୁହେଁ, CRS ନୁହେଁ।",
    "ଆବେଦନ ସରକାରୀ BIS ଡେସ୍କରେ ରହେ।",
    "ଏଠାର କାଟାଲଗ ଶୀର୍ଷକ FMCS ଅନୁମୋଦନ ନୁହେଁ।",
    "ଏହି ଡେସ୍କ ଫର୍ମ ଭରେ ନାହିଁ, ଶୁଳ୍କ କହେ ନାହିଁ।",
  ],
  openManak: "MANAK ଖୋଲନ୍ତୁ",
  openCrs: "CRS ଖୋଲନ୍ତୁ",
  openBis: "ସରକାରୀ BIS",
  coEyebrow: "ଅଭିଯୋଗ",
  coH1: "ଅଭିଯୋଗ ଦାଖଲ",
  coLede: "ନକଲି କିମ୍ବା ଅପବ୍ୟବହାର ମାନକ ଚିହ୍ନ BIS ପାଖରେ ଦାଖଲ, ଏହି ଡେସ୍କରେ ନୁହେଁ।",
  coSteps: [
    "ଚିହ୍ନର ଫଟୋ, ସହ ସଂଖ୍ୟା, ଓ ବିଲ୍ ଥିଲେ ରଖନ୍ତୁ।",
    "ସରକାରୀ BIS ଅଭିଯୋଗ ପୃଷ୍ଠାରେ ଦାଖଲ କରନ୍ତୁ, କିମ୍ବା complaints@bis.gov.inକୁ ଲେଖନ୍ତୁ।",
    "ମାନକ ମିତ୍ର ଅଭିଯୋଗ ନେଇ ନଥାଏ, ମାମଲା ଖୋଲେ ନାହିଁ।",
    "ଦୋକାନ ଆଶ୍ୱାସନ ଫଳ ନୁହେଁ। ସରକାରୀ ପୃଷ୍ଠା ଫଳ।",
  ],
  openComplaint: "BIS ଅଭିଯୋଗ ପୃଷ୍ଠା ଖୋଲନ୍ତୁ",
  contactTitle: "ପ୍ରକାଶିତ BIS ଯୋଗାଯୋଗ",
  contactSteps: [
    "ପ୍ରକାଶିତ ଠିକଣା ମାନକ ଭବନ, 9 ବହାଦୁର ଶାହ ଜଫର ମାର୍ଗ, ନୂଆ ଦିଲ୍ଲୀ।",
    "ଅଭିଯୋଗ complaints@bis.gov.in କିମ୍ବା ସରକାରୀ ଅଭିଯୋଗ ପୃଷ୍ଠାକୁ ଯାଏ।",
    "ଏହି ଡେସ୍କ ଲାଇସେନ୍ସ ଆବେଦନ ନେଇ ନଥାଏ।",
  ],
});

const BY: Record<AppLang, MoreCopy> = {
  en: EN,
  hi: HI,
  bn: BN,
  ta: TA,
  te: TE,
  mr: MR,
  gu: GU,
  kn: KN,
  ml: ML,
  pa: PA,
  ur: UR,
  or: ORC,
};

export function moreCopy(lang: AppLang): MoreCopy {
  return BY[lang] ?? EN;
}
